port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-GamrD
  type: ss
  server: 46.17.45.228
  port: 11111
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-fienJ
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-qwB8r
  type: vmess
  server: 195.154.40.247
  port: 33639
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-4Xtle
  type: vmess
  server: web.51.la
  port: 443
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-KhcOw
  type: vmess
  server: web.51.la
  port: 443
  uuid: e0c6b3b7-9f5b-4bd6-9abf-260663aa4f1b
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-eXsGo
  type: vmess
  server: web.51.la
  port: 443
  uuid: c6e84072-2e69-4928-90af-436b3fcd0663
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: SS-Wrmkm
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
- name: VMESS-yl4PC
  type: vmess
  server: tls.03.node-for-bigairport.win
  port: 32443
  uuid: 5ac8224f-6126-4ffb-9fad-97e3207f8c33
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: ''
    headers:
      Host: tls.03.node-for-bigairport.win
- name: VMESS-sQmr0
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-S3udA
  type: vmess
  server: 183.236.51.38
  port: 49302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-bWwzz
  type: vmess
  server: xcvg65.999815.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: ''
- name: VMESS-1KcwV
  type: vmess
  server: b79d3418-sux8g0-swe4j1-1rfon.cm5.p5pv.com
  port: 17232
  uuid: aed1cc24-351d-11ef-ba52-f23c9164ca5d
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: b79d3418-sux8g0-swe4j1-1rfon.cm5.p5pv.com
- name: VMESS-v7SPv
  type: vmess
  server: xcdvfrr54.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: ''
- name: VMESS-ZZMdz
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 118287d2-e968-42e1-80d0-12fa2f5d38d6
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: sahand.serveminecraft.net
- name: VMESS-sT31f
  type: vmess
  server: tls.04.node-for-bigairport.win
  port: 33443
  uuid: 5ac8224f-6126-4ffb-9fad-97e3207f8c33
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: ''
    headers:
      Host: tls.04.node-for-bigairport.win
- name: VMESS-n7f6L
  type: vmess
  server: de01.sh-cloudflare.sbs
  port: 2096
  uuid: b3928f8d-ea81-4d75-bcec-4016a072adff
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: de01.sh-cloudflare.sbs
- name: Trojan-j7hme
  type: trojan
  server: 104.21.71.112
  port: 443
  password: 895552fa-6284-4c1d-ba00-3944e0c7c626
  params: 'sni: CFR56ty7890.288288.sHOP, type: ws, path: /By7cEmOrNRS58yeduy9AOG,
    host: cfr56ty7890.288288.shop'
- name: Trojan-EJNVi
  type: trojan
  server: 172.67.133.248
  port: 443
  password: f0f6e76e-e5fe-4e2c-9faf-34832e021eae
  params: 'sni: DDd.890604.FIlEGear-sG.Me, type: ws, path: /mZr1mA5hub7QHHkQBzYO,
    host: ddd.890604.filegear-sg.me'
- name: Trojan-7acvL
  type: trojan
  server: 172.67.144.126
  port: 443
  password: 895552fa-6284-4c1d-ba00-3944e0c7c626
  params: 'sni: CFR56ty7890.288288.sHOP, type: ws, path: /By7cEmOrNRS58yeduy9AOG,
    host: cfr56ty7890.288288.shop'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-GamrD
  - SSR-fienJ
  - VMESS-qwB8r
  - VMESS-4Xtle
  - VMESS-KhcOw
  - VMESS-eXsGo
  - SS-Wrmkm
  - VMESS-yl4PC
  - VMESS-sQmr0
  - VMESS-S3udA
  - VMESS-bWwzz
  - VMESS-1KcwV
  - VMESS-v7SPv
  - VMESS-ZZMdz
  - VMESS-sT31f
  - VMESS-n7f6L
  - Trojan-j7hme
  - Trojan-EJNVi
  - Trojan-7acvL
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-GamrD
  - SSR-fienJ
  - VMESS-qwB8r
  - VMESS-4Xtle
  - VMESS-KhcOw
  - VMESS-eXsGo
  - SS-Wrmkm
  - VMESS-yl4PC
  - VMESS-sQmr0
  - VMESS-S3udA
  - VMESS-bWwzz
  - VMESS-1KcwV
  - VMESS-v7SPv
  - VMESS-ZZMdz
  - VMESS-sT31f
  - VMESS-n7f6L
  - Trojan-j7hme
  - Trojan-EJNVi
  - Trojan-7acvL
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
