port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-Yo6dN
  type: ss
  server: 46.17.45.228
  port: 11111
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-CHdRJ
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-bqRwZ
  type: vmess
  server: 195.154.40.247
  port: 19750
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-pbqy8
  type: vmess
  server: web.51.la
  port: 443
  uuid: e0c6b3b7-9f5b-4bd6-9abf-260663aa4f1b
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-rAxiE
  type: vmess
  server: web.51.la
  port: 443
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-0ACRk
  type: vmess
  server: web.51.la
  port: 443
  uuid: c6e84072-2e69-4928-90af-436b3fcd0663
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: SS-Cn0XF
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 16011
  cipher: aes-256-gcm
  password: FPPX8Y4YZRLOB5CP
- name: SS-VzWlt
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
- name: SS-wAPj8
  type: ss
  server: 104.167.197.25
  port: 57456
  cipher: chacha20-ietf-poly1305
  password: 360e21d21977dc11
- name: VMESS-EROjb
  type: vmess
  server: 141.147.95.94
  port: 443
  uuid: 9b456c2a-f2c1-45e1-87a9-b7628b04bb24
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: beyonddsz.cfd
- name: VMESS-cfKUS
  type: vmess
  server: tci3.tiamoci.us.kg
  port: 80
  uuid: 412466bf-7312-45dc-b089-f42d65a4c087
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: tci3.tiamoci.us.kg
- name: VMESS-3oK8w
  type: vmess
  server: e21df9ac-sxfz40-sy3miy-3kis.hkt.east.wctype.com
  port: 460
  uuid: 117fc3d8-fd04-11ed-b345-f23c93136cb3
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: a605477178.m.ctrip.com
- name: VMESS-MaLn9
  type: vmess
  server: 183.236.51.38
  port: 59652
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-CXsGn
  type: vmess
  server: 5tghyu8.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: ''
- name: VMESS-zfjOG
  type: vmess
  server: tk.hzlt.tkddns.xyz
  port: 22643
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-c.tkong.cc
- name: VMESS-1LV3Z
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: Trojan-bYG4Y
  type: trojan
  server: 104.21.16.1
  port: 443
  password: 84831b86-5c76-4173-bdf1-02fa3ed78a32
  params: 'sni: eeERrrR.999815.xYZ, type: ws, path: /eS3prPmcpzbScA5VUAi1psm38Tz,
    host: eeerrrr.999815.xyz'
- name: Trojan-ksvqI
  type: trojan
  server: 172.67.135.37
  port: 443
  password: 44ed7a37-af89-4cd1-8680-83a7207810d9
  params: 'sni: cCtv4.459.pp.uA, type: ws, path: /HpYP4foAlpTKtfYnjLYhU30U, host:
    cctv4.459.pp.ua'
- name: Trojan-G6r21
  type: trojan
  server: 172.67.133.248
  port: 443
  password: f0f6e76e-e5fe-4e2c-9faf-34832e021eae
  params: 'sni: DDd.890604.FIlEGear-sG.Me, type: ws, path: /mZr1mA5hub7QHHkQBzYO,
    host: ddd.890604.filegear-sg.me'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-Yo6dN
  - SSR-CHdRJ
  - VMESS-bqRwZ
  - VMESS-pbqy8
  - VMESS-rAxiE
  - VMESS-0ACRk
  - SS-Cn0XF
  - SS-VzWlt
  - SS-wAPj8
  - VMESS-EROjb
  - VMESS-cfKUS
  - VMESS-3oK8w
  - VMESS-MaLn9
  - VMESS-CXsGn
  - VMESS-zfjOG
  - VMESS-1LV3Z
  - Trojan-bYG4Y
  - Trojan-ksvqI
  - Trojan-G6r21
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-Yo6dN
  - SSR-CHdRJ
  - VMESS-bqRwZ
  - VMESS-pbqy8
  - VMESS-rAxiE
  - VMESS-0ACRk
  - SS-Cn0XF
  - SS-VzWlt
  - SS-wAPj8
  - VMESS-EROjb
  - VMESS-cfKUS
  - VMESS-3oK8w
  - VMESS-MaLn9
  - VMESS-CXsGn
  - VMESS-zfjOG
  - VMESS-1LV3Z
  - Trojan-bYG4Y
  - Trojan-ksvqI
  - Trojan-G6r21
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
