port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-EEsWz
  type: ss
  server: 46.17.45.228
  port: 11111
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-nvzuM
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-IC2AX
  type: vmess
  server: 195.154.40.247
  port: 33639
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-ivd43
  type: vmess
  server: web.51.la
  port: 443
  uuid: e0c6b3b7-9f5b-4bd6-9abf-260663aa4f1b
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-XH36w
  type: vmess
  server: web.51.la
  port: 443
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-SrsJU
  type: vmess
  server: web.51.la
  port: 443
  uuid: c6e84072-2e69-4928-90af-436b3fcd0663
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-FDWbl
  type: vmess
  server: b8605f97-swq1s0-swwcfg-1eijl.hgc1.tcpbbr.net
  port: 8080
  uuid: c2b58ae0-d21c-11ef-b414-f23c91cfbbc9
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-YGfyP
  type: vmess
  server: 183.236.51.38
  port: 41024
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-wxByY
  type: vmess
  server: 7b5d670c-sw1z40-swjbhe-8bem.hgc1.tcpbbr.net
  port: 8080
  uuid: ca506e08-ce3d-5e5a-c128-6358caca15e5
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-3E8JK
  type: vmess
  server: e6eb5fca-swexs0-sycpj3-18jxd.hgc1.tcpbbr.net
  port: 8080
  uuid: fcf7573c-faa4-11ef-8a67-f23c913c8d2b
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-8mBVn
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-p1V0h
  type: vmess
  server: 64f6e0b2-sw1z40-t51bp0-1nyy5.hgc1.tcpbbr.net
  port: 8080
  uuid: 8f7cb770-1305-11ee-b107-f23c91cfbbc9
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-exa7a
  type: vmess
  server: tk.hzlt.tkddns.xyz
  port: 22643
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-c.tkong.cc
- name: VMESS-7c1zv
  type: vmess
  server: 120.198.44.126
  port: 47883
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-MYIiB
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-gifTv
  type: vmess
  server: tls.14.node-for-bigairport.win
  port: 24443
  uuid: 5ac8224f-6126-4ffb-9fad-97e3207f8c33
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: ''
    headers:
      Host: tls.14.node-for-bigairport.win
- name: VMESS-gt327
  type: vmess
  server: 7df05a40-svwf40-sxe8ph-mubp.hgc1.tcpbbr.net
  port: 8080
  uuid: 1bcadc88-4741-11ee-ae2e-f23c91cfbbc9
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-d9yrz
  type: vmess
  server: 120.232.153.40
  port: 31209
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: Trojan-nsxuw
  type: trojan
  server: 172.67.133.248
  port: 443
  password: f0f6e76e-e5fe-4e2c-9faf-34832e021eae
  params: 'sni: DDd.890604.FIlEGear-sG.Me, type: ws, path: /mZr1mA5hub7QHHkQBzYO,
    host: ddd.890604.filegear-sg.me'
- name: Trojan-or1Hc
  type: trojan
  server: 172.67.144.126
  port: 443
  password: 895552fa-6284-4c1d-ba00-3944e0c7c626
  params: 'sni: CFR56ty7890.288288.sHOP, type: ws, path: /By7cEmOrNRS58yeduy9AOG,
    host: cfr56ty7890.288288.shop'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-EEsWz
  - SSR-nvzuM
  - VMESS-IC2AX
  - VMESS-ivd43
  - VMESS-XH36w
  - VMESS-SrsJU
  - VMESS-FDWbl
  - VMESS-YGfyP
  - VMESS-wxByY
  - VMESS-3E8JK
  - VMESS-8mBVn
  - VMESS-p1V0h
  - VMESS-exa7a
  - VMESS-7c1zv
  - VMESS-MYIiB
  - VMESS-gifTv
  - VMESS-gt327
  - VMESS-d9yrz
  - Trojan-nsxuw
  - Trojan-or1Hc
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-EEsWz
  - SSR-nvzuM
  - VMESS-IC2AX
  - VMESS-ivd43
  - VMESS-XH36w
  - VMESS-SrsJU
  - VMESS-FDWbl
  - VMESS-YGfyP
  - VMESS-wxByY
  - VMESS-3E8JK
  - VMESS-8mBVn
  - VMESS-p1V0h
  - VMESS-exa7a
  - VMESS-7c1zv
  - VMESS-MYIiB
  - VMESS-gifTv
  - VMESS-gt327
  - VMESS-d9yrz
  - Trojan-nsxuw
  - Trojan-or1Hc
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
