port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-iUdVx
  type: ss
  server: 46.17.45.228
  port: 11111
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-3xY6s
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-mZFS5
  type: vmess
  server: 195.154.40.247
  port: 33639
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-3ZMql
  type: vmess
  server: web.51.la
  port: 443
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-ceO4T
  type: vmess
  server: web.51.la
  port: 443
  uuid: c6e84072-2e69-4928-90af-436b3fcd0663
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-IOn9d
  type: vmess
  server: web.51.la
  port: 443
  uuid: e0c6b3b7-9f5b-4bd6-9abf-260663aa4f1b
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: SS-SCUKJ
  type: ss
  server: 193.243.147.128
  port: 40368
  cipher: aes-256-gcm
  password: 7BcLdsO1WweoGD0X
- name: VMESS-dKNWq
  type: vmess
  server: us01.sh-cloudflare.sbs
  port: 8443
  uuid: 2703867d-dd8f-4f7f-93f4-ac6e4f56c7e8
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-QOPB6
  type: vmess
  server: 104.17.147.22
  port: 80
  uuid: 3f638f34-8dba-4186-bc43-2716a7ddd4be
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /az05.beyondy.cfd:443/link
    headers:
      Host: telegram----cassiusvpn----3.kale-e08.workers.dev
- name: VMESS-BFPkz
  type: vmess
  server: xcdvfrr54.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: ''
- name: VMESS-OEFwY
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 2ff97c6d-8557-42a4-b43f-19c77c5959ea
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: irsoft.sytes.net
- name: VMESS-19wzR
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-Nl7cq
  type: vmess
  server: 183.236.51.38
  port: 49191
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: Trojan-GlkX2
  type: trojan
  server: 104.21.35.247
  port: 443
  password: c8eac4b7-95ba-4ce0-920d-c3279eb3b391
  params: 'sni: ff.HuangSHANg2030.DPDnS.oRg, type: ws, path: /ptGwaGzcA4KNAXX, host:
    ff.huangshang2030.dpdns.org'
- name: Trojan-HXjEw
  type: trojan
  server: 172.67.133.248
  port: 443
  password: f0f6e76e-e5fe-4e2c-9faf-34832e021eae
  params: 'sni: DDd.890604.FIlEGear-sG.Me, type: ws, path: /mZr1mA5hub7QHHkQBzYO,
    host: ddd.890604.filegear-sg.me'
- name: Trojan-WWvi6
  type: trojan
  server: 3050cfd7-sx6ps0-sydxa9-fa3p.cm5.cnkuaishou.com
  port: 27231
  password: 905fcd78-866c-81e1-3cb8-1beb59d661ab
  params: 'allowInsecure: 0, sni: 3050cfd7-sx6ps0-sydxa9-fa3p.cm5.cnkuaishou.com'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-iUdVx
  - SSR-3xY6s
  - VMESS-mZFS5
  - VMESS-3ZMql
  - VMESS-ceO4T
  - VMESS-IOn9d
  - SS-SCUKJ
  - VMESS-dKNWq
  - VMESS-QOPB6
  - VMESS-BFPkz
  - VMESS-OEFwY
  - VMESS-19wzR
  - VMESS-Nl7cq
  - Trojan-GlkX2
  - Trojan-HXjEw
  - Trojan-WWvi6
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-iUdVx
  - SSR-3xY6s
  - VMESS-mZFS5
  - VMESS-3ZMql
  - VMESS-ceO4T
  - VMESS-IOn9d
  - SS-SCUKJ
  - VMESS-dKNWq
  - VMESS-QOPB6
  - VMESS-BFPkz
  - VMESS-OEFwY
  - VMESS-19wzR
  - VMESS-Nl7cq
  - Trojan-GlkX2
  - Trojan-HXjEw
  - Trojan-WWvi6
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
