port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - +.srv.nintendo.net
  - +.stun.playstation.net
  - xbox.*.microsoft.com
  - +.xboxlive.com
  - '*.msftncsi.com'
  - '*.msftconnecttest.com'
  - lens.l.google.com
  - +.qq.com
  - +.music.163.com
  - localhost
  - +.local
  - +.internal
  - '*.aliyuncs.com'
  - stun.*.*
  - stun.*.*.*
  - +.cdn.jsdelivr.net
  nameservers:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - tls://dns.rubyfish.cn:853
  - 223.5.5.5
  - 119.29.29.29
  fallback:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  - 1.1.1.1
  - 8.8.8.8
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 224.0.0.0/4
    - 240.0.0.0/4
proxies:
- name: SS-iLC8B
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-h8REG
  type: ss
  server: 102.37.156.224
  port: 443
  cipher: chacha20-ietf-poly1305
  password: aduB9HGxQHjA2SBMRjkHX6
- name: SS-8Hy9D
  type: ss
  server: auto.poland.ray-vpn.ru
  port: 4495
  cipher: chacha20-ietf-poly1305
  password: 2Z9ba3GwDL-rn6DSQ0N-awHNhcuxaHP3
- name: SS-5oBea
  type: ss
  server: 77.73.68.155
  port: 54106
  cipher: chacha20-ietf-poly1305
  password: 9CmcQ6dF8LEyZU0YsMjgu8
- name: SS-y3P52
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-RjSa8
  type: ss
  server: 158.173.20.171
  port: 443
  cipher: aes-128-gcm
  password: shadowsocks
- name: SS-E6MVJ
  type: ss
  server: 144.31.234.82
  port: 45356
  cipher: chacha20-ietf-poly1305
  password: EDTfh0zLmD5dfg03sQYFcp
- name: SS-v74bK
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
- name: SS-LUdlf
  type: ss
  server: 193.135.174.135
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
- name: SS-tzIK0
  type: ss
  server: 144.126.145.77
  port: 443
  cipher: aes-256-gcm
  password: QzM0NfuMNngbVnZK
- name: SS-4YJKT
  type: ss
  server: 57.128.214.100
  port: 12000
  cipher: aes-256-gcm
  password: 8JCsPssfgS8tiRwiMlhARg==
- name: SS-cUxtz
  type: ss
  server: 106.75.162.7
  port: 50000
  cipher: aes-128-gcm
  password: d72781da-3ea8-4d7f-9bca-c04ed410443b
- name: SS-hc0aa
  type: ss
  server: 149.104.71.134
  port: 11201
  cipher: chacha20-ietf-poly1305
  password: 1e68d4bd002437ab
- name: SS-Lsva0
  type: ss
  server: 192.124.176.95
  port: 8388
  cipher: aes-256-gcm
  password: UcbtKq1aPi88
- name: SS-1ThKV
  type: ss
  server: 102.133.165.160
  port: 16233
  cipher: chacha20-ietf-poly1305
  password: Xsy8Ox4yOV3xLlpxtjzs3X
- name: SS-WU01d
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-4qsdS
  type: ss
  server: 185.111.156.33
  port: 80
  cipher: aes-256-gcm
  password: 5mCH4624QflO1cFR
- name: SS-80iD2
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-LGRgd
  type: ss
  server: 195.66.25.220
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: yhrHMDgZ2egKftvrecvkpUPqpUTyac7q
- name: SS-u3mUy
  type: ss
  server: 193.47.60.186
  port: 28687
  cipher: chacha20-ietf-poly1305
  password: yKVMoB3AwiTEznpnoq2FYR
- name: SS-SRmFO
  type: ss
  server: 185.176.221.72
  port: 24637
  cipher: chacha20-ietf-poly1305
  password: MholStyHL7DhrewKbpQa20
- name: SS-wzSiY
  type: ss
  server: 144.217.164.29
  port: 12000
  cipher: aes-256-gcm
  password: 8JCsPssfgS8tiRwiMlhARg==
- name: SS-Pkd9F
  type: ss
  server: chengbai02.ascwt179.com
  port: 13223
  cipher: aes-128-gcm
  password: JVrsLLN1tkN8oXZO
- name: SS-gUW87
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-C96pv
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: VMESS-elNeH
  type: vmess
  server: zdqbk.cmvvb.online
  port: 8443
  uuid: a2852e93-7255-4aae-9412-38273fdacd31
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zdqbk.cmvvb.online
- name: VMESS-H3dR2
  type: vmess
  server: 2a14:7584:d0a2::a
  port: 23456
  uuid: bd48e0ac-e90e-4451-a4f2-abf061cfb890
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /alvin9999.com
    headers:
      Host: www.bing.com
- name: VMESS-PVsXK
  type: vmess
  server: 103.181.164.145
  port: 54022
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: ''
    headers:
      Host: ''
- name: VMESS-lWAdQ
  type: vmess
  server: 82.198.246.97
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: Trojan-lE90r
  type: trojan
  server: 58.152.25.253
  port: 443
  password: BxceQaOe
  params: 'allowInsecure: 1, sni: t.me/ripaojiedian'
- name: Trojan-ZxPEJ
  type: trojan
  server: engaged-ram.rooster465.autos
  port: 443
  password: IL37892054
  params: 'allowInsecure: 0'
- name: Trojan-vsPXL
  type: trojan
  server: free-duckling.rooster465.autos
  port: 443
  password: ZY07256934
  params: 'security: tls'
- name: Trojan-s1tXe
  type: trojan
  server: glowing-deer.rooster465.autos
  port: 443
  password: ZY07256934
  params: 'security: tls, sni: glowing-deer.rooster465.autos'
- name: Trojan-Ty9uv
  type: trojan
  server: delicate-buck.rooster465.autos
  port: 443
  password: ZY07256934
  params: 'security: tls'
- name: Trojan-CZWYI
  type: trojan
  server: select-marmoset.rooster465.autos
  port: 443
  password: IL37892054
  params: 'security: tls, sni: select-marmoset.rooster465.autos'
- name: Trojan-aTEYB
  type: trojan
  server: 212.193.18.144
  port: 36158
  password: ZblhWr0mqMakCPg.N
  params: 'allowInsecure: 0, sni: ya.ru'
- name: Trojan-bvd3A
  type: trojan
  server: 160.16.70.180
  port: 4937
  password: 86e150eb21c6faee48e81d496d7f61c2
  params: 'security: tls, sni: www.nintendogames.net'
- name: Trojan-g19cA
  type: trojan
  server: 8443.golden-cards.me
  port: 443
  password: q2GRUM1-odJBWq_KV6xv2fuNvu8ed-
  params: 'security: tls, insecure: 1, headerType: none, type: tcp, allowInsecure:
    1'
- name: Trojan-A9pS9
  type: trojan
  server: upright-rhino.rooster465.autos
  port: 443
  password: IL37892054
  params: 'security: tls, sni: upright-rhino.rooster465.autos'
- name: Trojan-XA6rv
  type: trojan
  server: 160.16.106.99
  port: 3057
  password: 86e150eb21c6faee48e81d496d7f61c2
  params: 'security: tls, sni: www.nintendogames.net'
- name: Trojan-GzL3W
  type: trojan
  server: 153.121.65.107
  port: 4019
  password: f389ed926e512e15f382dc3804029474
  params: 'security: tls, sni: www.nintendogames.net'
- name: Trojan-1sa6Y
  type: trojan
  server: outgoing-ladybird.rooster465.autos
  port: 443
  password: IL37892054
  params: 'allowInsecure: 0, sni: outgoing-ladybird.rooster465.autos'
- name: Trojan-vgxX6
  type: trojan
  server: engaging-toucan.rooster465.autos
  port: 443
  password: IL37892054
  params: 'security: tls, sni: engaging-toucan.rooster465.autos'
- name: Trojan-Np2Rc
  type: trojan
  server: nl-4.tr202512.com
  port: 443
  password: M08tvzYWtUEJNtbpHp
  params: 'security: tls, sni: nl-4.tr202512.com'
proxy-groups:
- name: ♻️ 自动选择
  type: url-test
  proxies:
  - SS-iLC8B
  - SS-h8REG
  - SS-8Hy9D
  - SS-5oBea
  - SS-y3P52
  - SS-RjSa8
  - SS-E6MVJ
  - SS-v74bK
  - SS-LUdlf
  - SS-tzIK0
  - SS-4YJKT
  - SS-cUxtz
  - SS-hc0aa
  - SS-Lsva0
  - SS-1ThKV
  - SS-WU01d
  - SS-4qsdS
  - SS-80iD2
  - SS-LGRgd
  - SS-u3mUy
  - SS-SRmFO
  - SS-wzSiY
  - SS-Pkd9F
  - SS-gUW87
  - SS-C96pv
  - VMESS-elNeH
  - VMESS-H3dR2
  - VMESS-PVsXK
  - VMESS-lWAdQ
  - Trojan-lE90r
  - Trojan-ZxPEJ
  - Trojan-vsPXL
  - Trojan-s1tXe
  - Trojan-Ty9uv
  - Trojan-CZWYI
  - Trojan-aTEYB
  - Trojan-bvd3A
  - Trojan-g19cA
  - Trojan-A9pS9
  - Trojan-XA6rv
  - Trojan-GzL3W
  - Trojan-1sa6Y
  - Trojan-vgxX6
  - Trojan-Np2Rc
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 国外媒体
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: Ⓜ️ 微软服务
  type: select
  proxies:
  - DIRECT
  - ♻️ 自动选择
- name: 🍎 苹果服务
  type: select
  proxies:
  - DIRECT
  - ♻️ 自动选择
- name: 📲 电报信息
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎮 游戏平台
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎬 YouTube
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎥 Netflix
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🔍 学术搜索
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🛑 全球拦截
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: 🐟 漏网之鱼
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,ip6-localhost,DIRECT
- DOMAIN-SUFFIX,ip6-loopback,DIRECT
- DOMAIN-SUFFIX,lan,DIRECT
- DOMAIN-SUFFIX,localhost,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN,yacd.metacubex.one,DIRECT
- DOMAIN,clash.metacubex.one,DIRECT
- DOMAIN-KEYWORD,apple,🍎 苹果服务
- DOMAIN-KEYWORD,icloud,🍎 苹果服务
- DOMAIN-SUFFIX,aaplimg.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple.co,🍎 苹果服务
- DOMAIN-SUFFIX,apple.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple-cloudkit.com,🍎 苹果服务
- DOMAIN-SUFFIX,appstore.com,🍎 苹果服务
- DOMAIN-SUFFIX,cdn-apple.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud-content.com,🍎 苹果服务
- DOMAIN-SUFFIX,me.com,🍎 苹果服务
- DOMAIN-SUFFIX,mzstatic.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple.news,🍎 苹果服务
- DOMAIN-SUFFIX,apple.com.cn,🍎 苹果服务
- DOMAIN-SUFFIX,appstore.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud.com.cn,🍎 苹果服务
- DOMAIN-KEYWORD,microsoft,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoft.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msecnd.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msedge.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,office.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,office.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,outlook.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,visualstudio.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windows.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windows.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windowsupdate.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,xbox.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,xboxlive.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msn.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoftonline.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoft365.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,skype.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,live.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,bing.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,hotmail.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,azureedge.net,Ⓜ️ 微软服务
- DOMAIN-KEYWORD,admarvel,🛑 全球拦截
- DOMAIN-KEYWORD,admaster,🛑 全球拦截
- DOMAIN-KEYWORD,adsage,🛑 全球拦截
- DOMAIN-KEYWORD,adsmogo,🛑 全球拦截
- DOMAIN-KEYWORD,adsrvmedia,🛑 全球拦截
- DOMAIN-KEYWORD,adwords,🛑 全球拦截
- DOMAIN-KEYWORD,analytics,🛑 全球拦截
- DOMAIN-KEYWORD,duomeng,🛑 全球拦截
- DOMAIN-KEYWORD,dwtrack,🛑 全球拦截
- DOMAIN-KEYWORD,guanggao,🛑 全球拦截
- DOMAIN-KEYWORD,lianmeng,🛑 全球拦截
- DOMAIN-KEYWORD,mopub,🛑 全球拦截
- DOMAIN-KEYWORD,omgmta,🛑 全球拦截
- DOMAIN-KEYWORD,openx,🛑 全球拦截
- DOMAIN-KEYWORD,partnerad,🛑 全球拦截
- DOMAIN-KEYWORD,pingfore,🛑 全球拦截
- DOMAIN-KEYWORD,supersonicads,🛑 全球拦截
- DOMAIN-KEYWORD,tracking,🛑 全球拦截
- DOMAIN-KEYWORD,uedas,🛑 全球拦截
- DOMAIN-KEYWORD,umeng,🛑 全球拦截
- DOMAIN-KEYWORD,usage,🛑 全球拦截
- DOMAIN-KEYWORD,wlmonitor,🛑 全球拦截
- DOMAIN-KEYWORD,zjtoolbar,🛑 全球拦截
- DOMAIN-SUFFIX,adjust.com,🛑 全球拦截
- DOMAIN-SUFFIX,ad.gt,🛑 全球拦截
- DOMAIN-SUFFIX,adcolony.com,🛑 全球拦截
- DOMAIN-SUFFIX,adform.net,🛑 全球拦截
- DOMAIN-SUFFIX,admob.com,🛑 全球拦截
- DOMAIN-SUFFIX,adnxs.com,🛑 全球拦截
- DOMAIN-SUFFIX,ads-twitter.com,🛑 全球拦截
- DOMAIN-SUFFIX,adsafeprotected.com,🛑 全球拦截
- DOMAIN-SUFFIX,adsrvr.org,🛑 全球拦截
- DOMAIN-SUFFIX,appsflyer.com,🛑 全球拦截
- DOMAIN-SUFFIX,doubleclick.net,🛑 全球拦截
- DOMAIN-SUFFIX,googleadservices.com,🛑 全球拦截
- DOMAIN-SUFFIX,googleadsserving.cn,🛑 全球拦截
- DOMAIN-SUFFIX,googlesyndication.com,🛑 全球拦截
- DOMAIN-SUFFIX,googletagmanager.com,🛑 全球拦截
- DOMAIN-SUFFIX,googletagservices.com,🛑 全球拦截
- DOMAIN-SUFFIX,mopub.com,🛑 全球拦截
- DOMAIN-SUFFIX,telegra.ph,📲 电报信息
- DOMAIN-SUFFIX,telegram.org,📲 电报信息
- DOMAIN-SUFFIX,telegram.me,📲 电报信息
- DOMAIN-SUFFIX,telesco.pe,📲 电报信息
- DOMAIN-SUFFIX,t.me,📲 电报信息
- DOMAIN-SUFFIX,tdesktop.com,📲 电报信息
- DOMAIN-SUFFIX,telegramdownload.com,📲 电报信息
- IP-CIDR,91.108.4.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.8.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.12.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.16.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.56.0/22,📲 电报信息,no-resolve
- IP-CIDR,149.154.160.0/20,📲 电报信息,no-resolve
- IP-CIDR,2001:b28:f23d::/48,📲 电报信息,no-resolve
- IP-CIDR,2001:b28:f23f::/48,📲 电报信息,no-resolve
- IP-CIDR,2001:67c:4e8::/48,📲 电报信息,no-resolve
- DOMAIN-SUFFIX,steamcontent.com,🎮 游戏平台
- DOMAIN-SUFFIX,steampowered.com,🎮 游戏平台
- DOMAIN-SUFFIX,steamstatic.com,🎮 游戏平台
- DOMAIN-SUFFIX,steamcommunity.com,🎮 游戏平台
- DOMAIN-SUFFIX,valvesoftware.com,🎮 游戏平台
- DOMAIN-SUFFIX,steam-chat.com,🎮 游戏平台
- DOMAIN-SUFFIX,epicgames.com,🎮 游戏平台
- DOMAIN-SUFFIX,epicgames.dev,🎮 游戏平台
- DOMAIN-SUFFIX,unrealengine.com,🎮 游戏平台
- DOMAIN-SUFFIX,playstation.com,🎮 游戏平台
- DOMAIN-SUFFIX,playstation.net,🎮 游戏平台
- DOMAIN-SUFFIX,playstationnetwork.com,🎮 游戏平台
- DOMAIN-SUFFIX,sony.com,🎮 游戏平台
- DOMAIN-SUFFIX,xbox.com,🎮 游戏平台
- DOMAIN-SUFFIX,xboxlive.com,🎮 游戏平台
- DOMAIN-SUFFIX,nintendo.com,🎮 游戏平台
- DOMAIN-SUFFIX,nintendo.net,🎮 游戏平台
- DOMAIN-SUFFIX,ea.com,🎮 游戏平台
- DOMAIN-SUFFIX,origin.com,🎮 游戏平台
- DOMAIN-SUFFIX,ubisoft.com,🎮 游戏平台
- DOMAIN-SUFFIX,ubi.com,🎮 游戏平台
- DOMAIN-SUFFIX,battle.net,🎮 游戏平台
- DOMAIN-SUFFIX,blizzard.com,🎮 游戏平台
- DOMAIN-SUFFIX,youtube.com,🎬 YouTube
- DOMAIN-SUFFIX,ytimg.com,🎬 YouTube
- DOMAIN-SUFFIX,googlevideo.com,🎬 YouTube
- DOMAIN-SUFFIX,youtu.be,🎬 YouTube
- DOMAIN-SUFFIX,yt.be,🎬 YouTube
- DOMAIN-SUFFIX,youtube-nocookie.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubeeducation.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubegaming.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubekids.com,🎬 YouTube
- DOMAIN-SUFFIX,netflix.com,🎥 Netflix
- DOMAIN-SUFFIX,netflix.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxext.com,🎥 Netflix
- DOMAIN-SUFFIX,nflximg.com,🎥 Netflix
- DOMAIN-SUFFIX,nflximg.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxso.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxvideo.net,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest0.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest1.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest2.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest3.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest4.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest5.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest6.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest7.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest8.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest9.com,🎥 Netflix
- DOMAIN-SUFFIX,scholar.google.com,🔍 学术搜索
- DOMAIN-SUFFIX,scholar.googleusercontent.com,🔍 学术搜索
- DOMAIN-SUFFIX,scholarcdn.net,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.tw,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.st,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.se,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.ren,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.ru,🔍 学术搜索
- DOMAIN-SUFFIX,researchgate.net,🔍 学术搜索
- DOMAIN-SUFFIX,springer.com,🔍 学术搜索
- DOMAIN-SUFFIX,sciencedirect.com,🔍 学术搜索
- DOMAIN-SUFFIX,acm.org,🔍 学术搜索
- DOMAIN-SUFFIX,ieee.org,🔍 学术搜索
- DOMAIN-SUFFIX,nature.com,🔍 学术搜索
- DOMAIN-SUFFIX,jstor.org,🔍 学术搜索
- DOMAIN-SUFFIX,9cache.com,🌍 国外媒体
- DOMAIN-SUFFIX,9gag.com,🌍 国外媒体
- DOMAIN-SUFFIX,abc.com,🌍 国外媒体
- DOMAIN-SUFFIX,bbc.co.uk,🌍 国外媒体
- DOMAIN-SUFFIX,bbc.com,🌍 国外媒体
- DOMAIN-SUFFIX,cnn.com,🌍 国外媒体
- DOMAIN-SUFFIX,deezer.com,🌍 国外媒体
- DOMAIN-SUFFIX,discord.com,🌍 国外媒体
- DOMAIN-SUFFIX,dropbox.com,🌍 国外媒体
- DOMAIN-SUFFIX,facebook.com,🌍 国外媒体
- DOMAIN-SUFFIX,fb.com,🌍 国外媒体
- DOMAIN-SUFFIX,fbcdn.net,🌍 国外媒体
- DOMAIN-SUFFIX,github.com,🌍 国外媒体
- DOMAIN-SUFFIX,github.io,🌍 国外媒体
- DOMAIN-SUFFIX,githubusercontent.com,🌍 国外媒体
- DOMAIN-SUFFIX,instagram.com,🌍 国外媒体
- DOMAIN-SUFFIX,pinterest.com,🌍 国外媒体
- DOMAIN-SUFFIX,reddit.com,🌍 国外媒体
- DOMAIN-SUFFIX,redditmedia.com,🌍 国外媒体
- DOMAIN-SUFFIX,redditstatic.com,🌍 国外媒体
- DOMAIN-SUFFIX,spotify.com,🌍 国外媒体
- DOMAIN-SUFFIX,tiktok.com,🌍 国外媒体
- DOMAIN-SUFFIX,ttvnw.net,🌍 国外媒体
- DOMAIN-SUFFIX,twitch.tv,🌍 国外媒体
- DOMAIN-SUFFIX,twitter.com,🌍 国外媒体
- DOMAIN-SUFFIX,x.com,🌍 国外媒体
- DOMAIN-SUFFIX,t.co,🌍 国外媒体
- DOMAIN-SUFFIX,medium.com,🌍 国外媒体
- DOMAIN-SUFFIX,flickr.com,🌍 国外媒体
- DOMAIN-SUFFIX,imgur.com,🌍 国外媒体
- DOMAIN-SUFFIX,soundcloud.com,🌍 国外媒体
- DOMAIN-SUFFIX,vimeo.com,🌍 国外媒体
- DOMAIN-SUFFIX,tumblr.com,🌍 国外媒体
- DOMAIN-SUFFIX,quora.com,🌍 国外媒体
- DOMAIN-SUFFIX,reuters.com,🌍 国外媒体
- DOMAIN-SUFFIX,nytimes.com,🌍 国外媒体
- DOMAIN-SUFFIX,wsj.com,🌍 国外媒体
- DOMAIN-SUFFIX,ft.com,🌍 国外媒体
- DOMAIN-SUFFIX,theguardian.com,🌍 国外媒体
- DOMAIN-SUFFIX,apnews.com,🌍 国外媒体
- DOMAIN-SUFFIX,bloomberg.com,🌍 国外媒体
- DOMAIN-SUFFIX,googlevideo.com,🌍 国外媒体
- DOMAIN-SUFFIX,googleapis.com,🌍 国外媒体
- DOMAIN-SUFFIX,gstatic.com,🌍 国外媒体
- DOMAIN-SUFFIX,google.com,🌍 国外媒体
- DOMAIN-SUFFIX,cn,DIRECT
- DOMAIN-SUFFIX,126.com,DIRECT
- DOMAIN-SUFFIX,126.net,DIRECT
- DOMAIN-SUFFIX,127.net,DIRECT
- DOMAIN-SUFFIX,163.com,DIRECT
- DOMAIN-SUFFIX,360buyimg.com,DIRECT
- DOMAIN-SUFFIX,36kr.com,DIRECT
- DOMAIN-SUFFIX,alipay.com,DIRECT
- DOMAIN-SUFFIX,aliyun.com,DIRECT
- DOMAIN-SUFFIX,alicdn.com,DIRECT
- DOMAIN-SUFFIX,amap.com,DIRECT
- DOMAIN-SUFFIX,baidu.com,DIRECT
- DOMAIN-SUFFIX,bdimg.com,DIRECT
- DOMAIN-SUFFIX,bdstatic.com,DIRECT
- DOMAIN-SUFFIX,bilibili.com,DIRECT
- DOMAIN-SUFFIX,bilivideo.com,DIRECT
- DOMAIN-SUFFIX,caiyunapp.com,DIRECT
- DOMAIN-SUFFIX,csdn.net,DIRECT
- DOMAIN-SUFFIX,ctrip.com,DIRECT
- DOMAIN-SUFFIX,didi.com,DIRECT
- DOMAIN-SUFFIX,douban.com,DIRECT
- DOMAIN-SUFFIX,doubanio.com,DIRECT
- DOMAIN-SUFFIX,douyin.com,DIRECT
- DOMAIN-SUFFIX,jd.com,DIRECT
- DOMAIN-SUFFIX,mi.com,DIRECT
- DOMAIN-SUFFIX,meituan.com,DIRECT
- DOMAIN-SUFFIX,meituan.net,DIRECT
- DOMAIN-SUFFIX,netease.com,DIRECT
- DOMAIN-SUFFIX,oschina.net,DIRECT
- DOMAIN-SUFFIX,qq.com,DIRECT
- DOMAIN-SUFFIX,qqmail.com,DIRECT
- DOMAIN-SUFFIX,sina.com,DIRECT
- DOMAIN-SUFFIX,sinaimg.com,DIRECT
- DOMAIN-SUFFIX,taobao.com,DIRECT
- DOMAIN-SUFFIX,tencent.com,DIRECT
- DOMAIN-SUFFIX,tmall.com,DIRECT
- DOMAIN-SUFFIX,weibo.com,DIRECT
- DOMAIN-SUFFIX,wechat.com,DIRECT
- DOMAIN-SUFFIX,weixin.com,DIRECT
- DOMAIN-SUFFIX,zhihu.com,DIRECT
- DOMAIN-SUFFIX,zhimg.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.net,DIRECT
- DOMAIN-SUFFIX,iqiyi.com,DIRECT
- DOMAIN-SUFFIX,iqiyipic.com,DIRECT
- DOMAIN-SUFFIX,acfun.cn,DIRECT
- DOMAIN-SUFFIX,aixifan.com,DIRECT
- DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
- DOMAIN-SUFFIX,xhscdn.com,DIRECT
- DOMAIN-SUFFIX,xiaomi.com,DIRECT
- DOMAIN-SUFFIX,xiaomiyoupin.com,DIRECT
- DOMAIN-SUFFIX,huawei.com,DIRECT
- DOMAIN-SUFFIX,hicloud.com,DIRECT
- DOMAIN-SUFFIX,vmall.com,DIRECT
- DOMAIN-SUFFIX,vivo.com,DIRECT
- DOMAIN-SUFFIX,oppo.com,DIRECT
- DOMAIN-SUFFIX,heytap.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,🐟 漏网之鱼
