port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-gZGxd
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-06NCj
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-b9U5P
  type: vmess
  server: 195.154.40.247
  port: 38952
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-OFJgz
  type: vmess
  server: 120.198.71.216
  port: 46759
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-Fe4IV
  type: vmess
  server: www.xinjuc.com
  port: 80
  uuid: 2f38f848-a899-4c87-9807-207a41615e3c
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /rongseven?ed=2048
    headers:
      Host: hk.freeyyds.dpdns.org
- name: VMESS-LbcFL
  type: vmess
  server: cloudgetservice.mcloudservice.site
  port: 443
  uuid: 5428dcc2-9950-4404-b8a5-9dac82acb210
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: maXNEtVIP-usA-VP3.nETKH3.SiTE
- name: VMESS-1Zp9b
  type: vmess
  server: 104.21.112.1
  port: 2087
  uuid: 1c36906e-1a21-4330-b04f-85baf1a6ff26
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: rak1d3.777269.xyz
- name: VMESS-53CwT
  type: vmess
  server: ysl.fxlcn.com
  port: 45419
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-mnhfD
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-AneG8
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-yv0Yd
  type: vmess
  server: 120.232.153.40
  port: 31609
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-s5hB8
  type: vmess
  server: 183.236.51.38
  port: 41024
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-gR3n5
  type: vmess
  server: 120.198.71.214
  port: 32980
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-shi5Y
  type: vmess
  server: 120.232.153.123
  port: 40392
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-oAFHX
  type: vmess
  server: tk.hzlt.tkddns.xyz
  port: 22642
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-b.tkong.cc
- name: VMESS-j2bBm
  type: vmess
  server: v5.heduian.link
  port: 30805
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-2ITkC
  type: vmess
  server: 58.246.138.244
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: Trojan-7cf00
  type: trojan
  server: 172.67.135.37
  port: 443
  password: 44ed7a37-af89-4cd1-8680-83a7207810d9
  params: 'security: tls, sni: cCtv4.459.pp.uA, type: ws, host: cctv4.459.pp.ua, path:
    /HpYP4foAlpTKtfYnjLYhU30U, fp: chrome, alpn: http/1.1'
- name: Trojan-F3iLo
  type: trojan
  server: 212.183.88.58
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz, allowInsecure:
    1'
- name: Trojan-1j4hy
  type: trojan
  server: 104.26.13.31
  port: 8443
  password: trojan
  params: 'security: tls, sni: qianlang.pages.dev, type: ws, host: qianlang.pages.dev,
    path: /?ed=2560, fp: random'
- name: Trojan-pEsja
  type: trojan
  server: 172.67.205.22
  port: 443
  password: 5453ae26-250d-4e79-b4ec-016baf806865
  params: 'sni: 1SSdDdFfffHhHJJJJ.20220420.Pp.uA, allowInsecure: 1, type: ws, path:
    /OYzPAeaZdXUq2d6J3gc4aj, host: 1ssdddffffhhhjjjj.20220420.pp.ua, fp: chrome'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-gZGxd
  - SSR-06NCj
  - VMESS-b9U5P
  - VMESS-OFJgz
  - VMESS-Fe4IV
  - VMESS-LbcFL
  - VMESS-1Zp9b
  - VMESS-53CwT
  - VMESS-mnhfD
  - VMESS-AneG8
  - VMESS-yv0Yd
  - VMESS-s5hB8
  - VMESS-gR3n5
  - VMESS-shi5Y
  - VMESS-oAFHX
  - VMESS-j2bBm
  - VMESS-2ITkC
  - Trojan-7cf00
  - Trojan-F3iLo
  - Trojan-1j4hy
  - Trojan-pEsja
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-gZGxd
  - SSR-06NCj
  - VMESS-b9U5P
  - VMESS-OFJgz
  - VMESS-Fe4IV
  - VMESS-LbcFL
  - VMESS-1Zp9b
  - VMESS-53CwT
  - VMESS-mnhfD
  - VMESS-AneG8
  - VMESS-yv0Yd
  - VMESS-s5hB8
  - VMESS-gR3n5
  - VMESS-shi5Y
  - VMESS-oAFHX
  - VMESS-j2bBm
  - VMESS-2ITkC
  - Trojan-7cf00
  - Trojan-F3iLo
  - Trojan-1j4hy
  - Trojan-pEsja
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
