port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-EGazw
  type: ss
  server: 195.154.32.37
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-yR4PU
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-DiGj6
  type: vmess
  server: 195.154.40.247
  port: 31549
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-1tu4y
  type: ss
  server: 43.226.17.17
  port: 14312
  cipher: chacha20-ietf-poly1305
  password: 2e96aa2f3054
- name: SS-KdXEu
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-MAUG7
  type: ss
  server: 34.212.26.32
  port: 443
  cipher: aes-256-cfb
  password: awsps0501
- name: SS-J3ocw
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-6eze2
  type: ss
  server: hkkh11v1.xpmc.cc
  port: 20273
  cipher: chacha20-ietf-poly1305
  password: 91a41f4e02dc
- name: SS-dNsTu
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: SS-A4BCa
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-ARbad
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 15007
  cipher: aes-256-gcm
  password: Q5XH89ZLTSGOQASZ
- name: SS-7UibA
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18010
  cipher: aes-256-gcm
  password: TF63RS7M0DB9OJ3B
- name: SS-FrQiC
  type: ss
  server: 3.38.139.172
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-fQgMX
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-hz4Zk
  type: ss
  server: 125.141.26.12
  port: 4857
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-Luymu
  type: ss
  server: 52.195.15.105
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-1mTjZ
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: VMESS-zWy0h
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-PqyIu
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-PHol5
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-Xrl7E
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-9EYOT
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-mnG3a
  type: vmess
  server: 8.211.154.107
  port: 50951
  uuid: a3d04548-625c-4658-9ff0-f9a7835d1f6d
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-CiAYR
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-7K6Tt
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-pJHmN
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-WoXKW
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-jLsOJ
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-sVDAC
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-iWQxT
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-KwyLB
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-LKuYv
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: Trojan-30h4n
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 1, sni: 120.233.44.201'
- name: Trojan-4GjhN
  type: trojan
  server: 5f9d335d-swexs0-t5juhn-4tue.cu.plebai.net
  port: 15229
  password: fe506496-24eb-11ef-abd3-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 5f9d335d-swexs0-t5juhn-4tue.cu.plebai.net'
- name: Trojan-zYIbP
  type: trojan
  server: diagram.protocolbuffer.com
  port: 18334
  password: YaN8FFNe58nga3xAu3yTx0CSllcSeOnDZOj3SXROCz3S34B9D3F7Ka0aYa8yaxpXCDRKZ
  params: 'allowInsecure: 0'
- name: Trojan-Fb2Lj
  type: trojan
  server: bd8e9b7d-swzb40-t5vrf3-716s.cu.plebai.net
  port: 15229
  password: 088a0bbe-4f9f-11ea-a15d-f23c913c8d2b
  params: 'allowInsecure: 1, sni: bd8e9b7d-swzb40-t5vrf3-716s.cu.plebai.net'
- name: Trojan-sqbfq
  type: trojan
  server: 36.151.251.62
  port: 3330
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-Q075r
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: Trojan-AcVR3
  type: trojan
  server: 36.151.251.62
  port: 13542
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-QM5SA
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-d6bv3
  type: trojan
  server: 36.156.102.123
  port: 50723
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: 36.156.102.123'
- name: Trojan-bAQG6
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: Trojan-0B882
  type: trojan
  server: usla.mjt000.com
  port: 443
  password: e4af2638-bb12-4e4a-84f1-a032e23ca63f
  params: 'allowInsecure: 0, sni: usla.mjt000.com'
- name: Trojan-qWaC1
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 1'
- name: Trojan-5m3Ea
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: 36.151.251.61'
- name: Trojan-1Mt3C
  type: trojan
  server: f5ada702-swb8g0-t5fh9u-1uni.cu.plebai.net
  port: 15229
  password: adbd0a82-3336-11ed-bd7c-f23c913c8d2b
  params: 'allowInsecure: 1'
- name: Trojan-ml68p
  type: trojan
  server: bapus.koreanbbq.link
  port: 443
  password: 94Xn93e3F2uOxCE8De8upAAwnlI8ySRRj70Ol6zgYNBjZFCDK5Yaca3D8aT2qaxyEc0DK
  params: 'allowInsecure: 0'
- name: Trojan-ghLRG
  type: trojan
  server: 7d09e919-swq1s0-tcvn0z-1tlyg.cu.plebai.net
  port: 15229
  password: be8ba532-0dcf-11f0-9a65-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 7d09e919-swq1s0-tcvn0z-1tlyg.cu.plebai.net'
- name: SS-aEluL
  type: ss
  server: 193.243.147.128
  port: 40368
  cipher: aes-256-gcm
  password: 7BcLdsO1WweoGD0X
- name: SS-oaYaN
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: VMESS-hJVgz
  type: vmess
  server: 141.193.213.169
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ustoucjjnid18sj6us.lovebaipiao.com
- name: VMESS-qffLe
  type: vmess
  server: xxcvfrrt6.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: xxcvfrrt6.999820.xyz
- name: VMESS-D8kJB
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-j173L
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-nljIo
  type: vmess
  server: cdn2.bpcdn.cc
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: gz4wah11v4bem6ws.lovebaipiao.com
- name: VMESS-IuXOx
  type: vmess
  server: 170.114.45.52
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ustoucjjnid18sj6us.lovebaipiao.com
- name: VMESS-QcmT0
  type: vmess
  server: v8.heduian.link
  port: 30808
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: v8.heduian.link
- name: VMESS-p4lDh
  type: vmess
  server: 2sdfre3.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: ''
- name: Trojan-runX4
  type: trojan
  server: 36.151.251.62
  port: 3330
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-NT12a
  type: trojan
  server: connector.wireshop.net
  port: 28332
  password: 48yaxxO653y4FDCFZTnzBODaaEXuTOOYSeDCaZYZlqN9ww0SlDeyp7Y2eKZ3AaSICl393
  params: ''
- name: Trojan-aHuck
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 1, sni: 120.233.44.201'
- name: Trojan-pd5Dh
  type: trojan
  server: yecea.coffeekit.net
  port: 28335
  password: 9SS3yFAOZTx3FaNENDljOC6e67482RDpO3KA85eID3w9y2aAcZDlYzCpYqCZlCSun0Bya
  params: ''
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-EGazw
  - SSR-yR4PU
  - VMESS-DiGj6
  - SS-1tu4y
  - SS-KdXEu
  - SS-MAUG7
  - SS-J3ocw
  - SS-6eze2
  - SS-dNsTu
  - SS-A4BCa
  - SS-ARbad
  - SS-7UibA
  - SS-FrQiC
  - SS-fQgMX
  - SS-hz4Zk
  - SS-Luymu
  - SS-1mTjZ
  - VMESS-zWy0h
  - VMESS-PqyIu
  - VMESS-PHol5
  - VMESS-Xrl7E
  - VMESS-9EYOT
  - VMESS-mnG3a
  - VMESS-CiAYR
  - VMESS-7K6Tt
  - VMESS-pJHmN
  - VMESS-WoXKW
  - VMESS-jLsOJ
  - VMESS-sVDAC
  - VMESS-iWQxT
  - VMESS-KwyLB
  - VMESS-LKuYv
  - Trojan-30h4n
  - Trojan-4GjhN
  - Trojan-zYIbP
  - Trojan-Fb2Lj
  - Trojan-sqbfq
  - Trojan-Q075r
  - Trojan-AcVR3
  - Trojan-QM5SA
  - Trojan-d6bv3
  - Trojan-bAQG6
  - Trojan-0B882
  - Trojan-qWaC1
  - Trojan-5m3Ea
  - Trojan-1Mt3C
  - Trojan-ml68p
  - Trojan-ghLRG
  - SS-aEluL
  - SS-oaYaN
  - VMESS-hJVgz
  - VMESS-qffLe
  - VMESS-D8kJB
  - VMESS-j173L
  - VMESS-nljIo
  - VMESS-IuXOx
  - VMESS-QcmT0
  - VMESS-p4lDh
  - Trojan-runX4
  - Trojan-NT12a
  - Trojan-aHuck
  - Trojan-pd5Dh
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-EGazw
  - SSR-yR4PU
  - VMESS-DiGj6
  - SS-1tu4y
  - SS-KdXEu
  - SS-MAUG7
  - SS-J3ocw
  - SS-6eze2
  - SS-dNsTu
  - SS-A4BCa
  - SS-ARbad
  - SS-7UibA
  - SS-FrQiC
  - SS-fQgMX
  - SS-hz4Zk
  - SS-Luymu
  - SS-1mTjZ
  - VMESS-zWy0h
  - VMESS-PqyIu
  - VMESS-PHol5
  - VMESS-Xrl7E
  - VMESS-9EYOT
  - VMESS-mnG3a
  - VMESS-CiAYR
  - VMESS-7K6Tt
  - VMESS-pJHmN
  - VMESS-WoXKW
  - VMESS-jLsOJ
  - VMESS-sVDAC
  - VMESS-iWQxT
  - VMESS-KwyLB
  - VMESS-LKuYv
  - Trojan-30h4n
  - Trojan-4GjhN
  - Trojan-zYIbP
  - Trojan-Fb2Lj
  - Trojan-sqbfq
  - Trojan-Q075r
  - Trojan-AcVR3
  - Trojan-QM5SA
  - Trojan-d6bv3
  - Trojan-bAQG6
  - Trojan-0B882
  - Trojan-qWaC1
  - Trojan-5m3Ea
  - Trojan-1Mt3C
  - Trojan-ml68p
  - Trojan-ghLRG
  - SS-aEluL
  - SS-oaYaN
  - VMESS-hJVgz
  - VMESS-qffLe
  - VMESS-D8kJB
  - VMESS-j173L
  - VMESS-nljIo
  - VMESS-IuXOx
  - VMESS-QcmT0
  - VMESS-p4lDh
  - Trojan-runX4
  - Trojan-NT12a
  - Trojan-aHuck
  - Trojan-pd5Dh
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
