port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-E200S
  type: ss
  server: 46.17.45.228
  port: 11111
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-OqvFN
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-Re3Oq
  type: vmess
  server: 195.154.40.247
  port: 19750
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-EZN2C
  type: vmess
  server: web.51.la
  port: 443
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-BjEw4
  type: vmess
  server: web.51.la
  port: 443
  uuid: e0c6b3b7-9f5b-4bd6-9abf-260663aa4f1b
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-0eMAr
  type: vmess
  server: web.51.la
  port: 443
  uuid: c6e84072-2e69-4928-90af-436b3fcd0663
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: SS-iWOE5
  type: ss
  server: 185.126.238.37
  port: 20004
  cipher: aes-256-gcm
  password: G58X9QBRUK3WE37K
- name: VMESS-4OEL3
  type: vmess
  server: v8.heduian.link
  port: 30808
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: v8.heduian.link
- name: VMESS-YiWXv
  type: vmess
  server: 104.21.112.1
  port: 2096
  uuid: b3928f8d-ea81-4d75-bcec-4016a072adff
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: de01.sh-cloudflare.sbs
- name: VMESS-qBi13
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-t1kar
  type: vmess
  server: 104.21.82.183
  port: 8880
  uuid: 5a7021e0-26b4-45d6-b175-fe551601ca97
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server26.beheshtbaneh.com
- name: VMESS-D5skq
  type: vmess
  server: 183.236.51.38
  port: 59652
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-DGH4t
  type: vmess
  server: de01.sh-cloudflare.sbs
  port: 2096
  uuid: 2703867d-dd8f-4f7f-93f4-ac6e4f56c7e8
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: de01.sh-cloudflare.sbs
- name: VMESS-noIgQ
  type: vmess
  server: tk.hzlt.tkddns.xyz
  port: 22643
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-c.tkong.cc
- name: Trojan-HgqOK
  type: trojan
  server: 3050cfd7-sx6ps0-sydxa9-fa3p.cm5.cnkuaishou.com
  port: 27231
  password: 905fcd78-866c-81e1-3cb8-1beb59d661ab
  params: 'allowInsecure: 0, sni: 3050cfd7-sx6ps0-sydxa9-fa3p.cm5.cnkuaishou.com'
- name: Trojan-AzcfE
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'sni: 120.233.44.201, allowInsecure: 1'
- name: Trojan-jPcSD
  type: trojan
  server: 104.21.83.113
  port: 443
  password: 4a3ee276-f50f-46f6-ba4d-13571732ab70
  params: 'sni: SxcDe3.859886.XYz, type: ws, path: /COp52Dbu3dvwvDWUxOqxq, host: sxcde3.859886.xyz'
- name: Trojan-jPfCW
  type: trojan
  server: 15.237.7.228
  port: 22222
  password: telegram-id-privatevpns
  params: 'security: tls, sni: trojan.burgerip.co.uk'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-E200S
  - SSR-OqvFN
  - VMESS-Re3Oq
  - VMESS-EZN2C
  - VMESS-BjEw4
  - VMESS-0eMAr
  - SS-iWOE5
  - VMESS-4OEL3
  - VMESS-YiWXv
  - VMESS-qBi13
  - VMESS-t1kar
  - VMESS-D5skq
  - VMESS-DGH4t
  - VMESS-noIgQ
  - Trojan-HgqOK
  - Trojan-AzcfE
  - Trojan-jPcSD
  - Trojan-jPfCW
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-E200S
  - SSR-OqvFN
  - VMESS-Re3Oq
  - VMESS-EZN2C
  - VMESS-BjEw4
  - VMESS-0eMAr
  - SS-iWOE5
  - VMESS-4OEL3
  - VMESS-YiWXv
  - VMESS-qBi13
  - VMESS-t1kar
  - VMESS-D5skq
  - VMESS-DGH4t
  - VMESS-noIgQ
  - Trojan-HgqOK
  - Trojan-AzcfE
  - Trojan-jPcSD
  - Trojan-jPfCW
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
