port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-Ebwlg
  type: ss
  server: 212.129.25.237
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-r2WHD
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-T4oxV
  type: vmess
  server: 195.154.40.247
  port: 33639
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-g6Hvw
  type: vmess
  server: web.51.la
  port: 443
  uuid: c6e84072-2e69-4928-90af-436b3fcd0663
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-caflb
  type: vmess
  server: web.51.la
  port: 443
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-RcWeH
  type: vmess
  server: web.51.la
  port: 443
  uuid: e0c6b3b7-9f5b-4bd6-9abf-260663aa4f1b
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: SS-GdsZz
  type: ss
  server: 178.128.55.155
  port: 47798
  cipher: chacha20-ietf-poly1305
  password: GbQTxOdhXR6OZ224WyQtwf
- name: SS-wW4iA
  type: ss
  server: 193.243.147.128
  port: 40368
  cipher: aes-256-gcm
  password: 7BcLdsO1WweoGD0X
- name: VMESS-sd9SQ
  type: vmess
  server: aflzzul.meiquankongjian.com
  port: 51515
  uuid: 342bacfd-2b8f-3f49-a16e-439db5b0b9d5
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /564dfa20/
    headers:
      Host: aflzzul.meiquankongjian.com
- name: VMESS-utBqT
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-VPCRN
  type: vmess
  server: xxxsde4.freevpnatm2025.dpdns.org
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: xxxsde4.freevpnatm2025.dpdns.org
- name: VMESS-UPJyb
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 716eded6-2201-4dbd-9d63-1638c9e8e677
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: pendar.onthewifi.com
- name: VMESS-AHqIJ
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 118287d2-e968-42e1-80d0-12fa2f5d38d6
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: sahand.serveminecraft.net
- name: VMESS-OeYBu
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: Trojan-dp9Az
  type: trojan
  server: 104.21.71.112
  port: 443
  password: 895552fa-6284-4c1d-ba00-3944e0c7c626
  params: 'sni: CFR56ty7890.288288.sHOP, type: ws, path: /By7cEmOrNRS58yeduy9AOG,
    host: cfr56ty7890.288288.shop'
- name: Trojan-kdlsD
  type: trojan
  server: 3.78.69.36
  port: 22222
  password: telegram-id-privatevpns
  params: 'security: tls, sni: trojan.burgerip.co.uk'
- name: Trojan-zxM2E
  type: trojan
  server: 172.67.144.126
  port: 443
  password: 895552fa-6284-4c1d-ba00-3944e0c7c626
  params: 'sni: CFR56ty7890.288288.sHOP, type: ws, path: /By7cEmOrNRS58yeduy9AOG,
    host: cfr56ty7890.288288.shop'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-Ebwlg
  - SSR-r2WHD
  - VMESS-T4oxV
  - VMESS-g6Hvw
  - VMESS-caflb
  - VMESS-RcWeH
  - SS-GdsZz
  - SS-wW4iA
  - VMESS-sd9SQ
  - VMESS-utBqT
  - VMESS-VPCRN
  - VMESS-UPJyb
  - VMESS-AHqIJ
  - VMESS-OeYBu
  - Trojan-dp9Az
  - Trojan-kdlsD
  - Trojan-zxM2E
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-Ebwlg
  - SSR-r2WHD
  - VMESS-T4oxV
  - VMESS-g6Hvw
  - VMESS-caflb
  - VMESS-RcWeH
  - SS-GdsZz
  - SS-wW4iA
  - VMESS-sd9SQ
  - VMESS-utBqT
  - VMESS-VPCRN
  - VMESS-UPJyb
  - VMESS-AHqIJ
  - VMESS-OeYBu
  - Trojan-dp9Az
  - Trojan-kdlsD
  - Trojan-zxM2E
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
