port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-khKQZ
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-v2WVe
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-PMmx0
  type: vmess
  server: 195.154.40.247
  port: 34747
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-192o6
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 16015
  cipher: aes-256-gcm
  password: 3IJTYIFVEXKSJ92G
- name: SS-frbj9
  type: ss
  server: 35.165.193.21
  port: 443
  cipher: aes-256-cfb
  password: awsps0501
- name: SS-8QUvA
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-6YYbz
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-DzgPC
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-P9QhC
  type: ss
  server: 120.233.147.197
  port: 23340
  cipher: chacha20-ietf-poly1305
  password: 0fbed6c9-0fb4-4ec3-8582-f569f8d773d5
- name: SS-r6CzS
  type: ss
  server: hkkh11v1.xpmc.cc
  port: 24043
  cipher: chacha20-ietf-poly1305
  password: 91a41f4e02dc
- name: SS-LIk5R
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18010
  cipher: aes-256-gcm
  password: HO86LQ8KH31JNMBQ
- name: SS-QIPkj
  type: ss
  server: 120.233.147.197
  port: 23335
  cipher: chacha20-ietf-poly1305
  password: 0fbed6c9-0fb4-4ec3-8582-f569f8d773d5
- name: SS-0l9Xi
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-3g21Z
  type: ss
  server: 103.140.136.76
  port: 443
  cipher: chacha20-ietf-poly1305
  password: b87e23b41338
- name: SS-J9YYa
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-TefPm
  type: ss
  server: 103.186.155.20
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
- name: VMESS-jv93J
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-t9Qgu
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-X3DcB
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-So84J
  type: vmess
  server: 120.198.71.216
  port: 35921
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-KQRqX
  type: vmess
  server: 120.198.71.216
  port: 35921
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-5qny7
  type: vmess
  server: 43.247.134.85
  port: 47010
  uuid: cbffb825-93d5-4a19-aed0-0936a48c84d3
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Fa5VM
  type: vmess
  server: 43.247.134.85
  port: 47010
  uuid: cbffb825-93d5-4a19-aed0-0936a48c84d3
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-ZNA3y
  type: vmess
  server: 183.236.51.38
  port: 39919
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-mR2dM
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-MMe3N
  type: vmess
  server: 03566c42-swzb40-sznzxg-1jfvb.hgc1.tcpbbr.net
  port: 8080
  uuid: 06b2ac52-fcc6-11ec-bb74-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-g1jqx
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-ga2e3
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-x7Krf
  type: vmess
  server: 183.236.51.38
  port: 49121
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-IXEzo
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-6FwZl
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-IPqMN
  type: vmess
  server: 183.236.51.38
  port: 49121
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-v1xR3
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-yynDY
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-LLhAx
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-VYPWb
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-RFi1s
  type: vmess
  server: 183.236.51.38
  port: 39919
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-qfSQQ
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-PEa36
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-xArqC
  type: vmess
  server: 47.74.41.147
  port: 53893
  uuid: 07287360-e12f-4f94-9c7a-54386c100d8a
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: Trojan-GiaKN
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: Trojan-u15w9
  type: trojan
  server: 36.151.251.60
  port: 28296
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-owwhA
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-4OxVw
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: SS-vUkHW
  type: ss
  server: 193.243.147.128
  port: 40368
  cipher: aes-256-gcm
  password: 7BcLdsO1WweoGD0X
- name: SS-yWKYy
  type: ss
  server: 120.233.147.197
  port: 23340
  cipher: chacha20-ietf-poly1305
  password: 0fbed6c9-0fb4-4ec3-8582-f569f8d773d5
- name: VMESS-X4OS3
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 118287d2-e968-42e1-80d0-12fa2f5d38d6
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: sahand.serveminecraft.net
- name: VMESS-XZoke
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-2faIU
  type: vmess
  server: 183.236.51.38
  port: 49121
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-xmOpc
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-pKdwE
  type: vmess
  server: 104.21.73.59
  port: 80
  uuid: 2f38f848-a899-4c87-9807-207a41615e3c
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /rongseven?ed=2048
    headers:
      Host: hk.freeyyds.dpdns.org
- name: VMESS-aZWS2
  type: vmess
  server: 104.18.149.76
  port: 443
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /aa
    headers:
      Host: us.kkp.me.eu.org
- name: VMESS-9gSCq
  type: vmess
  server: 183.109.131.86
  port: 29400
  uuid: eb590b8d-5e3c-4b24-8af1-f1ad55fee0ca
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: ''
    headers:
      Host: ''
- name: VMESS-gM1e5
  type: vmess
  server: hk2.lrzdx.uk
  port: 443
  uuid: db69d5bc-d36c-4903-f471-74b98c5cefe5
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /register
    headers:
      Host: ''
- name: VMESS-QqrQH
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: Trojan-bEhy4
  type: trojan
  server: 35.77.216.3
  port: 443
  password: CXCu72eya8wFeRySSFpDz3CN6jBYac5OIl3q0gSl8xZOADY3EK94pxZanDA3RT
  params: 'sni: broker.superpokemon.com'
- name: Trojan-BMb7V
  type: trojan
  server: 45.135.228.28
  port: 443
  password: '74260653385993900'
  params: 'sni: star-anchovy.shiner427.skin'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-khKQZ
  - SSR-v2WVe
  - VMESS-PMmx0
  - SS-192o6
  - SS-frbj9
  - SS-8QUvA
  - SS-6YYbz
  - SS-DzgPC
  - SS-P9QhC
  - SS-r6CzS
  - SS-LIk5R
  - SS-QIPkj
  - SS-0l9Xi
  - SS-3g21Z
  - SS-J9YYa
  - SS-TefPm
  - VMESS-jv93J
  - VMESS-t9Qgu
  - VMESS-X3DcB
  - VMESS-So84J
  - VMESS-KQRqX
  - VMESS-5qny7
  - VMESS-Fa5VM
  - VMESS-ZNA3y
  - VMESS-mR2dM
  - VMESS-MMe3N
  - VMESS-g1jqx
  - VMESS-ga2e3
  - VMESS-x7Krf
  - VMESS-IXEzo
  - VMESS-6FwZl
  - VMESS-IPqMN
  - VMESS-v1xR3
  - VMESS-yynDY
  - VMESS-LLhAx
  - VMESS-VYPWb
  - VMESS-RFi1s
  - VMESS-qfSQQ
  - VMESS-PEa36
  - VMESS-xArqC
  - Trojan-GiaKN
  - Trojan-u15w9
  - Trojan-owwhA
  - Trojan-4OxVw
  - SS-vUkHW
  - SS-yWKYy
  - VMESS-X4OS3
  - VMESS-XZoke
  - VMESS-2faIU
  - VMESS-xmOpc
  - VMESS-pKdwE
  - VMESS-aZWS2
  - VMESS-9gSCq
  - VMESS-gM1e5
  - VMESS-QqrQH
  - Trojan-bEhy4
  - Trojan-BMb7V
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-khKQZ
  - SSR-v2WVe
  - VMESS-PMmx0
  - SS-192o6
  - SS-frbj9
  - SS-8QUvA
  - SS-6YYbz
  - SS-DzgPC
  - SS-P9QhC
  - SS-r6CzS
  - SS-LIk5R
  - SS-QIPkj
  - SS-0l9Xi
  - SS-3g21Z
  - SS-J9YYa
  - SS-TefPm
  - VMESS-jv93J
  - VMESS-t9Qgu
  - VMESS-X3DcB
  - VMESS-So84J
  - VMESS-KQRqX
  - VMESS-5qny7
  - VMESS-Fa5VM
  - VMESS-ZNA3y
  - VMESS-mR2dM
  - VMESS-MMe3N
  - VMESS-g1jqx
  - VMESS-ga2e3
  - VMESS-x7Krf
  - VMESS-IXEzo
  - VMESS-6FwZl
  - VMESS-IPqMN
  - VMESS-v1xR3
  - VMESS-yynDY
  - VMESS-LLhAx
  - VMESS-VYPWb
  - VMESS-RFi1s
  - VMESS-qfSQQ
  - VMESS-PEa36
  - VMESS-xArqC
  - Trojan-GiaKN
  - Trojan-u15w9
  - Trojan-owwhA
  - Trojan-4OxVw
  - SS-vUkHW
  - SS-yWKYy
  - VMESS-X4OS3
  - VMESS-XZoke
  - VMESS-2faIU
  - VMESS-xmOpc
  - VMESS-pKdwE
  - VMESS-aZWS2
  - VMESS-9gSCq
  - VMESS-gM1e5
  - VMESS-QqrQH
  - Trojan-bEhy4
  - Trojan-BMb7V
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
