port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 119.29.29.29
  - 180.76.76.76
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.localdomain'
  - '*.example'
  - '*.invalid'
  - '*.localhost'
  - '*.test'
  - '*.local'
  - '*.home.arpa'
  - router.asus.com
  - localhost.sec.qq.com
  - localhost.ptlogin2.qq.com
  - +.msftconnecttest.com
proxies:
- name: SS-ePO2I
  type: ss
  server: 103.186.155.22
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
- name: SS-Jvs42
  type: ss
  server: zf1.10101251.xyz
  port: 20251
  cipher: aes-256-gcm
  password: 3ee90aa9-8831-4ea3-9425-c361090a938d
- name: SS-jMvDT
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-Bx0BG
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-uSU0G
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-dxbCJ
  type: ss
  server: p231.panda004.net
  port: 11389
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-PUptD
  type: ss
  server: pr.fastsoonlink.com
  port: 40030
  cipher: chacha20-ietf-poly1305
  password: 7905a32b-012c-4711-89e2-73b6713eca75
- name: SS-Jicvy
  type: ss
  server: 125.141.26.12
  port: 4857
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-1vuzI
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-Pgk98
  type: ss
  server: 121.0.97.29
  port: 30203
  cipher: chacha20-ietf-poly1305
  password: 264727317ef6
- name: SS-hW9a9
  type: ss
  server: 62.100.205.48
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-80ae9
  type: ss
  server: 163.172.114.203
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SS-6csbv
  type: ss
  server: 185.153.197.5
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-6uBoV
  type: ss
  server: 85.210.120.237
  port: 443
  cipher: chacha20-ietf-poly1305
  password: Bog0ELmMM9DSxDdQ
- name: SS-ebGja
  type: ss
  server: 156.251.179.238
  port: 20507
  cipher: chacha20-ietf-poly1305
  password: 08293b204707
- name: SS-7TtJZ
  type: ss
  server: 54.251.150.228
  port: 443
  cipher: aes-256-cfb
  password: qawszxc123
- name: SSR-KpeLf
  type: ssr
  server: 62.100.205.48
  port: 989
  obfs: plain
  protocol: origin
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SSR-6z4Te
  type: ssr
  server: dongtaiwang5.com
  port: 11000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-Q8uVp
  type: vmess
  server: v35.heduian.link
  port: 30835
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: v35.heduian.link
- name: VMESS-9JhBJ
  type: vmess
  server: 118.194.253.15
  port: 5663
  uuid: 986b3bc8-d0fb-4b60-b01f-28164e44cd48
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-LIwDr
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-jJhHR
  type: vmess
  server: 195.154.40.247
  port: 10912
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-Y1u1j
  type: vmess
  server: 183.236.51.38
  port: 41302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-6twOI
  type: vmess
  server: s1.cn-db.top
  port: 8880
  uuid: 05881d43-e9da-3d65-8cbe-fb0459b78557
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /dabai.in172.64.34.180
    headers:
      Host: 100-253-82-166.s1.cn-db.top
- name: VMESS-ARkLy
  type: vmess
  server: 8.219.72.131
  port: 51713
  uuid: 5ddb4459-ce08-462b-b920-efc464f7e94e
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-BIqI4
  type: vmess
  server: 45.147.201.231
  port: 20060
  uuid: 87d64ac5-f3bd-4e5b-9d4b-024e801c41c4
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-csqfx
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-0JoKL
  type: vmess
  server: 120.198.71.216
  port: 46159
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-HryWi
  type: vmess
  server: 43.99.247.11
  port: 10655
  uuid: cd9d6687-d1c0-49d9-89fa-2ac90940b17a
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-lSSsK
  type: vmess
  server: 203.227.44.74
  port: 31945
  uuid: 7ccbb147-38b8-4d7c-9201-2ad4ae8b8761
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-YyW2f
  type: vmess
  server: 120.198.71.216
  port: 46159
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-16U5J
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-t1ulH
  type: vmess
  server: 203.227.44.74
  port: 31945
  uuid: 7ccbb147-38b8-4d7c-9201-2ad4ae8b8761
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-yA4wb
  type: vmess
  server: 20.2.80.240
  port: 20452
  uuid: 52aba3eb-0a6f-4c2f-29c6-d4b18a1d7c3e
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-NsLaK
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-uwseh
  type: vmess
  server: 120.198.71.219
  port: 49355
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-AFzBN
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-m0JQw
  type: vmess
  server: 20.2.80.240
  port: 20452
  uuid: 52aba3eb-0a6f-4c2f-29c6-d4b18a1d7c3e
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-ub9ee
  type: vmess
  server: 120.232.153.40
  port: 31209
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-6wUy0
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-PM0tP
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-667Xp
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-u0gCp
  type: vmess
  server: 8.211.175.53
  port: 36668
  uuid: b798372a-54c8-4597-969e-8b00d2f76c09
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-8Vhwx
  type: vmess
  server: 120.232.153.40
  port: 31209
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-JS73X
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-TWahr
  type: vmess
  server: 183.236.51.38
  port: 41302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: Trojan-aJBnK
  type: trojan
  server: 203.156.253.11
  port: 39001
  password: 85f133142f04dbf6547da33895cfabb3
  params: 'allowInsecure: 1, sni: www.yrtok.com'
- name: Trojan-uBuYG
  type: trojan
  server: 36.151.251.62
  port: 38632
  password: FpQhGpIr
  params: 'allowInsecure: 1, sni: 36.151.251.62'
- name: Trojan-nhF34
  type: trojan
  server: 223.111.144.12
  port: 43196
  password: HrTsLJvh
  params: 'allowInsecure: 1'
- name: Trojan-rhJWM
  type: trojan
  server: 120.233.44.201
  port: 21179
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 0, sni: k30.tudou211.com'
- name: Trojan-8895t
  type: trojan
  server: 172.67.204.120
  port: 443
  password: 4a3ee276-f50f-46f6-ba4d-13571732ab70
  params: 'security: tls, sni: ddcDe.890603.XYz, type: ws, host: ddcde.890603.xyz,
    path: /COp52Dbu3dvwvDWUxOqxq'
- name: Trojan-DDbP0
  type: trojan
  server: 36.151.251.62
  port: 38632
  password: HrTsLJvh
  params: 'allowInsecure: 1'
- name: Trojan-4ynHp
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: Trojan-IzbkY
  type: trojan
  server: 113.99.140.184
  port: 39001
  password: 85f133142f04dbf6547da33895cfabb3
  params: 'allowInsecure: 1, sni: www.yrtok.com'
- name: Trojan-PBdrT
  type: trojan
  server: 120.233.128.68
  port: 39001
  password: 85f133142f04dbf6547da33895cfabb3
  params: 'allowInsecure: 1, sni: 120.233.128.68'
- name: Trojan-qTDa6
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'security: tls, sni: k28.tudou211.com, type: tcp, headerType: none'
- name: Trojan-3p0Zj
  type: trojan
  server: 36.151.251.62
  port: 38632
  password: HrTsLJvh
  params: 'allowInsecure: 1, sni: 36.151.251.62'
- name: Trojan-xKim8
  type: trojan
  server: 42.240.152.238
  port: 8842
  password: 1b4c16925f934c57b954a9f0f23dea33
  params: 'allowInsecure: 1, sni: brwx.spvpv.com'
- name: Trojan-fp3Ve
  type: trojan
  server: 36.151.251.62
  port: 38632
  password: HrTsLJvh
  params: 'allowInsecure: 1, sni: 36.151.251.62'
- name: Trojan-zo1Mt
  type: trojan
  server: 113.99.140.184
  port: 39001
  password: 85f133142f04dbf6547da33895cfabb3
  params: 'allowInsecure: 1, sni: www.yrtok.com'
- name: Trojan-UXLBM
  type: trojan
  server: 35eb0e91-sy0cg0-t7fz1r-8rja.cu.plebai.net
  port: 15229
  password: d18bcaf4-1323-11ec-a0fc-f23c913c8d2b
  params: ''
- name: Trojan-t0NVN
  type: trojan
  server: 36.151.251.62
  port: 38632
  password: FpQhGpIr
  params: 'allowInsecure: 1'
- name: Trojan-pEvNm
  type: trojan
  server: 15.236.243.30
  port: 22223
  password: telegram-id-directvpn
  params: 'sni: trojan.burgerip.co.uk'
- name: Trojan-wK4dM
  type: trojan
  server: 15.236.243.30
  port: 22222
  password: telegram-id-privatevpns
  params: 'security: tls, sni: trojan.burgerip.co.uk'
- name: Trojan-lecKh
  type: trojan
  server: 35eb0e91-sy0cg0-t7fz1r-8rja.cu.plebai.net
  port: 15229
  password: d18bcaf4-1323-11ec-a0fc-f23c913c8d2b
  params: 'allowInsecure: 0, sni: 35eb0e91-sy0cg0-t7fz1r-8rja.cu.plebai.net'
- name: Trojan-Govbn
  type: trojan
  server: 194.53.53.249
  port: 2083
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  params: 'sni: vle.amclubsvip.dpdns.org, allowInsecure: 1, type: ws, path: /?ed=2560&PROT_TYPE=trojan,
    host: vle.amclubsvip.dpdns.org, fp: chrome'
- name: Trojan-kItwP
  type: trojan
  server: 183.232.235.2
  port: 8313
  password: 2c605663-b89a-5734-a9d6-97d4743d72cf
  params: 'security: tls, sni: hk-13-568.flztjc.net, type: tcp, headerType: none'
- name: Trojan-XpdrJ
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: Trojan-enH4E
  type: trojan
  server: 36.151.251.56
  port: 4448
  password: FpQhGpIr
  params: 'allowInsecure: 1'
- name: Trojan-7yzqU
  type: trojan
  server: 120.233.128.68
  port: 39001
  password: 85f133142f04dbf6547da33895cfabb3
  params: 'allowInsecure: 0, sni: 120.233.128.68'
- name: Trojan-hwqP2
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-MLpUq
  type: trojan
  server: dozo01.flztjc.top
  port: 8313
  password: 2c605663-b89a-5734-a9d6-97d4743d72cf
  params: 'security: tls, sni: hk-13-568.flztjc.net, type: tcp, headerType: none'
proxy-groups:
- name: ♻️ 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  tolerance: 100
  proxies:
  - DIRECT
  - SS-ePO2I
  - SS-Jvs42
  - SS-jMvDT
  - SS-Bx0BG
  - SS-uSU0G
  - SS-dxbCJ
  - SS-PUptD
  - SS-Jicvy
  - SS-1vuzI
  - SS-Pgk98
  - SS-hW9a9
  - SS-80ae9
  - SS-6csbv
  - SS-6uBoV
  - SS-ebGja
  - SS-7TtJZ
  - SSR-KpeLf
  - SSR-6z4Te
  - VMESS-Q8uVp
  - VMESS-9JhBJ
  - VMESS-LIwDr
  - VMESS-jJhHR
  - VMESS-Y1u1j
  - VMESS-6twOI
  - VMESS-ARkLy
  - VMESS-BIqI4
  - VMESS-csqfx
  - VMESS-0JoKL
  - VMESS-HryWi
  - VMESS-lSSsK
  - VMESS-YyW2f
  - VMESS-16U5J
  - VMESS-t1ulH
  - VMESS-yA4wb
  - VMESS-NsLaK
  - VMESS-uwseh
  - VMESS-AFzBN
  - VMESS-m0JQw
  - VMESS-ub9ee
  - VMESS-6wUy0
  - VMESS-PM0tP
  - VMESS-667Xp
  - VMESS-u0gCp
  - VMESS-8Vhwx
  - VMESS-JS73X
  - VMESS-TWahr
  - Trojan-aJBnK
  - Trojan-uBuYG
  - Trojan-nhF34
  - Trojan-rhJWM
  - Trojan-8895t
  - Trojan-DDbP0
  - Trojan-4ynHp
  - Trojan-IzbkY
  - Trojan-PBdrT
  - Trojan-qTDa6
  - Trojan-3p0Zj
  - Trojan-xKim8
  - Trojan-fp3Ve
  - Trojan-zo1Mt
  - Trojan-UXLBM
  - Trojan-t0NVN
  - Trojan-pEvNm
  - Trojan-wK4dM
  - Trojan-lecKh
  - Trojan-Govbn
  - Trojan-kItwP
  - Trojan-XpdrJ
  - Trojan-enH4E
  - Trojan-7yzqU
  - Trojan-hwqP2
  - Trojan-MLpUq
- name: 🚀 节点选择
  type: select
  proxies:
  - DIRECT
  - SS-ePO2I
  - SS-Jvs42
  - SS-jMvDT
  - SS-Bx0BG
  - SS-uSU0G
  - SS-dxbCJ
  - SS-PUptD
  - SS-Jicvy
  - SS-1vuzI
  - SS-Pgk98
  - SS-hW9a9
  - SS-80ae9
  - SS-6csbv
  - SS-6uBoV
  - SS-ebGja
  - SS-7TtJZ
  - SSR-KpeLf
  - SSR-6z4Te
  - VMESS-Q8uVp
  - VMESS-9JhBJ
  - VMESS-LIwDr
  - VMESS-jJhHR
  - VMESS-Y1u1j
  - VMESS-6twOI
  - VMESS-ARkLy
  - VMESS-BIqI4
  - VMESS-csqfx
  - VMESS-0JoKL
  - VMESS-HryWi
  - VMESS-lSSsK
  - VMESS-YyW2f
  - VMESS-16U5J
  - VMESS-t1ulH
  - VMESS-yA4wb
  - VMESS-NsLaK
  - VMESS-uwseh
  - VMESS-AFzBN
  - VMESS-m0JQw
  - VMESS-ub9ee
  - VMESS-6wUy0
  - VMESS-PM0tP
  - VMESS-667Xp
  - VMESS-u0gCp
  - VMESS-8Vhwx
  - VMESS-JS73X
  - VMESS-TWahr
  - Trojan-aJBnK
  - Trojan-uBuYG
  - Trojan-nhF34
  - Trojan-rhJWM
  - Trojan-8895t
  - Trojan-DDbP0
  - Trojan-4ynHp
  - Trojan-IzbkY
  - Trojan-PBdrT
  - Trojan-qTDa6
  - Trojan-3p0Zj
  - Trojan-xKim8
  - Trojan-fp3Ve
  - Trojan-zo1Mt
  - Trojan-UXLBM
  - Trojan-t0NVN
  - Trojan-pEvNm
  - Trojan-wK4dM
  - Trojan-lecKh
  - Trojan-Govbn
  - Trojan-kItwP
  - Trojan-XpdrJ
  - Trojan-enH4E
  - Trojan-7yzqU
  - Trojan-hwqP2
  - Trojan-MLpUq
- name: 🌍 国外媒体
  type: select
  proxies:
  - 🚀 节点选择
  - ♻️ 自动选择
- name: 📲 电报信息
  type: select
  proxies:
  - 🚀 节点选择
  - ♻️ 自动选择
- name: Ⓜ️ 微软服务
  type: select
  proxies:
  - DIRECT
  - 🚀 节点选择
  - ♻️ 自动选择
- name: 🍎 苹果服务
  type: select
  proxies:
  - DIRECT
  - 🚀 节点选择
  - ♻️ 自动选择
- name: 🎯 全球直连
  type: select
  proxies:
  - DIRECT
  - 🚀 节点选择
  - ♻️ 自动选择
- name: 🛑 全球拦截
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: 🍃 应用净化
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: 🐟 漏网之鱼
  type: select
  proxies:
  - DIRECT
  - ♻️ 自动选择
rule-providers:
  Apple:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
    format: text
    interval: 3600
    path: ./Clash/Apple.list
  Telegram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    format: text
    interval: 3600
    path: ./Clash/Telegram.list
  ProxyLite:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
    format: text
    interval: 3600
    path: ./Clash/ProxyLite.list
  ChinaDomain:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    format: text
    interval: 3600
    path: ./Clash/ChinaDomain.list
  ChinaCompanyIp:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    format: text
    interval: 3600
    path: ./Clash/ChinaCompanyIp.list
  ProxyMedia:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
    format: text
    interval: 3600
    path: ./Clash/ProxyMedia.list
  LocalAreaNetwork:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    format: text
    interval: 3600
    path: ./Clash/LocalAreaNetwork.list
  Microsoft:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
    format: text
    interval: 3600
    path: ./Clash/Microsoft.list
  GoogleCN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    format: text
    interval: 3600
    path: ./Clash/GoogleCN.list
  BanAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    format: text
    interval: 3600
    path: ./Clash/BanAD.list
  BanProgramAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    format: text
    interval: 3600
    path: ./Clash/BanProgramAD.list
  SteamCN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
    format: text
    interval: 3600
    path: ./Clash/SteamCN.list
rules:
- RULE-SET,LocalAreaNetwork,🎯 全球直连
- RULE-SET,BanAD,🛑 全球拦截
- RULE-SET,BanProgramAD,🍃 应用净化
- RULE-SET,GoogleCN,🎯 全球直连
- RULE-SET,SteamCN,🎯 全球直连
- RULE-SET,Microsoft,Ⓜ️ 微软服务
- RULE-SET,Apple,🍎 苹果服务
- RULE-SET,ProxyMedia,🌍 国外媒体
- RULE-SET,Telegram,📲 电报信息
- RULE-SET,ProxyLite,🚀 节点选择
- RULE-SET,ChinaDomain,🎯 全球直连
- RULE-SET,ChinaCompanyIp,🎯 全球直连
- GEOIP,CN,🎯 全球直连
- MATCH,🐟 漏网之鱼
