port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-TpeG3
  type: ss
  server: 195.154.32.37
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-ai0Hk
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-EmCfH
  type: vmess
  server: 195.154.40.247
  port: 31549
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-Abma7
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-KtheP
  type: ss
  server: 47.129.170.255
  port: 443
  cipher: aes-256-cfb
  password: qawszxc123
- name: SS-ZsY0q
  type: ss
  server: 125.141.26.12
  port: 4857
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-q17Tc
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-gjTI5
  type: ss
  server: 154.90.63.177
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-bxHgD
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-r698K
  type: ss
  server: 43.226.17.17
  port: 19363
  cipher: chacha20-ietf-poly1305
  password: 2e96aa2f3054
- name: SS-SVPVg
  type: ss
  server: 103.186.154.29
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
- name: SS-oXK28
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-KRJdt
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-zWNT7
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 16012
  cipher: aes-256-gcm
  password: NEYGNTEW7HUQHA1I
- name: SS-HibLn
  type: ss
  server: hkkh11v1.xpmc.cc
  port: 36368
  cipher: chacha20-ietf-poly1305
  password: 91a41f4e02dc
- name: VMESS-dsr5N
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-8bhWA
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-NgjKp
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-O8MY5
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-ehjpA
  type: vmess
  server: e871a090-sva740-tcq5zn-19qpt.cm.plebai.net
  port: 15229
  uuid: 4b9ca118-7fab-11eb-bd3a-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-JoGXH
  type: vmess
  server: 34ac196c-svlb40-tdnzz0-1qtp7.cm5.p5pv.com
  port: 17232
  uuid: 3653c708-df72-11ee-aec1-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-mWZ5o
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-9ZzUS
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-6LfW6
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-ajwRL
  type: vmess
  server: e871a090-sva740-tcq5zn-19qpt.cm.plebai.net
  port: 15229
  uuid: 4b9ca118-7fab-11eb-bd3a-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-wwhsd
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Mk3fH
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-P2A9J
  type: vmess
  server: 183.236.51.38
  port: 49302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-GILDx
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-Rs2u4
  type: vmess
  server: tk.hzlt.tkddns.xyz
  port: 22642
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-b.tkong.cc
- name: VMESS-lGhP4
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-JckF6
  type: vmess
  server: 34ac196c-svlb40-tdnzz0-1qtp7.cm5.p5pv.com
  port: 17232
  uuid: 3653c708-df72-11ee-aec1-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-2G3zG
  type: vmess
  server: 183.236.51.38
  port: 49302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-oo8iY
  type: vmess
  server: 120.236.198.165
  port: 22641
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-a.tkong.cc
- name: VMESS-W44vt
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-ghPZl
  type: vmess
  server: 8.211.154.107
  port: 50951
  uuid: a3d04548-625c-4658-9ff0-f9a7835d1f6d
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: Trojan-XyrHB
  type: trojan
  server: bapus.koreanbbq.link
  port: 443
  password: 94Xn93e3F2uOxCE8De8upAAwnlI8ySRRj70Ol6zgYNBjZFCDK5Yaca3D8aT2qaxyEc0DK
  params: 'allowInsecure: 0'
- name: Trojan-zJfJE
  type: trojan
  server: 36.156.102.123
  port: 50723
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: 36.156.102.123'
- name: Trojan-VORpJ
  type: trojan
  server: f5ada702-swb8g0-t5fh9u-1uni.cu.plebai.net
  port: 15229
  password: adbd0a82-3336-11ed-bd7c-f23c913c8d2b
  params: 'allowInsecure: 1'
- name: Trojan-0J9GG
  type: trojan
  server: bd8e9b7d-swzb40-t5vrf3-716s.cu.plebai.net
  port: 15229
  password: 088a0bbe-4f9f-11ea-a15d-f23c913c8d2b
  params: 'allowInsecure: 1, sni: bd8e9b7d-swzb40-t5vrf3-716s.cu.plebai.net'
- name: Trojan-vAbaK
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: 36.151.251.61'
- name: Trojan-X9VVU
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: Trojan-GaHVw
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 1'
- name: Trojan-S1mP2
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 1, sni: 120.233.44.201'
- name: Trojan-jWVo1
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: Trojan-u29eX
  type: trojan
  server: usla.mjt000.com
  port: 443
  password: e4af2638-bb12-4e4a-84f1-a032e23ca63f
  params: 'allowInsecure: 0, sni: usla.mjt000.com'
- name: Trojan-eG0Lw
  type: trojan
  server: 36.151.251.62
  port: 13542
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-utO2p
  type: trojan
  server: 7d09e919-swq1s0-tcvn0z-1tlyg.cu.plebai.net
  port: 15229
  password: be8ba532-0dcf-11f0-9a65-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 7d09e919-swq1s0-tcvn0z-1tlyg.cu.plebai.net'
- name: Trojan-L2Xf1
  type: trojan
  server: 36.151.251.62
  port: 3330
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-sInTe
  type: trojan
  server: diagram.protocolbuffer.com
  port: 18334
  password: YaN8FFNe58nga3xAu3yTx0CSllcSeOnDZOj3SXROCz3S34B9D3F7Ka0aYa8yaxpXCDRKZ
  params: 'allowInsecure: 0'
- name: Trojan-VPmuS
  type: trojan
  server: 5f9d335d-swexs0-t5juhn-4tue.cu.plebai.net
  port: 15229
  password: fe506496-24eb-11ef-abd3-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 5f9d335d-swexs0-t5juhn-4tue.cu.plebai.net'
- name: Trojan-HGaCW
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: SS-n3LKj
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: VMESS-QZTt2
  type: vmess
  server: 5tghyu8.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: 5tghyu8.999820.xyz
- name: VMESS-ZZGNa
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 2ff97c6d-8557-42a4-b43f-19c77c5959ea
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: irsoft.sytes.net
- name: VMESS-1Evo7
  type: vmess
  server: 104.21.23.231
  port: 2082
  uuid: 2f821152-c3e9-4074-9185-2790e7425f42
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cs.flha.ru
- name: VMESS-r4edK
  type: vmess
  server: cdn1.bpcdn.cc
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: gz4wah11v4bem6ws.lovebaipiao.com
- name: VMESS-QVCuy
  type: vmess
  server: 193.123.81.105
  port: 443
  uuid: 9b456c2a-f2c1-45e1-87a9-b7628b04bb24
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: beyonddsz.cfd
- name: VMESS-OaFo8
  type: vmess
  server: 141.193.213.168
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ustoucjjnid18sj6us.lovebaipiao.com
- name: VMESS-1KFey
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 716eded6-2201-4dbd-9d63-1638c9e8e677
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: pendar.onthewifi.com
- name: VMESS-YUD3O
  type: vmess
  server: cloudflare.182682.xyz
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ustoucjjnid18sj6us.lovebaipiao.com
- name: VMESS-jvNeG
  type: vmess
  server: 34ac196c-svlb40-tdnzz0-1qtp7.cm5.p5pv.com
  port: 17232
  uuid: 3653c708-df72-11ee-aec1-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-8KQh4
  type: vmess
  server: 104.21.82.183
  port: 8880
  uuid: 5a7021e0-26b4-45d6-b175-fe551601ca97
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server26.beheshtbaneh.com
- name: VMESS-0WtdO
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: Trojan-Pyhj3
  type: trojan
  server: young.golfland.club
  port: 28331
  password: OE2xAc83AwKjlFpyAa8w7pD0TaC9ueY2eCy3x9S5Dn8npOIRlXE3BgNFxCqeNFIYyD404
  params: ''
- name: Trojan-LqHTn
  type: trojan
  server: 63.176.41.214
  port: 22223
  password: telegram-id-directvpn
  params: 'sni: trojan.burgerip.co.uk'
- name: Trojan-qg8K1
  type: trojan
  server: 36.151.251.62
  port: 3330
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-pIwwI
  type: trojan
  server: mailbox.meijireform.com
  port: 28332
  password: FNCEZ4Z336SlI8TRlyx3Y3SljwaxFexDNRxzya4R82DEOOCYR25eOSBq0K0ez9ZnaX9D3
  params: ''
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-TpeG3
  - SSR-ai0Hk
  - VMESS-EmCfH
  - SS-Abma7
  - SS-KtheP
  - SS-ZsY0q
  - SS-q17Tc
  - SS-gjTI5
  - SS-bxHgD
  - SS-r698K
  - SS-SVPVg
  - SS-oXK28
  - SS-KRJdt
  - SS-zWNT7
  - SS-HibLn
  - VMESS-dsr5N
  - VMESS-8bhWA
  - VMESS-NgjKp
  - VMESS-O8MY5
  - VMESS-ehjpA
  - VMESS-JoGXH
  - VMESS-mWZ5o
  - VMESS-9ZzUS
  - VMESS-6LfW6
  - VMESS-ajwRL
  - VMESS-wwhsd
  - VMESS-Mk3fH
  - VMESS-P2A9J
  - VMESS-GILDx
  - VMESS-Rs2u4
  - VMESS-lGhP4
  - VMESS-JckF6
  - VMESS-2G3zG
  - VMESS-oo8iY
  - VMESS-W44vt
  - VMESS-ghPZl
  - Trojan-XyrHB
  - Trojan-zJfJE
  - Trojan-VORpJ
  - Trojan-0J9GG
  - Trojan-vAbaK
  - Trojan-X9VVU
  - Trojan-GaHVw
  - Trojan-S1mP2
  - Trojan-jWVo1
  - Trojan-u29eX
  - Trojan-eG0Lw
  - Trojan-utO2p
  - Trojan-L2Xf1
  - Trojan-sInTe
  - Trojan-VPmuS
  - Trojan-HGaCW
  - SS-n3LKj
  - VMESS-QZTt2
  - VMESS-ZZGNa
  - VMESS-1Evo7
  - VMESS-r4edK
  - VMESS-QVCuy
  - VMESS-OaFo8
  - VMESS-1KFey
  - VMESS-YUD3O
  - VMESS-jvNeG
  - VMESS-8KQh4
  - VMESS-0WtdO
  - Trojan-Pyhj3
  - Trojan-LqHTn
  - Trojan-qg8K1
  - Trojan-pIwwI
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-TpeG3
  - SSR-ai0Hk
  - VMESS-EmCfH
  - SS-Abma7
  - SS-KtheP
  - SS-ZsY0q
  - SS-q17Tc
  - SS-gjTI5
  - SS-bxHgD
  - SS-r698K
  - SS-SVPVg
  - SS-oXK28
  - SS-KRJdt
  - SS-zWNT7
  - SS-HibLn
  - VMESS-dsr5N
  - VMESS-8bhWA
  - VMESS-NgjKp
  - VMESS-O8MY5
  - VMESS-ehjpA
  - VMESS-JoGXH
  - VMESS-mWZ5o
  - VMESS-9ZzUS
  - VMESS-6LfW6
  - VMESS-ajwRL
  - VMESS-wwhsd
  - VMESS-Mk3fH
  - VMESS-P2A9J
  - VMESS-GILDx
  - VMESS-Rs2u4
  - VMESS-lGhP4
  - VMESS-JckF6
  - VMESS-2G3zG
  - VMESS-oo8iY
  - VMESS-W44vt
  - VMESS-ghPZl
  - Trojan-XyrHB
  - Trojan-zJfJE
  - Trojan-VORpJ
  - Trojan-0J9GG
  - Trojan-vAbaK
  - Trojan-X9VVU
  - Trojan-GaHVw
  - Trojan-S1mP2
  - Trojan-jWVo1
  - Trojan-u29eX
  - Trojan-eG0Lw
  - Trojan-utO2p
  - Trojan-L2Xf1
  - Trojan-sInTe
  - Trojan-VPmuS
  - Trojan-HGaCW
  - SS-n3LKj
  - VMESS-QZTt2
  - VMESS-ZZGNa
  - VMESS-1Evo7
  - VMESS-r4edK
  - VMESS-QVCuy
  - VMESS-OaFo8
  - VMESS-1KFey
  - VMESS-YUD3O
  - VMESS-jvNeG
  - VMESS-8KQh4
  - VMESS-0WtdO
  - Trojan-Pyhj3
  - Trojan-LqHTn
  - Trojan-qg8K1
  - Trojan-pIwwI
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
