port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - +.srv.nintendo.net
  - +.stun.playstation.net
  - xbox.*.microsoft.com
  - +.xboxlive.com
  - '*.msftncsi.com'
  - '*.msftconnecttest.com'
  - lens.l.google.com
  - +.qq.com
  - +.music.163.com
  - localhost
  - +.local
  - +.internal
  - '*.aliyuncs.com'
  - stun.*.*
  - stun.*.*.*
  - +.cdn.jsdelivr.net
  nameservers:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - tls://dns.rubyfish.cn:853
  - 223.5.5.5
  - 119.29.29.29
  fallback:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  - 1.1.1.1
  - 8.8.8.8
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 224.0.0.0/4
    - 240.0.0.0/4
proxies:
- name: SS-kYDSU
  type: ss
  server: 120.233.128.98
  port: 30015
  cipher: aes-256-gcm
  password: dwz1GtF7
- name: SS-IQx6K
  type: ss
  server: 46.17.40.79
  port: 38674
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SS-bCuHH
  type: ss
  server: 185.153.197.5
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-71Ng5
  type: ss
  server: 222.112.15.140
  port: 56780
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SSR-ZxIQ6
  type: ssr
  server: dongtaiwang5.com
  port: 19000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-yt9ab
  type: vmess
  server: 741c97ef-sy9ls0-szpnze-1pr35.hgc1.tcpbbr.net
  port: 8080
  uuid: 6b7c1278-ff9d-11ee-84ca-f23c913c8d2b
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-HDwaP
  type: vmess
  server: hkt.gotochinatown.net
  port: 80
  uuid: 55cce5a4-56b7-11ee-af82-f23c9164ca5d
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-6DutZ
  type: vmess
  server: 43b5a616-sw04g0-swasv3-luwe.hgc1.tcpbbr.net
  port: 8080
  uuid: a2b0fd2b-716f-0df8-d4e2-03a1c00e5f1a
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-jdAAA
  type: vmess
  server: EeR4567.999824.xYz
  port: 443
  uuid: cdec9d57-661d-456a-bbf2-b4c38e9c6711
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /9dZlJLjHHrL0VwSolbqFpg
    headers:
      Host: eer4567.999824.xyz
- name: VMESS-sBQB6
  type: vmess
  server: v7.heduian.link
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: v7.heduian.link
- name: VMESS-4O5HW
  type: vmess
  server: 0.0.0.0
  port: 2
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-JYUqI
  type: vmess
  server: SDFGhyJu.999824.XYz
  port: 443
  uuid: 512d9674-db12-44ca-a1b5-654244549b65
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /uiAxvH6OkVk0VCfa7dX3JIrYk7zm
    headers:
      Host: SDFGhyJu.999824.XYz
- name: VMESS-DMJk4
  type: vmess
  server: 120.198.71.218
  port: 32915
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-iZeKa
  type: vmess
  server: 4da9741f-swq1s0-sxmlck-1ta58.hgc1.tcpbbr.net
  port: 8080
  uuid: e2d8b574-e089-11ef-9cc7-f23c9164ca5d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-mUb7d
  type: vmess
  server: 195.154.40.247
  port: 65314
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-3bNex
  type: vmess
  server: a9316cd5-sx4v40-t1ppk8-1i3g8.hgc1.tcpbbr.net
  port: 8080
  uuid: 437cef58-f10b-11ef-8eaf-f23c9164ca5d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-3mg3L
  type: vmess
  server: 0.0.0.0
  port: 1
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-ZsVrh
  type: vmess
  server: 8f67244c-sxlj40-t7r6w5-1ppvf.hgc1.tcpbbr.net
  port: 8080
  uuid: 8da5616c-8566-11ee-9a21-f23c9164ca5d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-IP2Qk
  type: vmess
  server: 111.26.109.79
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-GMiLS
  type: vmess
  server: us01.sh-cloudflare.sbs
  port: 8443
  uuid: f10598e2-c606-4945-bfde-e5730756a2dd
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us01.sh-cloudflare.sbs
- name: VMESS-NV0zo
  type: vmess
  server: 111.26.109.79
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-udosI
  type: vmess
  server: 104.19.173.68
  port: 2086
  uuid: dc33ccac-f27b-494d-98c0-553742e23268
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /hkz7hea3xiaco2j/ca1
    headers:
      Host: bpca1.catimecsgo.xyz
- name: VMESS-TUPEm
  type: vmess
  server: 5tzwc-g01.jp03-7d22-vm0.entry.fr0307a.art
  port: 21581
  uuid: fb43824b-a53d-3341-b27c-6e50dc0aa113
  alterId: 1
  cipher: none
  tls: true
  network: tcp
  tcp-opts:
    path: ''
    headers:
      Host: ''
- name: Trojan-IzbOq
  type: trojan
  server: fc111582-syof40-t39hdu-1tf4x.cm5.cnkuaishou.com
  port: 27235
  password: 202c296a-f34a-11ef-80e5-f23c9164ca5d
  params: 'security: tls, sni: fc111582-syof40-t39hdu-1tf4x.cm5.cnkuaishou.com'
- name: Trojan-N09Zw
  type: trojan
  server: 172.67.177.109
  port: 443
  password: 357b1bba-6400-4944-baff-1b933311ff28
  params: 'sni: EeEEeEEeeeeeeE.666461.xyz, allowInsecure: 1, type: ws, path: /HbjLgzKC7MBYIsgt,
    host: EeEEeEEeeeeeeE.666461.xyz, alpn: http%2F1.1'
- name: Trojan-pAzLc
  type: trojan
  server: 18.193.51.241
  port: 22222
  password: telegram-id-privatevpns
  params: 'security: tls, sni: trojan.burgerip.co.uk, type: tcp, alpn: http/1.1'
- name: Trojan-Q9kGD
  type: trojan
  server: xd-js.timiwc.com
  port: 59599
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 0, sni: k62.tudou211.com'
proxy-groups:
- name: ♻️ 自动选择
  type: url-test
  proxies:
  - SS-kYDSU
  - SS-IQx6K
  - SS-bCuHH
  - SS-71Ng5
  - SSR-ZxIQ6
  - VMESS-yt9ab
  - VMESS-HDwaP
  - VMESS-6DutZ
  - VMESS-jdAAA
  - VMESS-sBQB6
  - VMESS-4O5HW
  - VMESS-JYUqI
  - VMESS-DMJk4
  - VMESS-iZeKa
  - VMESS-mUb7d
  - VMESS-3bNex
  - VMESS-3mg3L
  - VMESS-ZsVrh
  - VMESS-IP2Qk
  - VMESS-GMiLS
  - VMESS-NV0zo
  - VMESS-udosI
  - VMESS-TUPEm
  - Trojan-IzbOq
  - Trojan-N09Zw
  - Trojan-pAzLc
  - Trojan-Q9kGD
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 国外媒体
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: Ⓜ️ 微软服务
  type: select
  proxies:
  - DIRECT
  - ♻️ 自动选择
- name: 🍎 苹果服务
  type: select
  proxies:
  - DIRECT
  - ♻️ 自动选择
- name: 📲 电报信息
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎮 游戏平台
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎬 YouTube
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎥 Netflix
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🔍 学术搜索
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🛑 全球拦截
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: 🐟 漏网之鱼
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,ip6-localhost,DIRECT
- DOMAIN-SUFFIX,ip6-loopback,DIRECT
- DOMAIN-SUFFIX,lan,DIRECT
- DOMAIN-SUFFIX,localhost,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN,yacd.metacubex.one,DIRECT
- DOMAIN,clash.metacubex.one,DIRECT
- DOMAIN-KEYWORD,apple,🍎 苹果服务
- DOMAIN-KEYWORD,icloud,🍎 苹果服务
- DOMAIN-SUFFIX,aaplimg.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple.co,🍎 苹果服务
- DOMAIN-SUFFIX,apple.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple-cloudkit.com,🍎 苹果服务
- DOMAIN-SUFFIX,appstore.com,🍎 苹果服务
- DOMAIN-SUFFIX,cdn-apple.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud-content.com,🍎 苹果服务
- DOMAIN-SUFFIX,me.com,🍎 苹果服务
- DOMAIN-SUFFIX,mzstatic.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple.news,🍎 苹果服务
- DOMAIN-SUFFIX,apple.com.cn,🍎 苹果服务
- DOMAIN-SUFFIX,appstore.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud.com.cn,🍎 苹果服务
- DOMAIN-KEYWORD,microsoft,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoft.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msecnd.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msedge.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,office.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,office.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,outlook.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,visualstudio.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windows.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windows.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windowsupdate.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,xbox.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,xboxlive.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msn.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoftonline.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoft365.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,skype.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,live.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,bing.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,hotmail.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,azureedge.net,Ⓜ️ 微软服务
- DOMAIN-KEYWORD,admarvel,🛑 全球拦截
- DOMAIN-KEYWORD,admaster,🛑 全球拦截
- DOMAIN-KEYWORD,adsage,🛑 全球拦截
- DOMAIN-KEYWORD,adsmogo,🛑 全球拦截
- DOMAIN-KEYWORD,adsrvmedia,🛑 全球拦截
- DOMAIN-KEYWORD,adwords,🛑 全球拦截
- DOMAIN-KEYWORD,analytics,🛑 全球拦截
- DOMAIN-KEYWORD,duomeng,🛑 全球拦截
- DOMAIN-KEYWORD,dwtrack,🛑 全球拦截
- DOMAIN-KEYWORD,guanggao,🛑 全球拦截
- DOMAIN-KEYWORD,lianmeng,🛑 全球拦截
- DOMAIN-KEYWORD,mopub,🛑 全球拦截
- DOMAIN-KEYWORD,omgmta,🛑 全球拦截
- DOMAIN-KEYWORD,openx,🛑 全球拦截
- DOMAIN-KEYWORD,partnerad,🛑 全球拦截
- DOMAIN-KEYWORD,pingfore,🛑 全球拦截
- DOMAIN-KEYWORD,supersonicads,🛑 全球拦截
- DOMAIN-KEYWORD,tracking,🛑 全球拦截
- DOMAIN-KEYWORD,uedas,🛑 全球拦截
- DOMAIN-KEYWORD,umeng,🛑 全球拦截
- DOMAIN-KEYWORD,usage,🛑 全球拦截
- DOMAIN-KEYWORD,wlmonitor,🛑 全球拦截
- DOMAIN-KEYWORD,zjtoolbar,🛑 全球拦截
- DOMAIN-SUFFIX,adjust.com,🛑 全球拦截
- DOMAIN-SUFFIX,ad.gt,🛑 全球拦截
- DOMAIN-SUFFIX,adcolony.com,🛑 全球拦截
- DOMAIN-SUFFIX,adform.net,🛑 全球拦截
- DOMAIN-SUFFIX,admob.com,🛑 全球拦截
- DOMAIN-SUFFIX,adnxs.com,🛑 全球拦截
- DOMAIN-SUFFIX,ads-twitter.com,🛑 全球拦截
- DOMAIN-SUFFIX,adsafeprotected.com,🛑 全球拦截
- DOMAIN-SUFFIX,adsrvr.org,🛑 全球拦截
- DOMAIN-SUFFIX,appsflyer.com,🛑 全球拦截
- DOMAIN-SUFFIX,doubleclick.net,🛑 全球拦截
- DOMAIN-SUFFIX,googleadservices.com,🛑 全球拦截
- DOMAIN-SUFFIX,googleadsserving.cn,🛑 全球拦截
- DOMAIN-SUFFIX,googlesyndication.com,🛑 全球拦截
- DOMAIN-SUFFIX,googletagmanager.com,🛑 全球拦截
- DOMAIN-SUFFIX,googletagservices.com,🛑 全球拦截
- DOMAIN-SUFFIX,mopub.com,🛑 全球拦截
- DOMAIN-SUFFIX,telegra.ph,📲 电报信息
- DOMAIN-SUFFIX,telegram.org,📲 电报信息
- DOMAIN-SUFFIX,telegram.me,📲 电报信息
- DOMAIN-SUFFIX,telesco.pe,📲 电报信息
- DOMAIN-SUFFIX,t.me,📲 电报信息
- DOMAIN-SUFFIX,tdesktop.com,📲 电报信息
- DOMAIN-SUFFIX,telegramdownload.com,📲 电报信息
- IP-CIDR,91.108.4.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.8.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.12.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.16.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.56.0/22,📲 电报信息,no-resolve
- IP-CIDR,149.154.160.0/20,📲 电报信息,no-resolve
- IP-CIDR,2001:b28:f23d::/48,📲 电报信息,no-resolve
- IP-CIDR,2001:b28:f23f::/48,📲 电报信息,no-resolve
- IP-CIDR,2001:67c:4e8::/48,📲 电报信息,no-resolve
- DOMAIN-SUFFIX,steamcontent.com,🎮 游戏平台
- DOMAIN-SUFFIX,steampowered.com,🎮 游戏平台
- DOMAIN-SUFFIX,steamstatic.com,🎮 游戏平台
- DOMAIN-SUFFIX,steamcommunity.com,🎮 游戏平台
- DOMAIN-SUFFIX,valvesoftware.com,🎮 游戏平台
- DOMAIN-SUFFIX,steam-chat.com,🎮 游戏平台
- DOMAIN-SUFFIX,epicgames.com,🎮 游戏平台
- DOMAIN-SUFFIX,epicgames.dev,🎮 游戏平台
- DOMAIN-SUFFIX,unrealengine.com,🎮 游戏平台
- DOMAIN-SUFFIX,playstation.com,🎮 游戏平台
- DOMAIN-SUFFIX,playstation.net,🎮 游戏平台
- DOMAIN-SUFFIX,playstationnetwork.com,🎮 游戏平台
- DOMAIN-SUFFIX,sony.com,🎮 游戏平台
- DOMAIN-SUFFIX,xbox.com,🎮 游戏平台
- DOMAIN-SUFFIX,xboxlive.com,🎮 游戏平台
- DOMAIN-SUFFIX,nintendo.com,🎮 游戏平台
- DOMAIN-SUFFIX,nintendo.net,🎮 游戏平台
- DOMAIN-SUFFIX,ea.com,🎮 游戏平台
- DOMAIN-SUFFIX,origin.com,🎮 游戏平台
- DOMAIN-SUFFIX,ubisoft.com,🎮 游戏平台
- DOMAIN-SUFFIX,ubi.com,🎮 游戏平台
- DOMAIN-SUFFIX,battle.net,🎮 游戏平台
- DOMAIN-SUFFIX,blizzard.com,🎮 游戏平台
- DOMAIN-SUFFIX,youtube.com,🎬 YouTube
- DOMAIN-SUFFIX,ytimg.com,🎬 YouTube
- DOMAIN-SUFFIX,googlevideo.com,🎬 YouTube
- DOMAIN-SUFFIX,youtu.be,🎬 YouTube
- DOMAIN-SUFFIX,yt.be,🎬 YouTube
- DOMAIN-SUFFIX,youtube-nocookie.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubeeducation.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubegaming.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubekids.com,🎬 YouTube
- DOMAIN-SUFFIX,netflix.com,🎥 Netflix
- DOMAIN-SUFFIX,netflix.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxext.com,🎥 Netflix
- DOMAIN-SUFFIX,nflximg.com,🎥 Netflix
- DOMAIN-SUFFIX,nflximg.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxso.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxvideo.net,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest0.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest1.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest2.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest3.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest4.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest5.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest6.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest7.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest8.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest9.com,🎥 Netflix
- DOMAIN-SUFFIX,scholar.google.com,🔍 学术搜索
- DOMAIN-SUFFIX,scholar.googleusercontent.com,🔍 学术搜索
- DOMAIN-SUFFIX,scholarcdn.net,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.tw,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.st,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.se,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.ren,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.ru,🔍 学术搜索
- DOMAIN-SUFFIX,researchgate.net,🔍 学术搜索
- DOMAIN-SUFFIX,springer.com,🔍 学术搜索
- DOMAIN-SUFFIX,sciencedirect.com,🔍 学术搜索
- DOMAIN-SUFFIX,acm.org,🔍 学术搜索
- DOMAIN-SUFFIX,ieee.org,🔍 学术搜索
- DOMAIN-SUFFIX,nature.com,🔍 学术搜索
- DOMAIN-SUFFIX,jstor.org,🔍 学术搜索
- DOMAIN-SUFFIX,9cache.com,🌍 国外媒体
- DOMAIN-SUFFIX,9gag.com,🌍 国外媒体
- DOMAIN-SUFFIX,abc.com,🌍 国外媒体
- DOMAIN-SUFFIX,bbc.co.uk,🌍 国外媒体
- DOMAIN-SUFFIX,bbc.com,🌍 国外媒体
- DOMAIN-SUFFIX,cnn.com,🌍 国外媒体
- DOMAIN-SUFFIX,deezer.com,🌍 国外媒体
- DOMAIN-SUFFIX,discord.com,🌍 国外媒体
- DOMAIN-SUFFIX,dropbox.com,🌍 国外媒体
- DOMAIN-SUFFIX,facebook.com,🌍 国外媒体
- DOMAIN-SUFFIX,fb.com,🌍 国外媒体
- DOMAIN-SUFFIX,fbcdn.net,🌍 国外媒体
- DOMAIN-SUFFIX,github.com,🌍 国外媒体
- DOMAIN-SUFFIX,github.io,🌍 国外媒体
- DOMAIN-SUFFIX,githubusercontent.com,🌍 国外媒体
- DOMAIN-SUFFIX,instagram.com,🌍 国外媒体
- DOMAIN-SUFFIX,pinterest.com,🌍 国外媒体
- DOMAIN-SUFFIX,reddit.com,🌍 国外媒体
- DOMAIN-SUFFIX,redditmedia.com,🌍 国外媒体
- DOMAIN-SUFFIX,redditstatic.com,🌍 国外媒体
- DOMAIN-SUFFIX,spotify.com,🌍 国外媒体
- DOMAIN-SUFFIX,tiktok.com,🌍 国外媒体
- DOMAIN-SUFFIX,ttvnw.net,🌍 国外媒体
- DOMAIN-SUFFIX,twitch.tv,🌍 国外媒体
- DOMAIN-SUFFIX,twitter.com,🌍 国外媒体
- DOMAIN-SUFFIX,x.com,🌍 国外媒体
- DOMAIN-SUFFIX,t.co,🌍 国外媒体
- DOMAIN-SUFFIX,medium.com,🌍 国外媒体
- DOMAIN-SUFFIX,flickr.com,🌍 国外媒体
- DOMAIN-SUFFIX,imgur.com,🌍 国外媒体
- DOMAIN-SUFFIX,soundcloud.com,🌍 国外媒体
- DOMAIN-SUFFIX,vimeo.com,🌍 国外媒体
- DOMAIN-SUFFIX,tumblr.com,🌍 国外媒体
- DOMAIN-SUFFIX,quora.com,🌍 国外媒体
- DOMAIN-SUFFIX,reuters.com,🌍 国外媒体
- DOMAIN-SUFFIX,nytimes.com,🌍 国外媒体
- DOMAIN-SUFFIX,wsj.com,🌍 国外媒体
- DOMAIN-SUFFIX,ft.com,🌍 国外媒体
- DOMAIN-SUFFIX,theguardian.com,🌍 国外媒体
- DOMAIN-SUFFIX,apnews.com,🌍 国外媒体
- DOMAIN-SUFFIX,bloomberg.com,🌍 国外媒体
- DOMAIN-SUFFIX,googlevideo.com,🌍 国外媒体
- DOMAIN-SUFFIX,googleapis.com,🌍 国外媒体
- DOMAIN-SUFFIX,gstatic.com,🌍 国外媒体
- DOMAIN-SUFFIX,google.com,🌍 国外媒体
- DOMAIN-SUFFIX,cn,DIRECT
- DOMAIN-SUFFIX,126.com,DIRECT
- DOMAIN-SUFFIX,126.net,DIRECT
- DOMAIN-SUFFIX,127.net,DIRECT
- DOMAIN-SUFFIX,163.com,DIRECT
- DOMAIN-SUFFIX,360buyimg.com,DIRECT
- DOMAIN-SUFFIX,36kr.com,DIRECT
- DOMAIN-SUFFIX,alipay.com,DIRECT
- DOMAIN-SUFFIX,aliyun.com,DIRECT
- DOMAIN-SUFFIX,alicdn.com,DIRECT
- DOMAIN-SUFFIX,amap.com,DIRECT
- DOMAIN-SUFFIX,baidu.com,DIRECT
- DOMAIN-SUFFIX,bdimg.com,DIRECT
- DOMAIN-SUFFIX,bdstatic.com,DIRECT
- DOMAIN-SUFFIX,bilibili.com,DIRECT
- DOMAIN-SUFFIX,bilivideo.com,DIRECT
- DOMAIN-SUFFIX,caiyunapp.com,DIRECT
- DOMAIN-SUFFIX,csdn.net,DIRECT
- DOMAIN-SUFFIX,ctrip.com,DIRECT
- DOMAIN-SUFFIX,didi.com,DIRECT
- DOMAIN-SUFFIX,douban.com,DIRECT
- DOMAIN-SUFFIX,doubanio.com,DIRECT
- DOMAIN-SUFFIX,douyin.com,DIRECT
- DOMAIN-SUFFIX,jd.com,DIRECT
- DOMAIN-SUFFIX,mi.com,DIRECT
- DOMAIN-SUFFIX,meituan.com,DIRECT
- DOMAIN-SUFFIX,meituan.net,DIRECT
- DOMAIN-SUFFIX,netease.com,DIRECT
- DOMAIN-SUFFIX,oschina.net,DIRECT
- DOMAIN-SUFFIX,qq.com,DIRECT
- DOMAIN-SUFFIX,qqmail.com,DIRECT
- DOMAIN-SUFFIX,sina.com,DIRECT
- DOMAIN-SUFFIX,sinaimg.com,DIRECT
- DOMAIN-SUFFIX,taobao.com,DIRECT
- DOMAIN-SUFFIX,tencent.com,DIRECT
- DOMAIN-SUFFIX,tmall.com,DIRECT
- DOMAIN-SUFFIX,weibo.com,DIRECT
- DOMAIN-SUFFIX,wechat.com,DIRECT
- DOMAIN-SUFFIX,weixin.com,DIRECT
- DOMAIN-SUFFIX,zhihu.com,DIRECT
- DOMAIN-SUFFIX,zhimg.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.net,DIRECT
- DOMAIN-SUFFIX,iqiyi.com,DIRECT
- DOMAIN-SUFFIX,iqiyipic.com,DIRECT
- DOMAIN-SUFFIX,acfun.cn,DIRECT
- DOMAIN-SUFFIX,aixifan.com,DIRECT
- DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
- DOMAIN-SUFFIX,xhscdn.com,DIRECT
- DOMAIN-SUFFIX,xiaomi.com,DIRECT
- DOMAIN-SUFFIX,xiaomiyoupin.com,DIRECT
- DOMAIN-SUFFIX,huawei.com,DIRECT
- DOMAIN-SUFFIX,hicloud.com,DIRECT
- DOMAIN-SUFFIX,vmall.com,DIRECT
- DOMAIN-SUFFIX,vivo.com,DIRECT
- DOMAIN-SUFFIX,oppo.com,DIRECT
- DOMAIN-SUFFIX,heytap.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,🐟 漏网之鱼
