port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-Vhsyh
  type: ss
  server: 46.17.45.228
  port: 11111
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-wu2Mo
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-gCp5E
  type: vmess
  server: 195.154.40.247
  port: 33639
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-kkFes
  type: vmess
  server: web.51.la
  port: 443
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-zMN0g
  type: vmess
  server: web.51.la
  port: 443
  uuid: c6e84072-2e69-4928-90af-436b3fcd0663
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-IxscX
  type: vmess
  server: web.51.la
  port: 443
  uuid: e0c6b3b7-9f5b-4bd6-9abf-260663aa4f1b
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: SS-HmW9S
  type: ss
  server: 193.243.147.128
  port: 40368
  cipher: aes-256-gcm
  password: 7BcLdsO1WweoGD0X
- name: SS-C48Zw
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18008
  cipher: aes-256-gcm
  password: 6EZ5QKFX60AVSUYT
- name: VMESS-ttVqY
  type: vmess
  server: hk2.lrzdx.uk
  port: 443
  uuid: db69d5bc-d36c-4903-f471-74b98c5cefe5
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /register
    headers:
      Host: ''
- name: VMESS-pQsd8
  type: vmess
  server: 183.236.51.38
  port: 49191
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-QPKbv
  type: vmess
  server: m11sdfg.890604.dpdns.org
  port: 80
  uuid: 0a28b420-4f7c-43ad-a29e-80068ce08263
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /lhU8ShsoPZlulnnYPb86csp
    headers:
      Host: ''
- name: VMESS-poVU7
  type: vmess
  server: 183.236.51.38
  port: 49302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-Nztfr
  type: vmess
  server: xcdvfrr54.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: ''
- name: VMESS-8gnJ5
  type: vmess
  server: 183.236.51.38
  port: 59652
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-5W3DH
  type: vmess
  server: tk.hzlt.tkddns.xyz
  port: 22643
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-c.tkong.cc
- name: Trojan-uzg99
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'sni: 36.151.251.61, allowInsecure: 1'
- name: Trojan-5Vy2N
  type: trojan
  server: 36.151.251.62
  port: 13542
  password: RlzoEILU
  params: 'sni: cdn.egvra.cn, allowInsecure: 1'
- name: Trojan-oFhBj
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'sni: 120.233.44.201, allowInsecure: 1'
- name: Trojan-6csWO
  type: trojan
  server: 3050cfd7-sx6ps0-sydxa9-fa3p.cm5.cnkuaishou.com
  port: 27231
  password: 905fcd78-866c-81e1-3cb8-1beb59d661ab
  params: 'allowInsecure: 0, sni: 3050cfd7-sx6ps0-sydxa9-fa3p.cm5.cnkuaishou.com'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-Vhsyh
  - SSR-wu2Mo
  - VMESS-gCp5E
  - VMESS-kkFes
  - VMESS-zMN0g
  - VMESS-IxscX
  - SS-HmW9S
  - SS-C48Zw
  - VMESS-ttVqY
  - VMESS-pQsd8
  - VMESS-QPKbv
  - VMESS-poVU7
  - VMESS-Nztfr
  - VMESS-8gnJ5
  - VMESS-5W3DH
  - Trojan-uzg99
  - Trojan-5Vy2N
  - Trojan-oFhBj
  - Trojan-6csWO
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-Vhsyh
  - SSR-wu2Mo
  - VMESS-gCp5E
  - VMESS-kkFes
  - VMESS-zMN0g
  - VMESS-IxscX
  - SS-HmW9S
  - SS-C48Zw
  - VMESS-ttVqY
  - VMESS-pQsd8
  - VMESS-QPKbv
  - VMESS-poVU7
  - VMESS-Nztfr
  - VMESS-8gnJ5
  - VMESS-5W3DH
  - Trojan-uzg99
  - Trojan-5Vy2N
  - Trojan-oFhBj
  - Trojan-6csWO
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
