port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-7a8lW
  type: ss
  server: 195.154.32.37
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-YeQLn
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-AM5Pf
  type: vmess
  server: 195.154.40.247
  port: 31549
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-8cW08
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18010
  cipher: aes-256-gcm
  password: TF63RS7M0DB9OJ3B
- name: SS-Xkw7P
  type: ss
  server: 125.141.26.12
  port: 4857
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-Y3eIX
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-4kq6H
  type: ss
  server: 3.38.139.172
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-JIKWT
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-tnMPd
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-krnx7
  type: ss
  server: 34.212.26.32
  port: 443
  cipher: aes-256-cfb
  password: awsps0501
- name: SS-SKugK
  type: ss
  server: hkkh11v1.xpmc.cc
  port: 20273
  cipher: chacha20-ietf-poly1305
  password: 91a41f4e02dc
- name: SS-SUEKX
  type: ss
  server: 43.226.17.17
  port: 14312
  cipher: chacha20-ietf-poly1305
  password: 2e96aa2f3054
- name: SS-zqqlB
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-EzynW
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 15007
  cipher: aes-256-gcm
  password: Q5XH89ZLTSGOQASZ
- name: SS-sOY7S
  type: ss
  server: 52.195.15.105
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-gqvxh
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: SS-P1IgJ
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: VMESS-ZX7JH
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-2hG9C
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-5shln
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-sHSE7
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-EHBo9
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-0Lx8r
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-mIDQ6
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-ls3Rm
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-9gkY0
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-j7HVz
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-A15AM
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-GN0eB
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-mYLEu
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-7nGXY
  type: vmess
  server: 8.211.154.107
  port: 50951
  uuid: a3d04548-625c-4658-9ff0-f9a7835d1f6d
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-NQrtB
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: Trojan-BsKvC
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: Trojan-0rrfP
  type: trojan
  server: 192.3.127.231
  port: 443
  password: Aimer
  params: 'allowInsecure: 0, sni: epmw.ambercc.filegear-sg.me, type: ws, host: epmw.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-XuMSe
  type: trojan
  server: 141.11.203.191
  port: 8443
  password: Aimer
  params: 'allowInsecure: 0, sni: epmw.ambercc.filegear-sg.me, type: ws, host: epmw.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-3hQaY
  type: trojan
  server: fireplace.wireshop.net
  port: 28331
  password: Ye8uA37l3C9FwpCwBCuZBy4SqlKTapDXEDnCZFRKSNlZCRSy0I3Yc8DxayzOeO3xaxjjg
  params: 'allowInsecure: 0'
- name: Trojan-wUq4S
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-4cB8k
  type: trojan
  server: 216.24.57.30
  port: 443
  password: tg-fq521free
  params: 'allowInsecure: 0, sni: torjan.xn--xhq44j.eu.org, type: ws, host: torjan.xn--xhq44j.eu.org,
    path: /'
- name: Trojan-dcPXi
  type: trojan
  server: closet.homeofbrave.net
  port: 18332
  password: BIRCauz5R2S8O3pZ56eg8yC43yla4T3D7znxCDFxSCODO9jA3NxAcaE3YYK3Sq8u9DxZg
  params: 'allowInsecure: 0'
- name: Trojan-lq7e8
  type: trojan
  server: luber.protocolbuffer.com
  port: 18333
  password: 4a3paxFKgSCxXBlaZn73Suc6AF3Dj3078l8FeDzDOXZOwyCDCICzeApyySAEgeTOSEZSZ
  params: 'allowInsecure: 0, sni: luber.protocolbuffer.com'
- name: Trojan-Ln6L9
  type: trojan
  server: huzzah.meijireform.com
  port: 28331
  password: Aa4cexaO3FReREXgAlp9CjyTjpaRNan3YDx6DxaDYFS3On0SqgF08CZcBpYxy3awXeEIC
  params: 'allowInsecure: 0'
- name: Trojan-ASlCs
  type: trojan
  server: cutlery.homeofbrave.net
  port: 28331
  password: e3qTaj4gOeDDzR8lzYXpyZDpga5a3SCwyE4CO6c738aZxwlaaAD0SYSYyXOlF9S3FRF0x
  params: 'allowInsecure: 0'
- name: Trojan-xAa0C
  type: trojan
  server: 108.165.152.58
  port: 2087
  password: Aimer
  params: 'allowInsecure: 0, sni: epmw.ambercc.filegear-sg.me, type: ws, host: epmw.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-nLoxh
  type: trojan
  server: huzzah.meijireform.com
  port: 28331
  password: Aa4cexaO3FReREXgAlp9CjyTjpaRNan3YDx6DxaDYFS3On0SqgF08CZcBpYxy3awXeEIC
  params: 'allowInsecure: 0, sni: huzzah.meijireform.com'
- name: Trojan-aPdgf
  type: trojan
  server: cutlery.homeofbrave.net
  port: 28331
  password: e3qTaj4gOeDDzR8lzYXpyZDpga5a3SCwyE4CO6c738aZxwlaaAD0SYSYyXOlF9S3FRF0x
  params: 'allowInsecure: 0, sni: cutlery.homeofbrave.net'
- name: Trojan-j47gF
  type: trojan
  server: usla.mjt000.com
  port: 443
  password: e4af2638-bb12-4e4a-84f1-a032e23ca63f
  params: 'allowInsecure: 0, sni: usla.mjt000.com'
- name: Trojan-Qnd5C
  type: trojan
  server: handles.homeofbrave.net
  port: 28332
  password: CYjXlaFOAyEDZaTe0gZaCOCyy4RwSyKYDq9SSpDCxzF33eA3SS06O28aj65a3lY3znO88
  params: 'allowInsecure: 0'
- name: Trojan-eqnIi
  type: trojan
  server: 192.210.207.89
  port: 20080
  password: Aimer
  params: 'allowInsecure: 0, sni: epme.ambercc.filegear-sg.me, type: ws, host: epme.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-4KCwW
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: SS-kFaLt
  type: ss
  server: 193.243.147.128
  port: 40368
  cipher: aes-256-gcm
  password: 7BcLdsO1WweoGD0X
- name: SS-GYDeO
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-zukGO
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: VMESS-ehBep
  type: vmess
  server: 104.21.96.1
  port: 2096
  uuid: b3928f8d-ea81-4d75-bcec-4016a072adff
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: de01.sh-cloudflare.sbs
- name: VMESS-4xajh
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 2ff97c6d-8557-42a4-b43f-19c77c5959ea
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: irsoft.sytes.net
- name: VMESS-lL2ef
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-rNCjf
  type: vmess
  server: 45.147.201.231
  port: 23090
  uuid: 0862298f-762e-4b0e-b162-915142f087a7
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-0wl9Z
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-YCg92
  type: vmess
  server: 120.198.44.126
  port: 47883
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-VCSg6
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: Trojan-NrhwW
  type: trojan
  server: hotpot.homeofbrave.net
  port: 443
  password: ZaEjzYF6Dj6393CaBZO2pyE9BES2ZZ65SzD5eA283qOyFSSX3C0KqCSIXSFyRqau4DezYwAa3XyCnj8
  params: ''
- name: Trojan-YmGJ1
  type: trojan
  server: siwtno.coffeekit.net
  port: 443
  password: 7gZIq33OD6pxTR0SCK4z3IDElYCSe9lRFXaCaOT380eSuCe9yj8OFanXYADAA5B3BwK62
  params: ''
- name: Trojan-Kwofl
  type: trojan
  server: napkin.homeofbrave.net
  port: 28332
  password: 8nCED4l05aB2CqO2ODlDTwK8YRcuazTa3SpIe3wxYR369eX5ZCFY7DFREFO36acxNyS3S
  params: ''
- name: Trojan-z8L0I
  type: trojan
  server: 61.221.48.98
  port: 28332
  password: 4NDgRx3YxEuCnxIFlOj84SnZy3gyXAa3OO383jzIRS7eCC2euaaeYKlTp9cFFCyCD0yap
  params: ''
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-7a8lW
  - SSR-YeQLn
  - VMESS-AM5Pf
  - SS-8cW08
  - SS-Xkw7P
  - SS-Y3eIX
  - SS-4kq6H
  - SS-JIKWT
  - SS-tnMPd
  - SS-krnx7
  - SS-SKugK
  - SS-SUEKX
  - SS-zqqlB
  - SS-EzynW
  - SS-sOY7S
  - SS-gqvxh
  - SS-P1IgJ
  - VMESS-ZX7JH
  - VMESS-2hG9C
  - VMESS-5shln
  - VMESS-sHSE7
  - VMESS-EHBo9
  - VMESS-0Lx8r
  - VMESS-mIDQ6
  - VMESS-ls3Rm
  - VMESS-9gkY0
  - VMESS-j7HVz
  - VMESS-A15AM
  - VMESS-GN0eB
  - VMESS-mYLEu
  - VMESS-7nGXY
  - VMESS-NQrtB
  - Trojan-BsKvC
  - Trojan-0rrfP
  - Trojan-XuMSe
  - Trojan-3hQaY
  - Trojan-wUq4S
  - Trojan-4cB8k
  - Trojan-dcPXi
  - Trojan-lq7e8
  - Trojan-Ln6L9
  - Trojan-ASlCs
  - Trojan-xAa0C
  - Trojan-nLoxh
  - Trojan-aPdgf
  - Trojan-j47gF
  - Trojan-Qnd5C
  - Trojan-eqnIi
  - Trojan-4KCwW
  - SS-kFaLt
  - SS-GYDeO
  - SS-zukGO
  - VMESS-ehBep
  - VMESS-4xajh
  - VMESS-lL2ef
  - VMESS-rNCjf
  - VMESS-0wl9Z
  - VMESS-YCg92
  - VMESS-VCSg6
  - Trojan-NrhwW
  - Trojan-YmGJ1
  - Trojan-Kwofl
  - Trojan-z8L0I
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-7a8lW
  - SSR-YeQLn
  - VMESS-AM5Pf
  - SS-8cW08
  - SS-Xkw7P
  - SS-Y3eIX
  - SS-4kq6H
  - SS-JIKWT
  - SS-tnMPd
  - SS-krnx7
  - SS-SKugK
  - SS-SUEKX
  - SS-zqqlB
  - SS-EzynW
  - SS-sOY7S
  - SS-gqvxh
  - SS-P1IgJ
  - VMESS-ZX7JH
  - VMESS-2hG9C
  - VMESS-5shln
  - VMESS-sHSE7
  - VMESS-EHBo9
  - VMESS-0Lx8r
  - VMESS-mIDQ6
  - VMESS-ls3Rm
  - VMESS-9gkY0
  - VMESS-j7HVz
  - VMESS-A15AM
  - VMESS-GN0eB
  - VMESS-mYLEu
  - VMESS-7nGXY
  - VMESS-NQrtB
  - Trojan-BsKvC
  - Trojan-0rrfP
  - Trojan-XuMSe
  - Trojan-3hQaY
  - Trojan-wUq4S
  - Trojan-4cB8k
  - Trojan-dcPXi
  - Trojan-lq7e8
  - Trojan-Ln6L9
  - Trojan-ASlCs
  - Trojan-xAa0C
  - Trojan-nLoxh
  - Trojan-aPdgf
  - Trojan-j47gF
  - Trojan-Qnd5C
  - Trojan-eqnIi
  - Trojan-4KCwW
  - SS-kFaLt
  - SS-GYDeO
  - SS-zukGO
  - VMESS-ehBep
  - VMESS-4xajh
  - VMESS-lL2ef
  - VMESS-rNCjf
  - VMESS-0wl9Z
  - VMESS-YCg92
  - VMESS-VCSg6
  - Trojan-NrhwW
  - Trojan-YmGJ1
  - Trojan-Kwofl
  - Trojan-z8L0I
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
