port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - +.srv.nintendo.net
  - +.stun.playstation.net
  - xbox.*.microsoft.com
  - +.xboxlive.com
  - '*.msftncsi.com'
  - '*.msftconnecttest.com'
  - lens.l.google.com
  - +.qq.com
  - +.music.163.com
  - localhost
  - +.local
  - +.internal
  - '*.aliyuncs.com'
  - stun.*.*
  - stun.*.*.*
  - +.cdn.jsdelivr.net
  nameservers:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - tls://dns.rubyfish.cn:853
  - 223.5.5.5
  - 119.29.29.29
  fallback:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  - 1.1.1.1
  - 8.8.8.8
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 224.0.0.0/4
    - 240.0.0.0/4
proxies:
- name: SS-ryUTY
  type: ss
  server: tinkered-pennies-puppies.freesocks.work
  port: 443
  cipher: chacha20-ietf-poly1305
  password: hbGrpfvNrJsUmKmPbR3iY2
- name: SS-CehGm
  type: ss
  server: 93.174.164.89
  port: 11201
  cipher: chacha20-ietf-poly1305
  password: 0bc801a7cac5f134
- name: SS-JdniR
  type: ss
  server: ldu.izenny.com
  port: 20149
  cipher: chacha20-ietf-poly1305
  password: c6d61cd1-d3dc-405e-afb2-d67815f4e4da
- name: SS-Loqgo
  type: ss
  server: 104.211.63.232
  port: 443
  cipher: chacha20-ietf-poly1305
  password: E2DnpxLTj4IEeLMQ
- name: SS-Isor7
  type: ss
  server: 144.217.164.29
  port: 12000
  cipher: aes-256-gcm
  password: 8JCsPssfgS8tiRwiMlhARg==
- name: SS-kxOLl
  type: ss
  server: 38.180.161.123
  port: 8119
  cipher: aes-256-gcm
  password: cdBIDV42DCwnfIN
- name: SS-AET9h
  type: ss
  server: ldu.izenny.com
  port: 46197
  cipher: chacha20-ietf-poly1305
  password: c6d61cd1-d3dc-405e-afb2-d67815f4e4da
- name: SS-t545l
  type: ss
  server: 66.94.125.178
  port: 80
  cipher: aes-256-gcm
  password: 14CLBaFBqwqxBJy6
- name: SS-v2Eda
  type: ss
  server: 147.45.135.39
  port: 4205
  cipher: chacha20-ietf-poly1305
  password: c0Zy18nHmjcUfome1fYPhA
- name: SS-8Rerf
  type: ss
  server: 103.106.228.175
  port: 8009
  cipher: aes-256-gcm
  password: XKFKl2rULjIp74
- name: SS-nljXb
  type: ss
  server: admin.c1.webramz.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
- name: SS-LSFXt
  type: ss
  server: 45.80.231.75
  port: 31019
  cipher: chacha20-ietf-poly1305
  password: XN6Xf0ZqwDeFrt39TQraen
- name: SS-QejwG
  type: ss
  server: 89.223.88.33
  port: 11201
  cipher: chacha20-ietf-poly1305
  password: 7c31a67b41b18c26
- name: SS-0SZfm
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-rOJNj
  type: ss
  server: download.riferoser.icu
  port: 56594
  cipher: chacha20-ietf-poly1305
  password: mzeMYBJYp4Bo7nA1qYLvv7QG73igtAA85nt4pr8A9ntx2qhDfYgRtiJ7iH7VrcneQKNmtvpbsvvFKPaUATYELi18iH56Ttr4
- name: SS-Yg1sy
  type: ss
  server: ldu.izenny.com
  port: 57927
  cipher: chacha20-ietf-poly1305
  password: c6d61cd1-d3dc-405e-afb2-d67815f4e4da
- name: SS-dtENa
  type: ss
  server: 124.217.247.205
  port: 51348
  cipher: chacha20-ietf-poly1305
  password: RZirHzSqyyb37DDIiQeDLZTJft5ZQGmUCwyA3wm5ath4j9Y3
- name: SS-UaWL4
  type: ss
  server: 149.102.132.186
  port: 80
  cipher: aes-256-gcm
  password: YhzqOeJsfuZ9rkkc
- name: SS-512Mb
  type: ss
  server: 38.180.2.141
  port: 5499
  cipher: aes-256-gcm
  password: lGqs95QkFHo2NV
- name: SS-RWQon
  type: ss
  server: 46.250.241.55
  port: 45720
  cipher: chacha20-ietf-poly1305
  password: c90d63dc7a6203af
- name: SS-CAu3R
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-AjGcC
  type: ss
  server: 51.75.168.50
  port: 13030
  cipher: chacha20-ietf-poly1305
  password: 6c815bb84c781da5
- name: SS-x1PX6
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-KtrVe
  type: ss
  server: 209.46.102.22
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: 1hhrqrokj3ag
- name: SS-ryMq8
  type: ss
  server: ldu.izenny.com
  port: 28063
  cipher: chacha20-ietf-poly1305
  password: c6d61cd1-d3dc-405e-afb2-d67815f4e4da
- name: SS-AI3jG
  type: ss
  server: series-a1.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
- name: SS-gymoH
  type: ss
  server: 91.107.144.0
  port: 1080
  cipher: chacha20-ietf-poly1305
  password: kDt8cG1TLg4uB0nUMOAu
- name: SS-NZ2cE
  type: ss
  server: 154.53.63.42
  port: 80
  cipher: aes-256-gcm
  password: SM7WYtAwvBORXKjI
- name: SS-kqPb7
  type: ss
  server: 154.46.31.106
  port: 443
  cipher: chacha20-ietf-poly1305
  password: QFWzCw2uX9B9i6qAYeFBIE
- name: SS-6DOJ5
  type: ss
  server: 5.181.2.76
  port: 36608
  cipher: chacha20-ietf-poly1305
  password: JOZ5Mb3nJCmmoKhd8Cc9aC
- name: SS-j58Lt
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-W3oTi
  type: ss
  server: 212.192.14.226
  port: 41968
  cipher: chacha20-ietf-poly1305
  password: gC7aQv9DsENaVfKzTPDKYV
- name: SS-2gUZ3
  type: ss
  server: 193.135.174.135
  port: 990
  cipher: chacha20-ietf-poly1305
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
- name: SS-zwD0Y
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-JM6by
  type: ss
  server: 57.128.214.100
  port: 12000
  cipher: aes-256-gcm
  password: 8JCsPssfgS8tiRwiMlhARg==
- name: SS-8Cvrs
  type: ss
  server: www.ccgfw.top
  port: 443
  cipher: aes-128-gcm
  password: 6601fb90e9b3
- name: SS-OPjPN
  type: ss
  server: 203.202.232.78
  port: 60299
  cipher: chacha20-ietf-poly1305
  password: AVLbEUEtBD59FsRqcNyEib
- name: VMESS-zCQpB
  type: vmess
  server: 2a14:7584:d0a2::a
  port: 23456
  uuid: bd48e0ac-e90e-4451-a4f2-abf061cfb890
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /alvin9999.com
    headers:
      Host: www.bing.com
- name: VMESS-ptMNt
  type: vmess
  server: dffgg.2no.ccwu.cc
  port: 443
  uuid: 2215657e-2af4-405f-b770-4e61b298d5b8
  alterId: 0
  cipher: null
  tls: true
  network: ws
  ws-opts:
    path: /PGsqb2SHJfbCLo
    headers:
      Host: dffgg.2no.ccwu.cc
- name: VMESS-ZfUt2
  type: vmess
  server: 198.62.62.199
  port: 443
  uuid: f08369d1-5ee7-4b16-d786-30bce12fc33c
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /f08369d1-5ee7-4b16-d786-30bce12fc33c
    headers:
      Host: ous3.dean52.top
- name: VMESS-VX5mn
  type: vmess
  server: t1.620720.xyz
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: t1.620720.xyz
- name: Trojan-BDbkS
  type: trojan
  server: 160.16.214.104
  port: 2001
  password: f7dbed8b1ca85124e793ba6c0bcfd0db
  params: 'security: tls, sni: www.nintendogames.net'
- name: Trojan-74nPC
  type: trojan
  server: 167.17.185.152
  port: 10889
  password: cTv.9PDdCt-wybBrG1qlxI5UJuaEj
  params: 'allowInsecure: 0, sni: ozon.ru'
- name: Trojan-Wvt0z
  type: trojan
  server: 220.130.58.136
  port: 35502
  password: c5355528-55a2-45df-b8fd-a48ce3c41413
  params: 'security: tls, sni: green2.cdntencentmusic.com'
- name: Trojan-yg3iy
  type: trojan
  server: 153.121.45.139
  port: 4674
  password: f7dbed8b1ca85124e793ba6c0bcfd0db
  params: 'security: tls, sni: www.nintendogames.net'
- name: Trojan-rm0rd
  type: trojan
  server: 58.152.18.189
  port: 443
  password: f7dbed8b1ca85124e793ba6c0bcfd0db
  params: 'security: tls, sni: www.nintendogames.net'
- name: Trojan-IlhHr
  type: trojan
  server: green2.cdntencentmusic.com
  port: 35501
  password: 04e5b584-1850-483d-a844-9ad624a4ca8e
  params: 'security: tls, sni: green2.cdntencentmusic.com'
- name: Trojan-I0Ve3
  type: trojan
  server: ubu.okaoclax.me
  port: 443
  password: 13c169be-8592-4eaa-94cb-69c859e7d987
  params: 'path: /trojan-ws, security: tls, host: ubu.okaoclax.me, type: ws, sni:
    ubu.okaoclax.me'
- name: Trojan-qms2r
  type: trojan
  server: 80.173.230.196
  port: 26279
  password: a5inYFE=JGV89+hjxIqgDp1tcWBd6
  params: 'sni: io.ozone.ru'
proxy-groups:
- name: ♻️ 自动选择
  type: url-test
  proxies:
  - SS-ryUTY
  - SS-CehGm
  - SS-JdniR
  - SS-Loqgo
  - SS-Isor7
  - SS-kxOLl
  - SS-AET9h
  - SS-t545l
  - SS-v2Eda
  - SS-8Rerf
  - SS-nljXb
  - SS-LSFXt
  - SS-QejwG
  - SS-0SZfm
  - SS-rOJNj
  - SS-Yg1sy
  - SS-dtENa
  - SS-UaWL4
  - SS-512Mb
  - SS-RWQon
  - SS-CAu3R
  - SS-AjGcC
  - SS-x1PX6
  - SS-KtrVe
  - SS-ryMq8
  - SS-AI3jG
  - SS-gymoH
  - SS-NZ2cE
  - SS-kqPb7
  - SS-6DOJ5
  - SS-j58Lt
  - SS-W3oTi
  - SS-2gUZ3
  - SS-zwD0Y
  - SS-JM6by
  - SS-8Cvrs
  - SS-OPjPN
  - VMESS-zCQpB
  - VMESS-ptMNt
  - VMESS-ZfUt2
  - VMESS-VX5mn
  - Trojan-BDbkS
  - Trojan-74nPC
  - Trojan-Wvt0z
  - Trojan-yg3iy
  - Trojan-rm0rd
  - Trojan-IlhHr
  - Trojan-I0Ve3
  - Trojan-qms2r
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 国外媒体
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: Ⓜ️ 微软服务
  type: select
  proxies:
  - DIRECT
  - ♻️ 自动选择
- name: 🍎 苹果服务
  type: select
  proxies:
  - DIRECT
  - ♻️ 自动选择
- name: 📲 电报信息
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎮 游戏平台
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎬 YouTube
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎥 Netflix
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🔍 学术搜索
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🛑 全球拦截
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: 🐟 漏网之鱼
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,ip6-localhost,DIRECT
- DOMAIN-SUFFIX,ip6-loopback,DIRECT
- DOMAIN-SUFFIX,lan,DIRECT
- DOMAIN-SUFFIX,localhost,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN,yacd.metacubex.one,DIRECT
- DOMAIN,clash.metacubex.one,DIRECT
- DOMAIN-KEYWORD,apple,🍎 苹果服务
- DOMAIN-KEYWORD,icloud,🍎 苹果服务
- DOMAIN-SUFFIX,aaplimg.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple.co,🍎 苹果服务
- DOMAIN-SUFFIX,apple.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple-cloudkit.com,🍎 苹果服务
- DOMAIN-SUFFIX,appstore.com,🍎 苹果服务
- DOMAIN-SUFFIX,cdn-apple.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud-content.com,🍎 苹果服务
- DOMAIN-SUFFIX,me.com,🍎 苹果服务
- DOMAIN-SUFFIX,mzstatic.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple.news,🍎 苹果服务
- DOMAIN-SUFFIX,apple.com.cn,🍎 苹果服务
- DOMAIN-SUFFIX,appstore.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud.com.cn,🍎 苹果服务
- DOMAIN-KEYWORD,microsoft,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoft.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msecnd.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msedge.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,office.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,office.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,outlook.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,visualstudio.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windows.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windows.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windowsupdate.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,xbox.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,xboxlive.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msn.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoftonline.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoft365.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,skype.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,live.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,bing.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,hotmail.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,azureedge.net,Ⓜ️ 微软服务
- DOMAIN-KEYWORD,admarvel,🛑 全球拦截
- DOMAIN-KEYWORD,admaster,🛑 全球拦截
- DOMAIN-KEYWORD,adsage,🛑 全球拦截
- DOMAIN-KEYWORD,adsmogo,🛑 全球拦截
- DOMAIN-KEYWORD,adsrvmedia,🛑 全球拦截
- DOMAIN-KEYWORD,adwords,🛑 全球拦截
- DOMAIN-KEYWORD,analytics,🛑 全球拦截
- DOMAIN-KEYWORD,duomeng,🛑 全球拦截
- DOMAIN-KEYWORD,dwtrack,🛑 全球拦截
- DOMAIN-KEYWORD,guanggao,🛑 全球拦截
- DOMAIN-KEYWORD,lianmeng,🛑 全球拦截
- DOMAIN-KEYWORD,mopub,🛑 全球拦截
- DOMAIN-KEYWORD,omgmta,🛑 全球拦截
- DOMAIN-KEYWORD,openx,🛑 全球拦截
- DOMAIN-KEYWORD,partnerad,🛑 全球拦截
- DOMAIN-KEYWORD,pingfore,🛑 全球拦截
- DOMAIN-KEYWORD,supersonicads,🛑 全球拦截
- DOMAIN-KEYWORD,tracking,🛑 全球拦截
- DOMAIN-KEYWORD,uedas,🛑 全球拦截
- DOMAIN-KEYWORD,umeng,🛑 全球拦截
- DOMAIN-KEYWORD,usage,🛑 全球拦截
- DOMAIN-KEYWORD,wlmonitor,🛑 全球拦截
- DOMAIN-KEYWORD,zjtoolbar,🛑 全球拦截
- DOMAIN-SUFFIX,adjust.com,🛑 全球拦截
- DOMAIN-SUFFIX,ad.gt,🛑 全球拦截
- DOMAIN-SUFFIX,adcolony.com,🛑 全球拦截
- DOMAIN-SUFFIX,adform.net,🛑 全球拦截
- DOMAIN-SUFFIX,admob.com,🛑 全球拦截
- DOMAIN-SUFFIX,adnxs.com,🛑 全球拦截
- DOMAIN-SUFFIX,ads-twitter.com,🛑 全球拦截
- DOMAIN-SUFFIX,adsafeprotected.com,🛑 全球拦截
- DOMAIN-SUFFIX,adsrvr.org,🛑 全球拦截
- DOMAIN-SUFFIX,appsflyer.com,🛑 全球拦截
- DOMAIN-SUFFIX,doubleclick.net,🛑 全球拦截
- DOMAIN-SUFFIX,googleadservices.com,🛑 全球拦截
- DOMAIN-SUFFIX,googleadsserving.cn,🛑 全球拦截
- DOMAIN-SUFFIX,googlesyndication.com,🛑 全球拦截
- DOMAIN-SUFFIX,googletagmanager.com,🛑 全球拦截
- DOMAIN-SUFFIX,googletagservices.com,🛑 全球拦截
- DOMAIN-SUFFIX,mopub.com,🛑 全球拦截
- DOMAIN-SUFFIX,telegra.ph,📲 电报信息
- DOMAIN-SUFFIX,telegram.org,📲 电报信息
- DOMAIN-SUFFIX,telegram.me,📲 电报信息
- DOMAIN-SUFFIX,telesco.pe,📲 电报信息
- DOMAIN-SUFFIX,t.me,📲 电报信息
- DOMAIN-SUFFIX,tdesktop.com,📲 电报信息
- DOMAIN-SUFFIX,telegramdownload.com,📲 电报信息
- IP-CIDR,91.108.4.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.8.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.12.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.16.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.56.0/22,📲 电报信息,no-resolve
- IP-CIDR,149.154.160.0/20,📲 电报信息,no-resolve
- IP-CIDR,2001:b28:f23d::/48,📲 电报信息,no-resolve
- IP-CIDR,2001:b28:f23f::/48,📲 电报信息,no-resolve
- IP-CIDR,2001:67c:4e8::/48,📲 电报信息,no-resolve
- DOMAIN-SUFFIX,steamcontent.com,🎮 游戏平台
- DOMAIN-SUFFIX,steampowered.com,🎮 游戏平台
- DOMAIN-SUFFIX,steamstatic.com,🎮 游戏平台
- DOMAIN-SUFFIX,steamcommunity.com,🎮 游戏平台
- DOMAIN-SUFFIX,valvesoftware.com,🎮 游戏平台
- DOMAIN-SUFFIX,steam-chat.com,🎮 游戏平台
- DOMAIN-SUFFIX,epicgames.com,🎮 游戏平台
- DOMAIN-SUFFIX,epicgames.dev,🎮 游戏平台
- DOMAIN-SUFFIX,unrealengine.com,🎮 游戏平台
- DOMAIN-SUFFIX,playstation.com,🎮 游戏平台
- DOMAIN-SUFFIX,playstation.net,🎮 游戏平台
- DOMAIN-SUFFIX,playstationnetwork.com,🎮 游戏平台
- DOMAIN-SUFFIX,sony.com,🎮 游戏平台
- DOMAIN-SUFFIX,xbox.com,🎮 游戏平台
- DOMAIN-SUFFIX,xboxlive.com,🎮 游戏平台
- DOMAIN-SUFFIX,nintendo.com,🎮 游戏平台
- DOMAIN-SUFFIX,nintendo.net,🎮 游戏平台
- DOMAIN-SUFFIX,ea.com,🎮 游戏平台
- DOMAIN-SUFFIX,origin.com,🎮 游戏平台
- DOMAIN-SUFFIX,ubisoft.com,🎮 游戏平台
- DOMAIN-SUFFIX,ubi.com,🎮 游戏平台
- DOMAIN-SUFFIX,battle.net,🎮 游戏平台
- DOMAIN-SUFFIX,blizzard.com,🎮 游戏平台
- DOMAIN-SUFFIX,youtube.com,🎬 YouTube
- DOMAIN-SUFFIX,ytimg.com,🎬 YouTube
- DOMAIN-SUFFIX,googlevideo.com,🎬 YouTube
- DOMAIN-SUFFIX,youtu.be,🎬 YouTube
- DOMAIN-SUFFIX,yt.be,🎬 YouTube
- DOMAIN-SUFFIX,youtube-nocookie.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubeeducation.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubegaming.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubekids.com,🎬 YouTube
- DOMAIN-SUFFIX,netflix.com,🎥 Netflix
- DOMAIN-SUFFIX,netflix.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxext.com,🎥 Netflix
- DOMAIN-SUFFIX,nflximg.com,🎥 Netflix
- DOMAIN-SUFFIX,nflximg.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxso.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxvideo.net,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest0.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest1.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest2.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest3.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest4.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest5.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest6.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest7.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest8.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest9.com,🎥 Netflix
- DOMAIN-SUFFIX,scholar.google.com,🔍 学术搜索
- DOMAIN-SUFFIX,scholar.googleusercontent.com,🔍 学术搜索
- DOMAIN-SUFFIX,scholarcdn.net,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.tw,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.st,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.se,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.ren,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.ru,🔍 学术搜索
- DOMAIN-SUFFIX,researchgate.net,🔍 学术搜索
- DOMAIN-SUFFIX,springer.com,🔍 学术搜索
- DOMAIN-SUFFIX,sciencedirect.com,🔍 学术搜索
- DOMAIN-SUFFIX,acm.org,🔍 学术搜索
- DOMAIN-SUFFIX,ieee.org,🔍 学术搜索
- DOMAIN-SUFFIX,nature.com,🔍 学术搜索
- DOMAIN-SUFFIX,jstor.org,🔍 学术搜索
- DOMAIN-SUFFIX,9cache.com,🌍 国外媒体
- DOMAIN-SUFFIX,9gag.com,🌍 国外媒体
- DOMAIN-SUFFIX,abc.com,🌍 国外媒体
- DOMAIN-SUFFIX,bbc.co.uk,🌍 国外媒体
- DOMAIN-SUFFIX,bbc.com,🌍 国外媒体
- DOMAIN-SUFFIX,cnn.com,🌍 国外媒体
- DOMAIN-SUFFIX,deezer.com,🌍 国外媒体
- DOMAIN-SUFFIX,discord.com,🌍 国外媒体
- DOMAIN-SUFFIX,dropbox.com,🌍 国外媒体
- DOMAIN-SUFFIX,facebook.com,🌍 国外媒体
- DOMAIN-SUFFIX,fb.com,🌍 国外媒体
- DOMAIN-SUFFIX,fbcdn.net,🌍 国外媒体
- DOMAIN-SUFFIX,github.com,🌍 国外媒体
- DOMAIN-SUFFIX,github.io,🌍 国外媒体
- DOMAIN-SUFFIX,githubusercontent.com,🌍 国外媒体
- DOMAIN-SUFFIX,instagram.com,🌍 国外媒体
- DOMAIN-SUFFIX,pinterest.com,🌍 国外媒体
- DOMAIN-SUFFIX,reddit.com,🌍 国外媒体
- DOMAIN-SUFFIX,redditmedia.com,🌍 国外媒体
- DOMAIN-SUFFIX,redditstatic.com,🌍 国外媒体
- DOMAIN-SUFFIX,spotify.com,🌍 国外媒体
- DOMAIN-SUFFIX,tiktok.com,🌍 国外媒体
- DOMAIN-SUFFIX,ttvnw.net,🌍 国外媒体
- DOMAIN-SUFFIX,twitch.tv,🌍 国外媒体
- DOMAIN-SUFFIX,twitter.com,🌍 国外媒体
- DOMAIN-SUFFIX,x.com,🌍 国外媒体
- DOMAIN-SUFFIX,t.co,🌍 国外媒体
- DOMAIN-SUFFIX,medium.com,🌍 国外媒体
- DOMAIN-SUFFIX,flickr.com,🌍 国外媒体
- DOMAIN-SUFFIX,imgur.com,🌍 国外媒体
- DOMAIN-SUFFIX,soundcloud.com,🌍 国外媒体
- DOMAIN-SUFFIX,vimeo.com,🌍 国外媒体
- DOMAIN-SUFFIX,tumblr.com,🌍 国外媒体
- DOMAIN-SUFFIX,quora.com,🌍 国外媒体
- DOMAIN-SUFFIX,reuters.com,🌍 国外媒体
- DOMAIN-SUFFIX,nytimes.com,🌍 国外媒体
- DOMAIN-SUFFIX,wsj.com,🌍 国外媒体
- DOMAIN-SUFFIX,ft.com,🌍 国外媒体
- DOMAIN-SUFFIX,theguardian.com,🌍 国外媒体
- DOMAIN-SUFFIX,apnews.com,🌍 国外媒体
- DOMAIN-SUFFIX,bloomberg.com,🌍 国外媒体
- DOMAIN-SUFFIX,googlevideo.com,🌍 国外媒体
- DOMAIN-SUFFIX,googleapis.com,🌍 国外媒体
- DOMAIN-SUFFIX,gstatic.com,🌍 国外媒体
- DOMAIN-SUFFIX,google.com,🌍 国外媒体
- DOMAIN-SUFFIX,cn,DIRECT
- DOMAIN-SUFFIX,126.com,DIRECT
- DOMAIN-SUFFIX,126.net,DIRECT
- DOMAIN-SUFFIX,127.net,DIRECT
- DOMAIN-SUFFIX,163.com,DIRECT
- DOMAIN-SUFFIX,360buyimg.com,DIRECT
- DOMAIN-SUFFIX,36kr.com,DIRECT
- DOMAIN-SUFFIX,alipay.com,DIRECT
- DOMAIN-SUFFIX,aliyun.com,DIRECT
- DOMAIN-SUFFIX,alicdn.com,DIRECT
- DOMAIN-SUFFIX,amap.com,DIRECT
- DOMAIN-SUFFIX,baidu.com,DIRECT
- DOMAIN-SUFFIX,bdimg.com,DIRECT
- DOMAIN-SUFFIX,bdstatic.com,DIRECT
- DOMAIN-SUFFIX,bilibili.com,DIRECT
- DOMAIN-SUFFIX,bilivideo.com,DIRECT
- DOMAIN-SUFFIX,caiyunapp.com,DIRECT
- DOMAIN-SUFFIX,csdn.net,DIRECT
- DOMAIN-SUFFIX,ctrip.com,DIRECT
- DOMAIN-SUFFIX,didi.com,DIRECT
- DOMAIN-SUFFIX,douban.com,DIRECT
- DOMAIN-SUFFIX,doubanio.com,DIRECT
- DOMAIN-SUFFIX,douyin.com,DIRECT
- DOMAIN-SUFFIX,jd.com,DIRECT
- DOMAIN-SUFFIX,mi.com,DIRECT
- DOMAIN-SUFFIX,meituan.com,DIRECT
- DOMAIN-SUFFIX,meituan.net,DIRECT
- DOMAIN-SUFFIX,netease.com,DIRECT
- DOMAIN-SUFFIX,oschina.net,DIRECT
- DOMAIN-SUFFIX,qq.com,DIRECT
- DOMAIN-SUFFIX,qqmail.com,DIRECT
- DOMAIN-SUFFIX,sina.com,DIRECT
- DOMAIN-SUFFIX,sinaimg.com,DIRECT
- DOMAIN-SUFFIX,taobao.com,DIRECT
- DOMAIN-SUFFIX,tencent.com,DIRECT
- DOMAIN-SUFFIX,tmall.com,DIRECT
- DOMAIN-SUFFIX,weibo.com,DIRECT
- DOMAIN-SUFFIX,wechat.com,DIRECT
- DOMAIN-SUFFIX,weixin.com,DIRECT
- DOMAIN-SUFFIX,zhihu.com,DIRECT
- DOMAIN-SUFFIX,zhimg.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.net,DIRECT
- DOMAIN-SUFFIX,iqiyi.com,DIRECT
- DOMAIN-SUFFIX,iqiyipic.com,DIRECT
- DOMAIN-SUFFIX,acfun.cn,DIRECT
- DOMAIN-SUFFIX,aixifan.com,DIRECT
- DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
- DOMAIN-SUFFIX,xhscdn.com,DIRECT
- DOMAIN-SUFFIX,xiaomi.com,DIRECT
- DOMAIN-SUFFIX,xiaomiyoupin.com,DIRECT
- DOMAIN-SUFFIX,huawei.com,DIRECT
- DOMAIN-SUFFIX,hicloud.com,DIRECT
- DOMAIN-SUFFIX,vmall.com,DIRECT
- DOMAIN-SUFFIX,vivo.com,DIRECT
- DOMAIN-SUFFIX,oppo.com,DIRECT
- DOMAIN-SUFFIX,heytap.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,🐟 漏网之鱼
