port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-RtDID
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-tlzjb
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-HMFmC
  type: vmess
  server: 195.154.40.247
  port: 27628
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-6CcRq
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18010
  cipher: aes-256-gcm
  password: HO86LQ8KH31JNMBQ
- name: SS-toO3j
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-RnLAU
  type: ss
  server: 35.165.193.21
  port: 443
  cipher: aes-256-cfb
  password: awsps0501
- name: SS-tF5Ag
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-Q2RBI
  type: ss
  server: 120.233.147.197
  port: 23340
  cipher: chacha20-ietf-poly1305
  password: 0fbed6c9-0fb4-4ec3-8582-f569f8d773d5
- name: SS-Z4a2q
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-IbJmc
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-wVO7L
  type: ss
  server: 103.186.155.20
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
- name: SS-JGLDY
  type: ss
  server: hkkh11v1.xpmc.cc
  port: 24043
  cipher: chacha20-ietf-poly1305
  password: 91a41f4e02dc
- name: SS-0lqZL
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-bsVEG
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 16015
  cipher: aes-256-gcm
  password: 3IJTYIFVEXKSJ92G
- name: SS-k3rHX
  type: ss
  server: 120.233.147.197
  port: 23335
  cipher: chacha20-ietf-poly1305
  password: 0fbed6c9-0fb4-4ec3-8582-f569f8d773d5
- name: SS-2wNuL
  type: ss
  server: 103.140.136.76
  port: 443
  cipher: chacha20-ietf-poly1305
  password: b87e23b41338
- name: VMESS-Ohdbr
  type: vmess
  server: 03566c42-swzb40-sznzxg-1jfvb.hgc1.tcpbbr.net
  port: 8080
  uuid: 06b2ac52-fcc6-11ec-bb74-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-QfXOC
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-TnSGI
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-aOixl
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-jKj4x
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-5B3PS
  type: vmess
  server: 183.236.51.38
  port: 49121
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-B4IiO
  type: vmess
  server: 120.198.71.216
  port: 35921
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-bj1eG
  type: vmess
  server: 43.247.134.85
  port: 47010
  uuid: cbffb825-93d5-4a19-aed0-0936a48c84d3
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Teicl
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-1Xuen
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Nj8tq
  type: vmess
  server: 183.236.51.38
  port: 39919
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-0QW4T
  type: vmess
  server: 120.198.71.216
  port: 35921
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-jlgW4
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-qeT2Z
  type: vmess
  server: 43.247.134.85
  port: 47010
  uuid: cbffb825-93d5-4a19-aed0-0936a48c84d3
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-t4h9Z
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-W7MQb
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-2QWTI
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-VKEjs
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-zOJL9
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-cQjeU
  type: vmess
  server: 183.236.51.38
  port: 39919
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-vh0N9
  type: vmess
  server: 47.74.41.147
  port: 53893
  uuid: 07287360-e12f-4f94-9c7a-54386c100d8a
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-n2sJe
  type: vmess
  server: 183.236.51.38
  port: 49121
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-qvBMM
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-BSPKN
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: Trojan-LQoXO
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: Trojan-2YuAP
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-4ic2O
  type: trojan
  server: 36.151.251.60
  port: 28296
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-9vnLh
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: SS-qPmau
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
- name: SS-eNE9I
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18010
  cipher: aes-256-gcm
  password: HO86LQ8KH31JNMBQ
- name: VMESS-SWhAB
  type: vmess
  server: 5tghyu8.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: 5tghyu8.999820.xyz
- name: VMESS-gnj9g
  type: vmess
  server: 183.236.51.38
  port: 41024
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-qu0Ed
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-twThN
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 118287d2-e968-42e1-80d0-12fa2f5d38d6
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: sahand.serveminecraft.net
- name: VMESS-jrV7y
  type: vmess
  server: 120.232.153.40
  port: 43292
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-4nosB
  type: vmess
  server: 120.198.71.219
  port: 44915
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-dkTq0
  type: vmess
  server: aflzzul.meiquankongjian.com
  port: 51515
  uuid: 342bacfd-2b8f-3f49-a16e-439db5b0b9d5
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /564dfa20/
    headers:
      Host: aflzzul.meiquankongjian.com
- name: VMESS-wyp1A
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-IvFF5
  type: vmess
  server: 183.236.51.38
  port: 39919
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-oKTLM
  type: vmess
  server: 120.198.71.219
  port: 49355
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-WJcMk
  type: vmess
  server: 104.21.82.183
  port: 8880
  uuid: 5a7021e0-26b4-45d6-b175-fe551601ca97
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server26.beheshtbaneh.com
- name: Trojan-xT2im
  type: trojan
  server: 36.151.251.60
  port: 28296
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-tn8t4
  type: trojan
  server: 87.121.33.202
  port: 443
  password: '74260653385993900'
  params: 'allowInsecure: 0, sni: safe-flounder.shiner427.skin'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-RtDID
  - SSR-tlzjb
  - VMESS-HMFmC
  - SS-6CcRq
  - SS-toO3j
  - SS-RnLAU
  - SS-tF5Ag
  - SS-Q2RBI
  - SS-Z4a2q
  - SS-IbJmc
  - SS-wVO7L
  - SS-JGLDY
  - SS-0lqZL
  - SS-bsVEG
  - SS-k3rHX
  - SS-2wNuL
  - VMESS-Ohdbr
  - VMESS-QfXOC
  - VMESS-TnSGI
  - VMESS-aOixl
  - VMESS-jKj4x
  - VMESS-5B3PS
  - VMESS-B4IiO
  - VMESS-bj1eG
  - VMESS-Teicl
  - VMESS-1Xuen
  - VMESS-Nj8tq
  - VMESS-0QW4T
  - VMESS-jlgW4
  - VMESS-qeT2Z
  - VMESS-t4h9Z
  - VMESS-W7MQb
  - VMESS-2QWTI
  - VMESS-VKEjs
  - VMESS-zOJL9
  - VMESS-cQjeU
  - VMESS-vh0N9
  - VMESS-n2sJe
  - VMESS-qvBMM
  - VMESS-BSPKN
  - Trojan-LQoXO
  - Trojan-2YuAP
  - Trojan-4ic2O
  - Trojan-9vnLh
  - SS-qPmau
  - SS-eNE9I
  - VMESS-SWhAB
  - VMESS-gnj9g
  - VMESS-qu0Ed
  - VMESS-twThN
  - VMESS-jrV7y
  - VMESS-4nosB
  - VMESS-dkTq0
  - VMESS-wyp1A
  - VMESS-IvFF5
  - VMESS-oKTLM
  - VMESS-WJcMk
  - Trojan-xT2im
  - Trojan-tn8t4
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-RtDID
  - SSR-tlzjb
  - VMESS-HMFmC
  - SS-6CcRq
  - SS-toO3j
  - SS-RnLAU
  - SS-tF5Ag
  - SS-Q2RBI
  - SS-Z4a2q
  - SS-IbJmc
  - SS-wVO7L
  - SS-JGLDY
  - SS-0lqZL
  - SS-bsVEG
  - SS-k3rHX
  - SS-2wNuL
  - VMESS-Ohdbr
  - VMESS-QfXOC
  - VMESS-TnSGI
  - VMESS-aOixl
  - VMESS-jKj4x
  - VMESS-5B3PS
  - VMESS-B4IiO
  - VMESS-bj1eG
  - VMESS-Teicl
  - VMESS-1Xuen
  - VMESS-Nj8tq
  - VMESS-0QW4T
  - VMESS-jlgW4
  - VMESS-qeT2Z
  - VMESS-t4h9Z
  - VMESS-W7MQb
  - VMESS-2QWTI
  - VMESS-VKEjs
  - VMESS-zOJL9
  - VMESS-cQjeU
  - VMESS-vh0N9
  - VMESS-n2sJe
  - VMESS-qvBMM
  - VMESS-BSPKN
  - Trojan-LQoXO
  - Trojan-2YuAP
  - Trojan-4ic2O
  - Trojan-9vnLh
  - SS-qPmau
  - SS-eNE9I
  - VMESS-SWhAB
  - VMESS-gnj9g
  - VMESS-qu0Ed
  - VMESS-twThN
  - VMESS-jrV7y
  - VMESS-4nosB
  - VMESS-dkTq0
  - VMESS-wyp1A
  - VMESS-IvFF5
  - VMESS-oKTLM
  - VMESS-WJcMk
  - Trojan-xT2im
  - Trojan-tn8t4
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
