port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-epQd0
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-jbRyV
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-OpmRy
  type: vmess
  server: 195.154.40.247
  port: 52602
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-3TGI5
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
- name: SS-fPk0b
  type: ss
  server: kr001.dogsvip.site
  port: 21001
  cipher: aes-256-gcm
  password: 323537df-dbdf-4f7e-a4c7-6c290d8e53ff
- name: VMESS-dbZEo
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-8lsKx
  type: vmess
  server: 120.198.71.216
  port: 35921
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-emVpj
  type: vmess
  server: v8.heduian.link
  port: 30808
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ''
- name: VMESS-90v7C
  type: vmess
  server: cc424de4-swd340-swp3f3-1teuc.hgc1.tcpbbr.net
  port: 8080
  uuid: a5a81a34-f257-11ef-ba82-f23c913c8d2b
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cc424de4-swd340-swp3f3-1teuc.hgc1.tcpbbr.net
- name: VMESS-yMqf6
  type: vmess
  server: 183.236.51.38
  port: 39919
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-tbxM8
  type: vmess
  server: 104.21.112.1
  port: 2053
  uuid: 8f78e709-2c5f-4c19-9f44-b5b5f80ab74c
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cc2d4.988988.shop
- name: VMESS-4XlRH
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-j6GVr
  type: vmess
  server: m11sdfg.890604.dpdns.org
  port: 80
  uuid: 0a28b420-4f7c-43ad-a29e-80068ce08263
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /lhU8ShsoPZlulnnYPb86csp
    headers:
      Host: m11sdfg.890604.dpdns.org
- name: VMESS-DLk1f
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-GWL8C
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: Trojan-B9PrS
  type: trojan
  server: dozo01.flztjc.top
  port: 8313
  password: 2c605663-b89a-5734-a9d6-97d4743d72cf
  params: 'allowInsecure: 0, sni: hk-13-568.flztjc.net'
- name: Trojan-1Tnl6
  type: trojan
  server: 36.151.251.60
  port: 28296
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-vsxfp
  type: trojan
  server: 36.151.251.59
  port: 44907
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-y2Olw
  type: trojan
  server: 35.181.77.27
  port: 22222
  password: telegram-id-privatevpns
  params: 'sni: trojan.burgerip.co.uk'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-epQd0
  - SSR-jbRyV
  - VMESS-OpmRy
  - SS-3TGI5
  - SS-fPk0b
  - VMESS-dbZEo
  - VMESS-8lsKx
  - VMESS-emVpj
  - VMESS-90v7C
  - VMESS-yMqf6
  - VMESS-tbxM8
  - VMESS-4XlRH
  - VMESS-j6GVr
  - VMESS-DLk1f
  - VMESS-GWL8C
  - Trojan-B9PrS
  - Trojan-1Tnl6
  - Trojan-vsxfp
  - Trojan-y2Olw
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-epQd0
  - SSR-jbRyV
  - VMESS-OpmRy
  - SS-3TGI5
  - SS-fPk0b
  - VMESS-dbZEo
  - VMESS-8lsKx
  - VMESS-emVpj
  - VMESS-90v7C
  - VMESS-yMqf6
  - VMESS-tbxM8
  - VMESS-4XlRH
  - VMESS-j6GVr
  - VMESS-DLk1f
  - VMESS-GWL8C
  - Trojan-B9PrS
  - Trojan-1Tnl6
  - Trojan-vsxfp
  - Trojan-y2Olw
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
