port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-9BaTo
  type: ss
  server: 195.154.32.37
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-02lrI
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-ZHFCK
  type: vmess
  server: 195.154.40.247
  port: 31549
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-JQpzm
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18010
  cipher: aes-256-gcm
  password: TF63RS7M0DB9OJ3B
- name: SS-0xtfQ
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-1sruf
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 15007
  cipher: aes-256-gcm
  password: Q5XH89ZLTSGOQASZ
- name: SS-Noqv5
  type: ss
  server: hkkh11v1.xpmc.cc
  port: 20273
  cipher: chacha20-ietf-poly1305
  password: 91a41f4e02dc
- name: SS-fWorU
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-U7QQZ
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: SS-yb2vK
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-hLRJB
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-NYwSl
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-H8tsM
  type: ss
  server: 52.195.15.105
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-yPpo9
  type: ss
  server: 125.141.26.12
  port: 4857
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-UGhNZ
  type: ss
  server: 3.38.139.172
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-DGfAK
  type: ss
  server: 34.212.26.32
  port: 443
  cipher: aes-256-cfb
  password: awsps0501
- name: SS-i0gjh
  type: ss
  server: 43.226.17.17
  port: 14312
  cipher: chacha20-ietf-poly1305
  password: 2e96aa2f3054
- name: VMESS-5urlj
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-eXs7A
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-St2aH
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-8ODUH
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-9Eseh
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-FlT4o
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-JF1NN
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Fk8BG
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-sRgnT
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-HB6Yj
  type: vmess
  server: 8.211.154.107
  port: 50951
  uuid: a3d04548-625c-4658-9ff0-f9a7835d1f6d
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-QBw7q
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-KPKu5
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-WPBbp
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-vg6Bc
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-pZOIr
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: Trojan-dcHUe
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: Trojan-jnKBB
  type: trojan
  server: 7d09e919-swq1s0-tcvn0z-1tlyg.cu.plebai.net
  port: 15229
  password: be8ba532-0dcf-11f0-9a65-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 7d09e919-swq1s0-tcvn0z-1tlyg.cu.plebai.net'
- name: Trojan-3vZaN
  type: trojan
  server: 5f9d335d-swexs0-t5juhn-4tue.cu.plebai.net
  port: 15229
  password: fe506496-24eb-11ef-abd3-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 5f9d335d-swexs0-t5juhn-4tue.cu.plebai.net'
- name: Trojan-RzEzG
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: 36.151.251.61'
- name: Trojan-HKDC8
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 1, sni: 120.233.44.201'
- name: Trojan-rfTYv
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 1'
- name: Trojan-LWJKx
  type: trojan
  server: bapus.koreanbbq.link
  port: 443
  password: 94Xn93e3F2uOxCE8De8upAAwnlI8ySRRj70Ol6zgYNBjZFCDK5Yaca3D8aT2qaxyEc0DK
  params: 'allowInsecure: 0'
- name: Trojan-SnPjb
  type: trojan
  server: bd8e9b7d-swzb40-t5vrf3-716s.cu.plebai.net
  port: 15229
  password: 088a0bbe-4f9f-11ea-a15d-f23c913c8d2b
  params: 'allowInsecure: 1, sni: bd8e9b7d-swzb40-t5vrf3-716s.cu.plebai.net'
- name: Trojan-RKTc3
  type: trojan
  server: 36.151.251.62
  port: 3330
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-6EzLJ
  type: trojan
  server: 36.151.251.62
  port: 13542
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-JjyOP
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: Trojan-N5rSq
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-5rKdd
  type: trojan
  server: f5ada702-swb8g0-t5fh9u-1uni.cu.plebai.net
  port: 15229
  password: adbd0a82-3336-11ed-bd7c-f23c913c8d2b
  params: 'allowInsecure: 1'
- name: Trojan-5JxAZ
  type: trojan
  server: usla.mjt000.com
  port: 443
  password: e4af2638-bb12-4e4a-84f1-a032e23ca63f
  params: 'allowInsecure: 0, sni: usla.mjt000.com'
- name: Trojan-r4WP0
  type: trojan
  server: 36.156.102.123
  port: 50723
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: 36.156.102.123'
- name: Trojan-Bhznd
  type: trojan
  server: diagram.protocolbuffer.com
  port: 18334
  password: YaN8FFNe58nga3xAu3yTx0CSllcSeOnDZOj3SXROCz3S34B9D3F7Ka0aYa8yaxpXCDRKZ
  params: 'allowInsecure: 0'
- name: SS-BL8My
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: SS-sPQup
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: VMESS-loQQn
  type: vmess
  server: 2sdfre3.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: ''
- name: VMESS-SCSGl
  type: vmess
  server: www.wn03.cc
  port: 80
  uuid: 2f38f848-a899-4c87-9807-207a41615e3c
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /rongseven?ed=2048
    headers:
      Host: us.freeyyds.dpdns.org
- name: VMESS-UCo6k
  type: vmess
  server: 141.193.213.169
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ustoucjjnid18sj6us.lovebaipiao.com
- name: VMESS-3rCZd
  type: vmess
  server: 170.114.45.53
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ustoucjjnid18sj6us.lovebaipiao.com
- name: VMESS-W7A1a
  type: vmess
  server: us01.sh-cloudflare.sbs
  port: 8443
  uuid: 2bd0c9d7-f239-437e-a1e1-6cf830af2a1a
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us01.sh-cloudflare.sbs
- name: VMESS-aRVxg
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 118287d2-e968-42e1-80d0-12fa2f5d38d6
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: sahand.serveminecraft.net
- name: VMESS-SUwro
  type: vmess
  server: 170.114.45.52
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ustoucjjnid18sj6us.lovebaipiao.com
- name: VMESS-cknkP
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-zsSVM
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-1fkzB
  type: vmess
  server: cdn3.bpcdn.cc
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: gz4wah11v4bem6ws.lovebaipiao.com
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-9BaTo
  - SSR-02lrI
  - VMESS-ZHFCK
  - SS-JQpzm
  - SS-0xtfQ
  - SS-1sruf
  - SS-Noqv5
  - SS-fWorU
  - SS-U7QQZ
  - SS-yb2vK
  - SS-hLRJB
  - SS-NYwSl
  - SS-H8tsM
  - SS-yPpo9
  - SS-UGhNZ
  - SS-DGfAK
  - SS-i0gjh
  - VMESS-5urlj
  - VMESS-eXs7A
  - VMESS-St2aH
  - VMESS-8ODUH
  - VMESS-9Eseh
  - VMESS-FlT4o
  - VMESS-JF1NN
  - VMESS-Fk8BG
  - VMESS-sRgnT
  - VMESS-HB6Yj
  - VMESS-QBw7q
  - VMESS-KPKu5
  - VMESS-WPBbp
  - VMESS-vg6Bc
  - VMESS-pZOIr
  - Trojan-dcHUe
  - Trojan-jnKBB
  - Trojan-3vZaN
  - Trojan-RzEzG
  - Trojan-HKDC8
  - Trojan-rfTYv
  - Trojan-LWJKx
  - Trojan-SnPjb
  - Trojan-RKTc3
  - Trojan-6EzLJ
  - Trojan-JjyOP
  - Trojan-N5rSq
  - Trojan-5rKdd
  - Trojan-5JxAZ
  - Trojan-r4WP0
  - Trojan-Bhznd
  - SS-BL8My
  - SS-sPQup
  - VMESS-loQQn
  - VMESS-SCSGl
  - VMESS-UCo6k
  - VMESS-3rCZd
  - VMESS-W7A1a
  - VMESS-aRVxg
  - VMESS-SUwro
  - VMESS-cknkP
  - VMESS-zsSVM
  - VMESS-1fkzB
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-9BaTo
  - SSR-02lrI
  - VMESS-ZHFCK
  - SS-JQpzm
  - SS-0xtfQ
  - SS-1sruf
  - SS-Noqv5
  - SS-fWorU
  - SS-U7QQZ
  - SS-yb2vK
  - SS-hLRJB
  - SS-NYwSl
  - SS-H8tsM
  - SS-yPpo9
  - SS-UGhNZ
  - SS-DGfAK
  - SS-i0gjh
  - VMESS-5urlj
  - VMESS-eXs7A
  - VMESS-St2aH
  - VMESS-8ODUH
  - VMESS-9Eseh
  - VMESS-FlT4o
  - VMESS-JF1NN
  - VMESS-Fk8BG
  - VMESS-sRgnT
  - VMESS-HB6Yj
  - VMESS-QBw7q
  - VMESS-KPKu5
  - VMESS-WPBbp
  - VMESS-vg6Bc
  - VMESS-pZOIr
  - Trojan-dcHUe
  - Trojan-jnKBB
  - Trojan-3vZaN
  - Trojan-RzEzG
  - Trojan-HKDC8
  - Trojan-rfTYv
  - Trojan-LWJKx
  - Trojan-SnPjb
  - Trojan-RKTc3
  - Trojan-6EzLJ
  - Trojan-JjyOP
  - Trojan-N5rSq
  - Trojan-5rKdd
  - Trojan-5JxAZ
  - Trojan-r4WP0
  - Trojan-Bhznd
  - SS-BL8My
  - SS-sPQup
  - VMESS-loQQn
  - VMESS-SCSGl
  - VMESS-UCo6k
  - VMESS-3rCZd
  - VMESS-W7A1a
  - VMESS-aRVxg
  - VMESS-SUwro
  - VMESS-cknkP
  - VMESS-zsSVM
  - VMESS-1fkzB
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
