port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - +.srv.nintendo.net
  - +.stun.playstation.net
  - xbox.*.microsoft.com
  - +.xboxlive.com
  - '*.msftncsi.com'
  - '*.msftconnecttest.com'
  - lens.l.google.com
  - +.qq.com
  - +.music.163.com
  - localhost
  - +.local
  - +.internal
  - '*.aliyuncs.com'
  - stun.*.*
  - stun.*.*.*
  - +.cdn.jsdelivr.net
  nameservers:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - tls://dns.rubyfish.cn:853
  - 223.5.5.5
  - 119.29.29.29
  fallback:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  - tls://1.1.1.1:853
  - tls://8.8.8.8:853
  - 1.1.1.1
  - 8.8.8.8
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 224.0.0.0/4
    - 240.0.0.0/4
proxies:
- name: SS-OFKeE
  type: ss
  server: 209.46.102.22
  port: 8388
  cipher: chacha20-ietf-poly1305
  password: 1hhrqrokj3ag
- name: SS-EPseR
  type: ss
  server: 38.180.2.141
  port: 5499
  cipher: aes-256-gcm
  password: lGqs95QkFHo2NV
- name: SS-mSxyB
  type: ss
  server: 57.128.214.100
  port: 12000
  cipher: aes-256-gcm
  password: 8JCsPssfgS8tiRwiMlhARg==
- name: SS-cFEQm
  type: ss
  server: 149.102.132.186
  port: 80
  cipher: aes-256-gcm
  password: YhzqOeJsfuZ9rkkc
- name: SS-T1nxm
  type: ss
  server: 93.174.164.89
  port: 11201
  cipher: chacha20-ietf-poly1305
  password: 0bc801a7cac5f134
- name: SS-lS4TF
  type: ss
  server: chengbai02.ascwt179.com
  port: 13223
  cipher: aes-128-gcm
  password: JVrsLLN1tkN8oXZO
- name: SS-tkHPt
  type: ss
  server: 5.181.2.76
  port: 36608
  cipher: chacha20-ietf-poly1305
  password: JOZ5Mb3nJCmmoKhd8Cc9aC
- name: SS-RPh85
  type: ss
  server: series-a1.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
- name: SS-cvRGK
  type: ss
  server: 91.107.144.0
  port: 1080
  cipher: chacha20-ietf-poly1305
  password: kDt8cG1TLg4uB0nUMOAu
- name: SS-2CB7X
  type: ss
  server: 154.53.63.42
  port: 80
  cipher: aes-256-gcm
  password: SM7WYtAwvBORXKjI
- name: SS-FVIzz
  type: ss
  server: download.riferoser.icu
  port: 56594
  cipher: chacha20-ietf-poly1305
  password: mzeMYBJYp4Bo7nA1qYLvv7QG73igtAA85nt4pr8A9ntx2qhDfYgRtiJ7iH7VrcneQKNmtvpbsvvFKPaUATYELi18iH56Ttr4
- name: SS-SDfRC
  type: ss
  server: series-a2.samanehha.co
  port: 443
  cipher: chacha20-ietf-poly1305
  password: W74XFALLLuw6m5IA
- name: SS-ZaoJc
  type: ss
  server: 203.202.232.78
  port: 60299
  cipher: chacha20-ietf-poly1305
  password: AVLbEUEtBD59FsRqcNyEib
- name: SS-MOOaQ
  type: ss
  server: 154.46.31.106
  port: 443
  cipher: chacha20-ietf-poly1305
  password: QFWzCw2uX9B9i6qAYeFBIE
- name: SS-lCsIK
  type: ss
  server: 124.217.247.205
  port: 51348
  cipher: chacha20-ietf-poly1305
  password: RZirHzSqyyb37DDIiQeDLZTJft5ZQGmUCwyA3wm5ath4j9Y3
- name: SS-8Qx7j
  type: ss
  server: 46.250.241.55
  port: 45720
  cipher: chacha20-ietf-poly1305
  password: c90d63dc7a6203af
- name: SS-deaXB
  type: ss
  server: 38.180.197.41
  port: 8080
  cipher: aes-256-gcm
  password: KixLvKzwjekG00rm
- name: SS-rYQs9
  type: ss
  server: 144.217.164.29
  port: 12000
  cipher: aes-256-gcm
  password: 8JCsPssfgS8tiRwiMlhARg==
- name: SS-ba5sZ
  type: ss
  server: 38.180.161.123
  port: 8119
  cipher: aes-256-gcm
  password: cdBIDV42DCwnfIN
- name: SS-kDaNo
  type: ss
  server: 212.192.14.226
  port: 41968
  cipher: chacha20-ietf-poly1305
  password: gC7aQv9DsENaVfKzTPDKYV
- name: SS-YuvE9
  type: ss
  server: 147.45.135.39
  port: 4205
  cipher: chacha20-ietf-poly1305
  password: c0Zy18nHmjcUfome1fYPhA
- name: SS-t4LMs
  type: ss
  server: 45.80.231.75
  port: 31019
  cipher: chacha20-ietf-poly1305
  password: XN6Xf0ZqwDeFrt39TQraen
- name: VMESS-1WPZh
  type: vmess
  server: t1.620720.xyz
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: ''
    headers:
      Host: ''
- name: VMESS-ZkWpQ
  type: vmess
  server: sy4.620720.xyz
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: sy4.620720.xyz
- name: VMESS-1bpVe
  type: vmess
  server: 8.223.63.150
  port: 443
  uuid: 462d9694-62b5-4781-a287-61a422b920e8
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /vvip
    headers:
      Host: mn1ray.jagoanvip.xyz
- name: VMESS-qHr1i
  type: vmess
  server: 2a14:7584:d0a2::a
  port: 23456
  uuid: bd48e0ac-e90e-4451-a4f2-abf061cfb890
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /alvin9999.com
    headers:
      Host: www.bing.com
- name: VMESS-1ROHy
  type: vmess
  server: 188.114.96.3
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: sy4.620720.xyz
- name: Trojan-nMHle
  type: trojan
  server: 160.16.214.104
  port: 2001
  password: f7dbed8b1ca85124e793ba6c0bcfd0db
  params: 'security: tls, sni: www.nintendogames.net'
- name: Trojan-ahjbg
  type: trojan
  server: 167.17.185.172
  port: 10889
  password: cTv.9PDdCt-wybBrG1qlxI5UJuaEj
  params: 'security: tls, sni: web.max.ru'
- name: Trojan-L3ypt
  type: trojan
  server: 220.130.58.136
  port: 35502
  password: c5355528-55a2-45df-b8fd-a48ce3c41413
  params: 'security: tls, sni: green2.cdntencentmusic.com'
- name: Trojan-8kObe
  type: trojan
  server: 194.150.166.151
  port: 52047
  password: zp630tdUuD
  params: 'security: reality, sni: aws.amazon.com, fp: chrome, pbk: 4o28aGSIz_r6Fa9sG7ZjgeT764t3bVJKmC9RDwIff38,
    sid: 1abe0c286879, spx: /, allowInsecure: 1, type: grpc'
- name: Trojan-qtMIA
  type: trojan
  server: 52.47.37.116
  port: 22222
  password: telegram-id-privatevpns
  params: 'security: tls, amp;alpn: http/1.1, amp;headerType: none, amp;type: tcp,
    amp;sni: trojan.burgerip.co.uk'
- name: Trojan-jTgXC
  type: trojan
  server: ubu.okaoclax.me
  port: 443
  password: 13c169be-8592-4eaa-94cb-69c859e7d987
  params: 'path: /trojan-ws, security: tls, host: ubu.okaoclax.me, type: ws, sni:
    ubu.okaoclax.me'
- name: Trojan-U4Enm
  type: trojan
  server: 153.121.45.139
  port: 4920
  password: f7dbed8b1ca85124e793ba6c0bcfd0db
  params: 'security: tls, sni: www.nintendogames.net'
- name: Trojan-veWcd
  type: trojan
  server: 188.116.22.217
  port: 2083
  password: 0zmdDXd0Qt5ff_7Qg67R-Rtq4Tmt4c
  params: 'path: /trojan-ws, security: tls, insecure: 0, host: xo.e0f.cx, type: ws,
    allowInsecure: 0, sni: xo.e0f.cx'
- name: Trojan-0wVEp
  type: trojan
  server: 52.195.220.53
  port: 21508
  password: BxceQaOe
  params: 'allowInsecure: 1, sni: t.me%2Fripaojiedian'
- name: Trojan-BnHHB
  type: trojan
  server: 212.193.18.144
  port: 36158
  password: ZblhWr0mqMakCPg.N
  params: 'allowInsecure: 0, sni: ya.ru'
- name: Trojan-iBZcd
  type: trojan
  server: 153.121.45.139
  port: 4674
  password: f7dbed8b1ca85124e793ba6c0bcfd0db
  params: 'security: tls, sni: www.nintendogames.net'
- name: Trojan-MPXB6
  type: trojan
  server: 16.162.45.33
  port: 17255
  password: BxceQaOe
  params: 'allowInsecure: 1, sni: t.me/ripaojiedian'
- name: Trojan-4qh1H
  type: trojan
  server: 167.17.185.152
  port: 10889
  password: cTv.9PDdCt-wybBrG1qlxI5UJuaEj
  params: 'sni: ozon.ru'
proxy-groups:
- name: ♻️ 自动选择
  type: url-test
  proxies:
  - SS-OFKeE
  - SS-EPseR
  - SS-mSxyB
  - SS-cFEQm
  - SS-T1nxm
  - SS-lS4TF
  - SS-tkHPt
  - SS-RPh85
  - SS-cvRGK
  - SS-2CB7X
  - SS-FVIzz
  - SS-SDfRC
  - SS-ZaoJc
  - SS-MOOaQ
  - SS-lCsIK
  - SS-8Qx7j
  - SS-deaXB
  - SS-rYQs9
  - SS-ba5sZ
  - SS-kDaNo
  - SS-YuvE9
  - SS-t4LMs
  - VMESS-1WPZh
  - VMESS-ZkWpQ
  - VMESS-1bpVe
  - VMESS-qHr1i
  - VMESS-1ROHy
  - Trojan-nMHle
  - Trojan-ahjbg
  - Trojan-L3ypt
  - Trojan-8kObe
  - Trojan-qtMIA
  - Trojan-jTgXC
  - Trojan-U4Enm
  - Trojan-veWcd
  - Trojan-0wVEp
  - Trojan-BnHHB
  - Trojan-iBZcd
  - Trojan-MPXB6
  - Trojan-4qh1H
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: 🌍 国外媒体
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: Ⓜ️ 微软服务
  type: select
  proxies:
  - DIRECT
  - ♻️ 自动选择
- name: 🍎 苹果服务
  type: select
  proxies:
  - DIRECT
  - ♻️ 自动选择
- name: 📲 电报信息
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎮 游戏平台
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎬 YouTube
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🎥 Netflix
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🔍 学术搜索
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
- name: 🛑 全球拦截
  type: select
  proxies:
  - REJECT
  - DIRECT
- name: 🐟 漏网之鱼
  type: select
  proxies:
  - ♻️ 自动选择
  - DIRECT
rules:
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,ip6-localhost,DIRECT
- DOMAIN-SUFFIX,ip6-loopback,DIRECT
- DOMAIN-SUFFIX,lan,DIRECT
- DOMAIN-SUFFIX,localhost,DIRECT
- DOMAIN-SUFFIX,ir,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- DOMAIN,yacd.metacubex.one,DIRECT
- DOMAIN,clash.metacubex.one,DIRECT
- DOMAIN-KEYWORD,apple,🍎 苹果服务
- DOMAIN-KEYWORD,icloud,🍎 苹果服务
- DOMAIN-SUFFIX,aaplimg.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple.co,🍎 苹果服务
- DOMAIN-SUFFIX,apple.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple-cloudkit.com,🍎 苹果服务
- DOMAIN-SUFFIX,appstore.com,🍎 苹果服务
- DOMAIN-SUFFIX,cdn-apple.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud-content.com,🍎 苹果服务
- DOMAIN-SUFFIX,me.com,🍎 苹果服务
- DOMAIN-SUFFIX,mzstatic.com,🍎 苹果服务
- DOMAIN-SUFFIX,apple.news,🍎 苹果服务
- DOMAIN-SUFFIX,apple.com.cn,🍎 苹果服务
- DOMAIN-SUFFIX,appstore.com,🍎 苹果服务
- DOMAIN-SUFFIX,icloud.com.cn,🍎 苹果服务
- DOMAIN-KEYWORD,microsoft,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoft.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msecnd.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msedge.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,office.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,office.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,outlook.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,visualstudio.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windows.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windows.net,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,windowsupdate.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,xbox.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,xboxlive.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,msn.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoftonline.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,microsoft365.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,skype.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,live.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,bing.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,hotmail.com,Ⓜ️ 微软服务
- DOMAIN-SUFFIX,azureedge.net,Ⓜ️ 微软服务
- DOMAIN-KEYWORD,admarvel,🛑 全球拦截
- DOMAIN-KEYWORD,admaster,🛑 全球拦截
- DOMAIN-KEYWORD,adsage,🛑 全球拦截
- DOMAIN-KEYWORD,adsmogo,🛑 全球拦截
- DOMAIN-KEYWORD,adsrvmedia,🛑 全球拦截
- DOMAIN-KEYWORD,adwords,🛑 全球拦截
- DOMAIN-KEYWORD,analytics,🛑 全球拦截
- DOMAIN-KEYWORD,duomeng,🛑 全球拦截
- DOMAIN-KEYWORD,dwtrack,🛑 全球拦截
- DOMAIN-KEYWORD,guanggao,🛑 全球拦截
- DOMAIN-KEYWORD,lianmeng,🛑 全球拦截
- DOMAIN-KEYWORD,mopub,🛑 全球拦截
- DOMAIN-KEYWORD,omgmta,🛑 全球拦截
- DOMAIN-KEYWORD,openx,🛑 全球拦截
- DOMAIN-KEYWORD,partnerad,🛑 全球拦截
- DOMAIN-KEYWORD,pingfore,🛑 全球拦截
- DOMAIN-KEYWORD,supersonicads,🛑 全球拦截
- DOMAIN-KEYWORD,tracking,🛑 全球拦截
- DOMAIN-KEYWORD,uedas,🛑 全球拦截
- DOMAIN-KEYWORD,umeng,🛑 全球拦截
- DOMAIN-KEYWORD,usage,🛑 全球拦截
- DOMAIN-KEYWORD,wlmonitor,🛑 全球拦截
- DOMAIN-KEYWORD,zjtoolbar,🛑 全球拦截
- DOMAIN-SUFFIX,adjust.com,🛑 全球拦截
- DOMAIN-SUFFIX,ad.gt,🛑 全球拦截
- DOMAIN-SUFFIX,adcolony.com,🛑 全球拦截
- DOMAIN-SUFFIX,adform.net,🛑 全球拦截
- DOMAIN-SUFFIX,admob.com,🛑 全球拦截
- DOMAIN-SUFFIX,adnxs.com,🛑 全球拦截
- DOMAIN-SUFFIX,ads-twitter.com,🛑 全球拦截
- DOMAIN-SUFFIX,adsafeprotected.com,🛑 全球拦截
- DOMAIN-SUFFIX,adsrvr.org,🛑 全球拦截
- DOMAIN-SUFFIX,appsflyer.com,🛑 全球拦截
- DOMAIN-SUFFIX,doubleclick.net,🛑 全球拦截
- DOMAIN-SUFFIX,googleadservices.com,🛑 全球拦截
- DOMAIN-SUFFIX,googleadsserving.cn,🛑 全球拦截
- DOMAIN-SUFFIX,googlesyndication.com,🛑 全球拦截
- DOMAIN-SUFFIX,googletagmanager.com,🛑 全球拦截
- DOMAIN-SUFFIX,googletagservices.com,🛑 全球拦截
- DOMAIN-SUFFIX,mopub.com,🛑 全球拦截
- DOMAIN-SUFFIX,telegra.ph,📲 电报信息
- DOMAIN-SUFFIX,telegram.org,📲 电报信息
- DOMAIN-SUFFIX,telegram.me,📲 电报信息
- DOMAIN-SUFFIX,telesco.pe,📲 电报信息
- DOMAIN-SUFFIX,t.me,📲 电报信息
- DOMAIN-SUFFIX,tdesktop.com,📲 电报信息
- DOMAIN-SUFFIX,telegramdownload.com,📲 电报信息
- IP-CIDR,91.108.4.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.8.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.12.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.16.0/22,📲 电报信息,no-resolve
- IP-CIDR,91.108.56.0/22,📲 电报信息,no-resolve
- IP-CIDR,149.154.160.0/20,📲 电报信息,no-resolve
- IP-CIDR,2001:b28:f23d::/48,📲 电报信息,no-resolve
- IP-CIDR,2001:b28:f23f::/48,📲 电报信息,no-resolve
- IP-CIDR,2001:67c:4e8::/48,📲 电报信息,no-resolve
- DOMAIN-SUFFIX,steamcontent.com,🎮 游戏平台
- DOMAIN-SUFFIX,steampowered.com,🎮 游戏平台
- DOMAIN-SUFFIX,steamstatic.com,🎮 游戏平台
- DOMAIN-SUFFIX,steamcommunity.com,🎮 游戏平台
- DOMAIN-SUFFIX,valvesoftware.com,🎮 游戏平台
- DOMAIN-SUFFIX,steam-chat.com,🎮 游戏平台
- DOMAIN-SUFFIX,epicgames.com,🎮 游戏平台
- DOMAIN-SUFFIX,epicgames.dev,🎮 游戏平台
- DOMAIN-SUFFIX,unrealengine.com,🎮 游戏平台
- DOMAIN-SUFFIX,playstation.com,🎮 游戏平台
- DOMAIN-SUFFIX,playstation.net,🎮 游戏平台
- DOMAIN-SUFFIX,playstationnetwork.com,🎮 游戏平台
- DOMAIN-SUFFIX,sony.com,🎮 游戏平台
- DOMAIN-SUFFIX,xbox.com,🎮 游戏平台
- DOMAIN-SUFFIX,xboxlive.com,🎮 游戏平台
- DOMAIN-SUFFIX,nintendo.com,🎮 游戏平台
- DOMAIN-SUFFIX,nintendo.net,🎮 游戏平台
- DOMAIN-SUFFIX,ea.com,🎮 游戏平台
- DOMAIN-SUFFIX,origin.com,🎮 游戏平台
- DOMAIN-SUFFIX,ubisoft.com,🎮 游戏平台
- DOMAIN-SUFFIX,ubi.com,🎮 游戏平台
- DOMAIN-SUFFIX,battle.net,🎮 游戏平台
- DOMAIN-SUFFIX,blizzard.com,🎮 游戏平台
- DOMAIN-SUFFIX,youtube.com,🎬 YouTube
- DOMAIN-SUFFIX,ytimg.com,🎬 YouTube
- DOMAIN-SUFFIX,googlevideo.com,🎬 YouTube
- DOMAIN-SUFFIX,youtu.be,🎬 YouTube
- DOMAIN-SUFFIX,yt.be,🎬 YouTube
- DOMAIN-SUFFIX,youtube-nocookie.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubeeducation.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubegaming.com,🎬 YouTube
- DOMAIN-SUFFIX,youtubekids.com,🎬 YouTube
- DOMAIN-SUFFIX,netflix.com,🎥 Netflix
- DOMAIN-SUFFIX,netflix.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxext.com,🎥 Netflix
- DOMAIN-SUFFIX,nflximg.com,🎥 Netflix
- DOMAIN-SUFFIX,nflximg.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxso.net,🎥 Netflix
- DOMAIN-SUFFIX,nflxvideo.net,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest0.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest1.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest2.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest3.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest4.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest5.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest6.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest7.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest8.com,🎥 Netflix
- DOMAIN-SUFFIX,netflixdnstest9.com,🎥 Netflix
- DOMAIN-SUFFIX,scholar.google.com,🔍 学术搜索
- DOMAIN-SUFFIX,scholar.googleusercontent.com,🔍 学术搜索
- DOMAIN-SUFFIX,scholarcdn.net,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.tw,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.st,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.se,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.ren,🔍 学术搜索
- DOMAIN-SUFFIX,sci-hub.ru,🔍 学术搜索
- DOMAIN-SUFFIX,researchgate.net,🔍 学术搜索
- DOMAIN-SUFFIX,springer.com,🔍 学术搜索
- DOMAIN-SUFFIX,sciencedirect.com,🔍 学术搜索
- DOMAIN-SUFFIX,acm.org,🔍 学术搜索
- DOMAIN-SUFFIX,ieee.org,🔍 学术搜索
- DOMAIN-SUFFIX,nature.com,🔍 学术搜索
- DOMAIN-SUFFIX,jstor.org,🔍 学术搜索
- DOMAIN-SUFFIX,9cache.com,🌍 国外媒体
- DOMAIN-SUFFIX,9gag.com,🌍 国外媒体
- DOMAIN-SUFFIX,abc.com,🌍 国外媒体
- DOMAIN-SUFFIX,bbc.co.uk,🌍 国外媒体
- DOMAIN-SUFFIX,bbc.com,🌍 国外媒体
- DOMAIN-SUFFIX,cnn.com,🌍 国外媒体
- DOMAIN-SUFFIX,deezer.com,🌍 国外媒体
- DOMAIN-SUFFIX,discord.com,🌍 国外媒体
- DOMAIN-SUFFIX,dropbox.com,🌍 国外媒体
- DOMAIN-SUFFIX,facebook.com,🌍 国外媒体
- DOMAIN-SUFFIX,fb.com,🌍 国外媒体
- DOMAIN-SUFFIX,fbcdn.net,🌍 国外媒体
- DOMAIN-SUFFIX,github.com,🌍 国外媒体
- DOMAIN-SUFFIX,github.io,🌍 国外媒体
- DOMAIN-SUFFIX,githubusercontent.com,🌍 国外媒体
- DOMAIN-SUFFIX,instagram.com,🌍 国外媒体
- DOMAIN-SUFFIX,pinterest.com,🌍 国外媒体
- DOMAIN-SUFFIX,reddit.com,🌍 国外媒体
- DOMAIN-SUFFIX,redditmedia.com,🌍 国外媒体
- DOMAIN-SUFFIX,redditstatic.com,🌍 国外媒体
- DOMAIN-SUFFIX,spotify.com,🌍 国外媒体
- DOMAIN-SUFFIX,tiktok.com,🌍 国外媒体
- DOMAIN-SUFFIX,ttvnw.net,🌍 国外媒体
- DOMAIN-SUFFIX,twitch.tv,🌍 国外媒体
- DOMAIN-SUFFIX,twitter.com,🌍 国外媒体
- DOMAIN-SUFFIX,x.com,🌍 国外媒体
- DOMAIN-SUFFIX,t.co,🌍 国外媒体
- DOMAIN-SUFFIX,medium.com,🌍 国外媒体
- DOMAIN-SUFFIX,flickr.com,🌍 国外媒体
- DOMAIN-SUFFIX,imgur.com,🌍 国外媒体
- DOMAIN-SUFFIX,soundcloud.com,🌍 国外媒体
- DOMAIN-SUFFIX,vimeo.com,🌍 国外媒体
- DOMAIN-SUFFIX,tumblr.com,🌍 国外媒体
- DOMAIN-SUFFIX,quora.com,🌍 国外媒体
- DOMAIN-SUFFIX,reuters.com,🌍 国外媒体
- DOMAIN-SUFFIX,nytimes.com,🌍 国外媒体
- DOMAIN-SUFFIX,wsj.com,🌍 国外媒体
- DOMAIN-SUFFIX,ft.com,🌍 国外媒体
- DOMAIN-SUFFIX,theguardian.com,🌍 国外媒体
- DOMAIN-SUFFIX,apnews.com,🌍 国外媒体
- DOMAIN-SUFFIX,bloomberg.com,🌍 国外媒体
- DOMAIN-SUFFIX,googlevideo.com,🌍 国外媒体
- DOMAIN-SUFFIX,googleapis.com,🌍 国外媒体
- DOMAIN-SUFFIX,gstatic.com,🌍 国外媒体
- DOMAIN-SUFFIX,google.com,🌍 国外媒体
- DOMAIN-SUFFIX,cn,DIRECT
- DOMAIN-SUFFIX,126.com,DIRECT
- DOMAIN-SUFFIX,126.net,DIRECT
- DOMAIN-SUFFIX,127.net,DIRECT
- DOMAIN-SUFFIX,163.com,DIRECT
- DOMAIN-SUFFIX,360buyimg.com,DIRECT
- DOMAIN-SUFFIX,36kr.com,DIRECT
- DOMAIN-SUFFIX,alipay.com,DIRECT
- DOMAIN-SUFFIX,aliyun.com,DIRECT
- DOMAIN-SUFFIX,alicdn.com,DIRECT
- DOMAIN-SUFFIX,amap.com,DIRECT
- DOMAIN-SUFFIX,baidu.com,DIRECT
- DOMAIN-SUFFIX,bdimg.com,DIRECT
- DOMAIN-SUFFIX,bdstatic.com,DIRECT
- DOMAIN-SUFFIX,bilibili.com,DIRECT
- DOMAIN-SUFFIX,bilivideo.com,DIRECT
- DOMAIN-SUFFIX,caiyunapp.com,DIRECT
- DOMAIN-SUFFIX,csdn.net,DIRECT
- DOMAIN-SUFFIX,ctrip.com,DIRECT
- DOMAIN-SUFFIX,didi.com,DIRECT
- DOMAIN-SUFFIX,douban.com,DIRECT
- DOMAIN-SUFFIX,doubanio.com,DIRECT
- DOMAIN-SUFFIX,douyin.com,DIRECT
- DOMAIN-SUFFIX,jd.com,DIRECT
- DOMAIN-SUFFIX,mi.com,DIRECT
- DOMAIN-SUFFIX,meituan.com,DIRECT
- DOMAIN-SUFFIX,meituan.net,DIRECT
- DOMAIN-SUFFIX,netease.com,DIRECT
- DOMAIN-SUFFIX,oschina.net,DIRECT
- DOMAIN-SUFFIX,qq.com,DIRECT
- DOMAIN-SUFFIX,qqmail.com,DIRECT
- DOMAIN-SUFFIX,sina.com,DIRECT
- DOMAIN-SUFFIX,sinaimg.com,DIRECT
- DOMAIN-SUFFIX,taobao.com,DIRECT
- DOMAIN-SUFFIX,tencent.com,DIRECT
- DOMAIN-SUFFIX,tmall.com,DIRECT
- DOMAIN-SUFFIX,weibo.com,DIRECT
- DOMAIN-SUFFIX,wechat.com,DIRECT
- DOMAIN-SUFFIX,weixin.com,DIRECT
- DOMAIN-SUFFIX,zhihu.com,DIRECT
- DOMAIN-SUFFIX,zhimg.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.com,DIRECT
- DOMAIN-SUFFIX,dingtalk.net,DIRECT
- DOMAIN-SUFFIX,iqiyi.com,DIRECT
- DOMAIN-SUFFIX,iqiyipic.com,DIRECT
- DOMAIN-SUFFIX,acfun.cn,DIRECT
- DOMAIN-SUFFIX,aixifan.com,DIRECT
- DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
- DOMAIN-SUFFIX,xhscdn.com,DIRECT
- DOMAIN-SUFFIX,xiaomi.com,DIRECT
- DOMAIN-SUFFIX,xiaomiyoupin.com,DIRECT
- DOMAIN-SUFFIX,huawei.com,DIRECT
- DOMAIN-SUFFIX,hicloud.com,DIRECT
- DOMAIN-SUFFIX,vmall.com,DIRECT
- DOMAIN-SUFFIX,vivo.com,DIRECT
- DOMAIN-SUFFIX,oppo.com,DIRECT
- DOMAIN-SUFFIX,heytap.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,🐟 漏网之鱼
