port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-T9ekw
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SS-TJ3JC
  type: ss
  server: 45.128.151.67
  port: 31348
  cipher: chacha20-ietf-poly1305
  password: d3TphPPfMkIxFmPJpA0j7RkPJHjeHqaJk2D7Co7VsFuUU2v1
- name: SSR-MRm0f
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-7HBt8
  type: vmess
  server: 195.154.40.247
  port: 38952
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-uRxK0
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-sRHr2
  type: vmess
  server: v18.nmcf.me
  port: 8000
  uuid: d26fc1a3-0d97-416b-abcd-b335b4bf7881
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /nmkj
    headers:
      Host: www.bing.com
- name: VMESS-7gXrk
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-ECeTU
  type: vmess
  server: 104.21.96.1
  port: 2096
  uuid: b3928f8d-ea81-4d75-bcec-4016a072adff
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: de01.sh-cloudflare.sbs
- name: VMESS-15qXq
  type: vmess
  server: 120.232.153.41
  port: 46597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-nAv5h
  type: vmess
  server: 120.198.71.216
  port: 52082
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-buwc9
  type: vmess
  server: 120.198.71.216
  port: 35921
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-WFxXX
  type: vmess
  server: 58.246.138.244
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-511Xd
  type: vmess
  server: 183.238.90.8
  port: 41766
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-KjSXr
  type: vmess
  server: cs.flha.ru
  port: 2082
  uuid: 2f821152-c3e9-4074-9185-2790e7425f42
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cs.flha.ru
- name: VMESS-IwH40
  type: vmess
  server: de01.sh-cloudflare.sbs
  port: 2096
  uuid: b3928f8d-ea81-4d75-bcec-4016a072adff
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: de01.sh-cloudflare.sbs
- name: VMESS-hlIs5
  type: vmess
  server: 120.198.71.214
  port: 32980
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-fECo9
  type: vmess
  server: cloudgetservice.mcloudservice.site
  port: 443
  uuid: ad2bca4d-be9e-4ac2-b2ed-4c81abb4242f
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: mAxNEtVip-uSA-Vp4.nETKh3.sItE
- name: VMESS-MFpkV
  type: vmess
  server: 183.238.90.8
  port: 46920
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: Trojan-jO7Cx
  type: trojan
  server: 104.21.96.1
  port: 443
  password: 84831b86-5c76-4173-bdf1-02fa3ed78a32
  params: 'security: tls, sni: eeERrrR.999815.xYZ, type: ws, host: eeerrrr.999815.xyz,
    path: /eS3prPmcpzbScA5VUAi1psm38Tz, fp: chrome, alpn: http/1.1'
- name: Trojan-w9Hky
  type: trojan
  server: 172.67.181.193
  port: 443
  password: c8eac4b7-95ba-4ce0-920d-c3279eb3b391
  params: 'security: tls, sni: EEeEee4.hUAngSHANG2030.dPdNS.org, type: ws, host: EEeEee4.hUAngSHANG2030.dPdNS.org,
    path: /ptGwaGzcA4KNAXX'
- name: Trojan-vf4hL
  type: trojan
  server: 104.21.22.211
  port: 443
  password: 061ec9d5-ba40-428a-8be0-1947b10b5cfc
  params: 'security: tls, type: ws, sni: T.taipEi108.Dpdns.Org, path: /Dmby2AKiZKvMo1YauoQwY5,
    host: t.taipei108.dpdns.org'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-T9ekw
  - SS-TJ3JC
  - SSR-MRm0f
  - VMESS-7HBt8
  - VMESS-uRxK0
  - VMESS-sRHr2
  - VMESS-7gXrk
  - VMESS-ECeTU
  - VMESS-15qXq
  - VMESS-nAv5h
  - VMESS-buwc9
  - VMESS-WFxXX
  - VMESS-511Xd
  - VMESS-KjSXr
  - VMESS-IwH40
  - VMESS-hlIs5
  - VMESS-fECo9
  - VMESS-MFpkV
  - Trojan-jO7Cx
  - Trojan-w9Hky
  - Trojan-vf4hL
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-T9ekw
  - SS-TJ3JC
  - SSR-MRm0f
  - VMESS-7HBt8
  - VMESS-uRxK0
  - VMESS-sRHr2
  - VMESS-7gXrk
  - VMESS-ECeTU
  - VMESS-15qXq
  - VMESS-nAv5h
  - VMESS-buwc9
  - VMESS-WFxXX
  - VMESS-511Xd
  - VMESS-KjSXr
  - VMESS-IwH40
  - VMESS-hlIs5
  - VMESS-fECo9
  - VMESS-MFpkV
  - Trojan-jO7Cx
  - Trojan-w9Hky
  - Trojan-vf4hL
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
