port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-FLyZi
  type: ss
  server: 195.154.32.37
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-LFP6a
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-64PI2
  type: vmess
  server: 195.154.40.247
  port: 31549
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-cWEhW
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-1C94U
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: SS-rCyT0
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-EYfGl
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-ATKFt
  type: ss
  server: 43.226.17.17
  port: 14312
  cipher: chacha20-ietf-poly1305
  password: 2e96aa2f3054
- name: SS-5sosH
  type: ss
  server: hkkh11v1.xpmc.cc
  port: 20273
  cipher: chacha20-ietf-poly1305
  password: 91a41f4e02dc
- name: SS-BDLHC
  type: ss
  server: 34.212.26.32
  port: 443
  cipher: aes-256-cfb
  password: awsps0501
- name: SS-gQAWG
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 15007
  cipher: aes-256-gcm
  password: Q5XH89ZLTSGOQASZ
- name: SS-pD0o2
  type: ss
  server: 52.195.15.105
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-mkYtw
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-T4vxR
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18010
  cipher: aes-256-gcm
  password: TF63RS7M0DB9OJ3B
- name: SS-jWFf9
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-oFaRq
  type: ss
  server: 3.38.139.172
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-D9qkS
  type: ss
  server: 125.141.26.12
  port: 4857
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: VMESS-psCSf
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-BSURp
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-EYCNe
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-8u84D
  type: vmess
  server: 8.211.154.107
  port: 50951
  uuid: a3d04548-625c-4658-9ff0-f9a7835d1f6d
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-6ErH9
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-zqtkU
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-q9nr3
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-KiSO0
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-i5JGH
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-yyyhb
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-dqiZe
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-BcqN2
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-6U3pQ
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-oCrqU
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-sHs3h
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: Trojan-BLJsB
  type: trojan
  server: 192.3.127.231
  port: 443
  password: Aimer
  params: 'allowInsecure: 0, sni: epmw.ambercc.filegear-sg.me, type: ws, host: epmw.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-WGYUk
  type: trojan
  server: 108.165.152.58
  port: 2087
  password: Aimer
  params: 'allowInsecure: 0, sni: epmw.ambercc.filegear-sg.me, type: ws, host: epmw.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-jn76m
  type: trojan
  server: usla.mjt000.com
  port: 443
  password: e4af2638-bb12-4e4a-84f1-a032e23ca63f
  params: 'allowInsecure: 0, sni: usla.mjt000.com'
- name: Trojan-lp4J3
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: Trojan-iZgzR
  type: trojan
  server: handles.homeofbrave.net
  port: 28332
  password: CYjXlaFOAyEDZaTe0gZaCOCyy4RwSyKYDq9SSpDCxzF33eA3SS06O28aj65a3lY3znO88
  params: 'allowInsecure: 0'
- name: Trojan-wvhxF
  type: trojan
  server: huzzah.meijireform.com
  port: 28331
  password: Aa4cexaO3FReREXgAlp9CjyTjpaRNan3YDx6DxaDYFS3On0SqgF08CZcBpYxy3awXeEIC
  params: 'allowInsecure: 0'
- name: Trojan-s8Ih5
  type: trojan
  server: cutlery.homeofbrave.net
  port: 28331
  password: e3qTaj4gOeDDzR8lzYXpyZDpga5a3SCwyE4CO6c738aZxwlaaAD0SYSYyXOlF9S3FRF0x
  params: 'allowInsecure: 0'
- name: Trojan-RpyqY
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: Trojan-4kFNz
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-IrdeT
  type: trojan
  server: luber.protocolbuffer.com
  port: 18333
  password: 4a3paxFKgSCxXBlaZn73Suc6AF3Dj3078l8FeDzDOXZOwyCDCICzeApyySAEgeTOSEZSZ
  params: 'allowInsecure: 0, sni: luber.protocolbuffer.com'
- name: Trojan-blz6h
  type: trojan
  server: 192.210.207.89
  port: 20080
  password: Aimer
  params: 'allowInsecure: 0, sni: epme.ambercc.filegear-sg.me, type: ws, host: epme.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-ZlD9O
  type: trojan
  server: huzzah.meijireform.com
  port: 28331
  password: Aa4cexaO3FReREXgAlp9CjyTjpaRNan3YDx6DxaDYFS3On0SqgF08CZcBpYxy3awXeEIC
  params: 'allowInsecure: 0, sni: huzzah.meijireform.com'
- name: Trojan-scj4b
  type: trojan
  server: 216.24.57.30
  port: 443
  password: tg-fq521free
  params: 'allowInsecure: 0, sni: torjan.xn--xhq44j.eu.org, type: ws, host: torjan.xn--xhq44j.eu.org,
    path: /'
- name: Trojan-m6V8Z
  type: trojan
  server: cutlery.homeofbrave.net
  port: 28331
  password: e3qTaj4gOeDDzR8lzYXpyZDpga5a3SCwyE4CO6c738aZxwlaaAD0SYSYyXOlF9S3FRF0x
  params: 'allowInsecure: 0, sni: cutlery.homeofbrave.net'
- name: Trojan-jPONe
  type: trojan
  server: 141.11.203.191
  port: 8443
  password: Aimer
  params: 'allowInsecure: 0, sni: epmw.ambercc.filegear-sg.me, type: ws, host: epmw.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-QnYd2
  type: trojan
  server: closet.homeofbrave.net
  port: 18332
  password: BIRCauz5R2S8O3pZ56eg8yC43yla4T3D7znxCDFxSCODO9jA3NxAcaE3YYK3Sq8u9DxZg
  params: 'allowInsecure: 0'
- name: Trojan-QKTzy
  type: trojan
  server: fireplace.wireshop.net
  port: 28331
  password: Ye8uA37l3C9FwpCwBCuZBy4SqlKTapDXEDnCZFRKSNlZCRSy0I3Yc8DxayzOeO3xaxjjg
  params: 'allowInsecure: 0'
- name: SS-6sokx
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
- name: SS-9jELr
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: SS-zU1A9
  type: ss
  server: 139.162.106.142
  port: 11359
  cipher: aes-256-gcm
  password: tVPVlUgQhj9i7vHOHij3daCJEUZxctEQ9xoj0WT5A8w=
- name: SS-TlKZQ
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: VMESS-UxL62
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 2ff97c6d-8557-42a4-b43f-19c77c5959ea
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: irsoft.sytes.net
- name: VMESS-hqQzy
  type: vmess
  server: 120.198.71.219
  port: 51095
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-YaCh1
  type: vmess
  server: 43b5a616-sw04g0-swasv3-luwe.hgc1.tcpbbr.net
  port: 8080
  uuid: a2b0fd2b-716f-0df8-d4e2-03a1c00e5f1a
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-caFE3
  type: vmess
  server: 183.236.51.38
  port: 49302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-tNjx6
  type: vmess
  server: 1deb35dd-svn5s0-t1j1pq-sett.hgc1.tcpbbr.net
  port: 8080
  uuid: 303436ce-f8c5-11ef-8400-f23c9164ca5d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-8eXtn
  type: vmess
  server: 120.232.153.63
  port: 37805
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-n1AL8
  type: vmess
  server: 77becdb4-sw7j40-t94bdb-mrtr.hgc1.tcpbbr.net
  port: 8080
  uuid: 28a8a4d0-3e02-11eb-a8bf-f23c91cfbbc9
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-OZRAI
  type: vmess
  server: d98cad7b-swkhs0-swwn15-1phla.hgc1.tcpbbr.net
  port: 8080
  uuid: 467f2940-77cd-11ee-b5ed-f23c9164ca5d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-UsgEh
  type: vmess
  server: 120.232.153.40
  port: 31209
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-NUaMd
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-YScuF
  type: vmess
  server: xxxsde4.freevpnatm2025.dpdns.org
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: xxxsde4.freevpnatm2025.dpdns.org
- name: VMESS-vsJ3L
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-rV57a
  type: vmess
  server: 183.236.51.38
  port: 59652
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: Trojan-paWxu
  type: trojan
  server: 36.151.251.60
  port: 28296
  password: RlzoEILU
  params: 'allowInsecure: 0, sni: cdn.egvra.cn'
- name: Trojan-rzELT
  type: trojan
  server: 216.24.57.30
  port: 443
  password: tg-fq521free
  params: 'allowInsecure: 0, sni: torjan.xn--xhq44j.eu.org, type: ws, host: torjan.xn--xhq44j.eu.org,
    path: /'
- name: Trojan-2Cyzm
  type: trojan
  server: cutlery.homeofbrave.net
  port: 28331
  password: e3qTaj4gOeDDzR8lzYXpyZDpga5a3SCwyE4CO6c738aZxwlaaAD0SYSYyXOlF9S3FRF0x
  params: 'allowInsecure: 0'
- name: Trojan-ipYkV
  type: trojan
  server: 104.21.78.243
  port: 443
  password: 3d4ad187-b554-4300-bf71-d26c71962504
  params: 'sni: FFfgtyy.7282728.XYZ, allowInsecure: 1, type: ws, path: /WaHA3RC540rQ8PWqRcOEICAwmfH7,
    host: FFfgtyy.7282728.XYZ, fp: chrome'
- name: Trojan-PAd3l
  type: trojan
  server: 154.17.22.75
  port: 28331
  password: e3qTaj4gOeDDzR8lzYXpyZDpga5a3SCwyE4CO6c738aZxwlaaAD0SYSYyXOlF9S3FRF0x
  params: 'sni: cutlery.homeofbrave.net'
- name: Trojan-G8gnN
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 0, sni: 36.151.251.61'
- name: Trojan-ZsG3U
  type: trojan
  server: valance.protocolbuffer.com
  port: 443
  password: 3wFeD7FC8CRgIa6KaRDX8O9S3Zpn32aCl7ABZY3u5SlCpSTjqE6D3F8eRyxgSn34aO93p
  params: ''
- name: Trojan-Gwp92
  type: trojan
  server: compost.meijireform.com
  port: 18332
  password: 3DZwNDRFSa7ZYpYRx2lAZzR4SCncORY7ESYAXyFpaexDA98eljCw6xyCOa534TlCD0xKD
  params: ''
- name: Trojan-ecJHc
  type: trojan
  server: diagram.protocolbuffer.com
  port: 18334
  password: YaN8FFNe58nga3xAu3yTx0CSllcSeOnDZOj3SXROCz3S34B9D3F7Ka0aYa8yaxpXCDRKZ
  params: ''
- name: Trojan-yn3O6
  type: trojan
  server: kz.mjt000.com
  port: 443
  password: ea17601d-8ebf-4431-b815-4d644821ca7e
  params: 'sni: kz.mjt000.com'
- name: Trojan-TBjPm
  type: trojan
  server: 192.210.207.89
  port: 20080
  password: Aimer
  params: 'allowInsecure: 0, sni: epme.ambercc.filegear-sg.me, type: ws, host: epme.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-UTjYb
  type: trojan
  server: mailbox.meijireform.com
  port: 28332
  password: FNCEZ4Z336SlI8TRlyx3Y3SljwaxFexDNRxzya4R82DEOOCYR25eOSBq0K0ez9ZnaX9D3
  params: ''
- name: Trojan-B6hwv
  type: trojan
  server: 108.165.152.58
  port: 2087
  password: Aimer
  params: 'allowInsecure: 0, sni: epmw.ambercc.filegear-sg.me, type: ws, host: epmw.ambercc.filegear-sg.me,
    path: /?ed=2560'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-FLyZi
  - SSR-LFP6a
  - VMESS-64PI2
  - SS-cWEhW
  - SS-1C94U
  - SS-rCyT0
  - SS-EYfGl
  - SS-ATKFt
  - SS-5sosH
  - SS-BDLHC
  - SS-gQAWG
  - SS-pD0o2
  - SS-mkYtw
  - SS-T4vxR
  - SS-jWFf9
  - SS-oFaRq
  - SS-D9qkS
  - VMESS-psCSf
  - VMESS-BSURp
  - VMESS-EYCNe
  - VMESS-8u84D
  - VMESS-6ErH9
  - VMESS-zqtkU
  - VMESS-q9nr3
  - VMESS-KiSO0
  - VMESS-i5JGH
  - VMESS-yyyhb
  - VMESS-dqiZe
  - VMESS-BcqN2
  - VMESS-6U3pQ
  - VMESS-oCrqU
  - VMESS-sHs3h
  - Trojan-BLJsB
  - Trojan-WGYUk
  - Trojan-jn76m
  - Trojan-lp4J3
  - Trojan-iZgzR
  - Trojan-wvhxF
  - Trojan-s8Ih5
  - Trojan-RpyqY
  - Trojan-4kFNz
  - Trojan-IrdeT
  - Trojan-blz6h
  - Trojan-ZlD9O
  - Trojan-scj4b
  - Trojan-m6V8Z
  - Trojan-jPONe
  - Trojan-QnYd2
  - Trojan-QKTzy
  - SS-6sokx
  - SS-9jELr
  - SS-zU1A9
  - SS-TlKZQ
  - VMESS-UxL62
  - VMESS-hqQzy
  - VMESS-YaCh1
  - VMESS-caFE3
  - VMESS-tNjx6
  - VMESS-8eXtn
  - VMESS-n1AL8
  - VMESS-OZRAI
  - VMESS-UsgEh
  - VMESS-NUaMd
  - VMESS-YScuF
  - VMESS-vsJ3L
  - VMESS-rV57a
  - Trojan-paWxu
  - Trojan-rzELT
  - Trojan-2Cyzm
  - Trojan-ipYkV
  - Trojan-PAd3l
  - Trojan-G8gnN
  - Trojan-ZsG3U
  - Trojan-Gwp92
  - Trojan-ecJHc
  - Trojan-yn3O6
  - Trojan-TBjPm
  - Trojan-UTjYb
  - Trojan-B6hwv
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-FLyZi
  - SSR-LFP6a
  - VMESS-64PI2
  - SS-cWEhW
  - SS-1C94U
  - SS-rCyT0
  - SS-EYfGl
  - SS-ATKFt
  - SS-5sosH
  - SS-BDLHC
  - SS-gQAWG
  - SS-pD0o2
  - SS-mkYtw
  - SS-T4vxR
  - SS-jWFf9
  - SS-oFaRq
  - SS-D9qkS
  - VMESS-psCSf
  - VMESS-BSURp
  - VMESS-EYCNe
  - VMESS-8u84D
  - VMESS-6ErH9
  - VMESS-zqtkU
  - VMESS-q9nr3
  - VMESS-KiSO0
  - VMESS-i5JGH
  - VMESS-yyyhb
  - VMESS-dqiZe
  - VMESS-BcqN2
  - VMESS-6U3pQ
  - VMESS-oCrqU
  - VMESS-sHs3h
  - Trojan-BLJsB
  - Trojan-WGYUk
  - Trojan-jn76m
  - Trojan-lp4J3
  - Trojan-iZgzR
  - Trojan-wvhxF
  - Trojan-s8Ih5
  - Trojan-RpyqY
  - Trojan-4kFNz
  - Trojan-IrdeT
  - Trojan-blz6h
  - Trojan-ZlD9O
  - Trojan-scj4b
  - Trojan-m6V8Z
  - Trojan-jPONe
  - Trojan-QnYd2
  - Trojan-QKTzy
  - SS-6sokx
  - SS-9jELr
  - SS-zU1A9
  - SS-TlKZQ
  - VMESS-UxL62
  - VMESS-hqQzy
  - VMESS-YaCh1
  - VMESS-caFE3
  - VMESS-tNjx6
  - VMESS-8eXtn
  - VMESS-n1AL8
  - VMESS-OZRAI
  - VMESS-UsgEh
  - VMESS-NUaMd
  - VMESS-YScuF
  - VMESS-vsJ3L
  - VMESS-rV57a
  - Trojan-paWxu
  - Trojan-rzELT
  - Trojan-2Cyzm
  - Trojan-ipYkV
  - Trojan-PAd3l
  - Trojan-G8gnN
  - Trojan-ZsG3U
  - Trojan-Gwp92
  - Trojan-ecJHc
  - Trojan-yn3O6
  - Trojan-TBjPm
  - Trojan-UTjYb
  - Trojan-B6hwv
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
