port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-p413G
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SS-drK1I
  type: ss
  server: 45.128.151.67
  port: 31348
  cipher: chacha20-ietf-poly1305
  password: d3TphPPfMkIxFmPJpA0j7RkPJHjeHqaJk2D7Co7VsFuUU2v1
- name: SSR-ixZ6X
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-jBKR4
  type: vmess
  server: 195.154.40.247
  port: 38952
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-Ltnbi
  type: vmess
  server: us01.sh-cloudflare.sbs
  port: 8443
  uuid: 2bd0c9d7-f239-437e-a1e1-6cf830af2a1a
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us01.sh-cloudflare.sbs
- name: VMESS-LObSq
  type: vmess
  server: 172.67.170.51
  port: 80
  uuid: ced307a2-af2c-4113-bebc-fb888c702b7d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /PEQ7CoA1VrBwsbnEcmJLxC
    headers:
      Host: m4frt.999182.xyz
- name: VMESS-kJsFA
  type: vmess
  server: 120.198.71.216
  port: 46759
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-ofItm
  type: vmess
  server: 120.232.153.123
  port: 40392
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-FBLbv
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-KXA5J
  type: vmess
  server: 104.21.64.1
  port: 2087
  uuid: 1c36906e-1a21-4330-b04f-85baf1a6ff26
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: rak1d3.777269.xyz
- name: VMESS-g4O65
  type: vmess
  server: 104.21.112.1
  port: 2053
  uuid: 996016f7-da89-45f1-b3b4-555bc799ed86
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: rak2d1.777269.xyz
- name: VMESS-rsPnN
  type: vmess
  server: 3fbc10.2ca52629-3a60.shop
  port: 80
  uuid: 5be76fa5-3758-4282-bb54-b1efabd6ba3d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk02s.2ca52629-3a60.shop
- name: VMESS-7w1oW
  type: vmess
  server: 120.198.71.219
  port: 51095
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-B5Bj7
  type: vmess
  server: 104.21.112.1
  port: 2087
  uuid: 1c36906e-1a21-4330-b04f-85baf1a6ff26
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: rak1d3.777269.xyz
- name: VMESS-U1hjW
  type: vmess
  server: 104.17.147.22
  port: 80
  uuid: 3f638f34-8dba-4186-bc43-2716a7ddd4be
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /az05.beyondy.cfd:443/link
    headers:
      Host: telegram----cassiusvpn----3.kale-e08.workers.dev
- name: VMESS-GRzld
  type: vmess
  server: 45.147.201.231
  port: 23085
  uuid: 1cc59a3a-9625-40f7-b0e6-e233286ae82d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: Trojan-6fHcz
  type: trojan
  server: 217.163.76.221
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'allowInsecure: 1, sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz,
    path: /proxyip=217.163.76.221:443, proxyIP: null'
- name: Trojan-T0bUq
  type: trojan
  server: 212.183.88.172
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz, allowInsecure:
    1'
- name: Trojan-Fuy2M
  type: trojan
  server: 104.18.2.150
  port: 443
  password: trojan
  params: 'security: tls, sni: main.xicun.us.kg, type: ws, host: main.xicun.us.kg'
- name: Trojan-NsPua
  type: trojan
  server: 172.67.205.22
  port: 443
  password: 5453ae26-250d-4e79-b4ec-016baf806865
  params: 'sni: 1SSdDdFfffHhHJJJJ.20220420.Pp.uA, allowInsecure: 1, type: ws, path:
    /OYzPAeaZdXUq2d6J3gc4aj, host: 1ssdddffffhhhjjjj.20220420.pp.ua, fp: chrome'
- name: Trojan-xhUpe
  type: trojan
  server: 104.21.83.113
  port: 443
  password: 4a3ee276-f50f-46f6-ba4d-13571732ab70
  params: 'security: tls, sni: SxcDe3.859886.XYz, type: ws, host: sxcde3.859886.xyz,
    path: /COp52Dbu3dvwvDWUxOqxq, fp: chrome, alpn: http/1.1'
- name: Trojan-iPn6D
  type: trojan
  server: 45.67.215.218
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz, allowInsecure:
    1'
- name: Trojan-Rhg5Y
  type: trojan
  server: 13.38.145.138
  port: 22223
  password: telegram-id-directvpn
  params: 'security: tls, sni: trojan.burgerip.co.uk'
- name: Trojan-zo48n
  type: trojan
  server: 160.79.105.81
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, allowInsecure: 1, type: ws, path: /proxyip=160.79.105.81:443&proxyIP=null,
    host: icecream.955850.xyz'
- name: Trojan-q20bm
  type: trojan
  server: 185.16.110.113
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz, allowInsecure:
    1'
- name: Trojan-acarp
  type: trojan
  server: 202.37.33.80
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, allowInsecure: 1, type: ws, path: /proxyip=202.37.33.80:443&proxyIP=null,
    host: icecream.955850.xyz'
- name: Trojan-y0i8Z
  type: trojan
  server: 59.3.209.82
  port: 50000
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, allowInsecure: 1, type: ws, path: /proxyip=59.3.209.82:50000&proxyIP=null,
    host: icecream.955850.xyz'
- name: Trojan-hDZ4v
  type: trojan
  server: 162.159.153.216
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz, allowInsecure:
    1'
- name: Trojan-Fasl3
  type: trojan
  server: 160.79.105.169
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz, allowInsecure:
    1'
- name: Trojan-cjim4
  type: trojan
  server: 217.163.76.254
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz, allowInsecure:
    0'
- name: Trojan-FLFE7
  type: trojan
  server: 212.183.88.194
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz, allowInsecure:
    0'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-p413G
  - SS-drK1I
  - SSR-ixZ6X
  - VMESS-jBKR4
  - VMESS-Ltnbi
  - VMESS-LObSq
  - VMESS-kJsFA
  - VMESS-ofItm
  - VMESS-FBLbv
  - VMESS-KXA5J
  - VMESS-g4O65
  - VMESS-rsPnN
  - VMESS-7w1oW
  - VMESS-B5Bj7
  - VMESS-U1hjW
  - VMESS-GRzld
  - Trojan-6fHcz
  - Trojan-T0bUq
  - Trojan-Fuy2M
  - Trojan-NsPua
  - Trojan-xhUpe
  - Trojan-iPn6D
  - Trojan-Rhg5Y
  - Trojan-zo48n
  - Trojan-q20bm
  - Trojan-acarp
  - Trojan-y0i8Z
  - Trojan-hDZ4v
  - Trojan-Fasl3
  - Trojan-cjim4
  - Trojan-FLFE7
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-p413G
  - SS-drK1I
  - SSR-ixZ6X
  - VMESS-jBKR4
  - VMESS-Ltnbi
  - VMESS-LObSq
  - VMESS-kJsFA
  - VMESS-ofItm
  - VMESS-FBLbv
  - VMESS-KXA5J
  - VMESS-g4O65
  - VMESS-rsPnN
  - VMESS-7w1oW
  - VMESS-B5Bj7
  - VMESS-U1hjW
  - VMESS-GRzld
  - Trojan-6fHcz
  - Trojan-T0bUq
  - Trojan-Fuy2M
  - Trojan-NsPua
  - Trojan-xhUpe
  - Trojan-iPn6D
  - Trojan-Rhg5Y
  - Trojan-zo48n
  - Trojan-q20bm
  - Trojan-acarp
  - Trojan-y0i8Z
  - Trojan-hDZ4v
  - Trojan-Fasl3
  - Trojan-cjim4
  - Trojan-FLFE7
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
