port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-0iYDp
  type: ss
  server: 46.17.45.228
  port: 11111
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-WJNPH
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-5K53S
  type: vmess
  server: 195.154.40.247
  port: 33639
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-ceGn5
  type: vmess
  server: web.51.la
  port: 443
  uuid: e0c6b3b7-9f5b-4bd6-9abf-260663aa4f1b
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-gAKZm
  type: vmess
  server: web.51.la
  port: 443
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-eTlqy
  type: vmess
  server: web.51.la
  port: 443
  uuid: c6e84072-2e69-4928-90af-436b3fcd0663
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: SS-rJ5sY
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18008
  cipher: aes-256-gcm
  password: 6EZ5QKFX60AVSUYT
- name: VMESS-eX55S
  type: vmess
  server: 7b5d670c-sw1z40-swjbhe-8bem.hgc1.tcpbbr.net
  port: 8080
  uuid: ca506e08-ce3d-5e5a-c128-6358caca15e5
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-wLG1Y
  type: vmess
  server: xxxsde4.freevpnatm2025.dpdns.org
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: xxxsde4.freevpnatm2025.dpdns.org
- name: VMESS-2Q9zg
  type: vmess
  server: 019be018-swq1s0-sx1srd-1m0fq.hgc1.tcpbbr.net
  port: 8080
  uuid: a698c4a6-c3c9-11ee-9693-f23c91cfbbc9
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-DfYEZ
  type: vmess
  server: 507dabb3-swtr40-sxzp1j-1irfn.hgc1.tcpbbr.net
  port: 8080
  uuid: a33115b6-75fa-11ed-8826-f23c9164ca5d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-dToNM
  type: vmess
  server: 5tghyu8.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: ''
- name: VMESS-Oh9sH
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 118287d2-e968-42e1-80d0-12fa2f5d38d6
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: sahand.serveminecraft.net
- name: VMESS-nFzdn
  type: vmess
  server: 104.21.64.1
  port: 2096
  uuid: 8f78e709-2c5f-4c19-9f44-b5b5f80ab74c
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cc2d1.988988.shop
- name: VMESS-xg6J1
  type: vmess
  server: xcdvfrr54.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: ''
- name: VMESS-kQTHc
  type: vmess
  server: 2cd9bcb4-sw1z40-sw0aec-1t3oz.hgc1.tcpbbr.net
  port: 8080
  uuid: b3370cdc-c26e-11ef-bd97-f23c9164ca5d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-3pvmw
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: Trojan-2VaVi
  type: trojan
  server: 104.21.35.247
  port: 443
  password: c8eac4b7-95ba-4ce0-920d-c3279eb3b391
  params: 'sni: ff.HuangSHANg2030.DPDnS.oRg, type: ws, path: /ptGwaGzcA4KNAXX, host:
    ff.huangshang2030.dpdns.org'
- name: Trojan-E2qP8
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'sni: 36.151.251.61, allowInsecure: 1'
- name: Trojan-E8lLr
  type: trojan
  server: 36.151.251.62
  port: 3330
  password: RlzoEILU
  params: 'sni: cdn.egvra.cn, allowInsecure: 1'
- name: Trojan-dwzic
  type: trojan
  server: 36.151.251.62
  port: 13542
  password: RlzoEILU
  params: 'sni: cdn.egvra.cn, allowInsecure: 1'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-0iYDp
  - SSR-WJNPH
  - VMESS-5K53S
  - VMESS-ceGn5
  - VMESS-gAKZm
  - VMESS-eTlqy
  - SS-rJ5sY
  - VMESS-eX55S
  - VMESS-wLG1Y
  - VMESS-2Q9zg
  - VMESS-DfYEZ
  - VMESS-dToNM
  - VMESS-Oh9sH
  - VMESS-nFzdn
  - VMESS-xg6J1
  - VMESS-kQTHc
  - VMESS-3pvmw
  - Trojan-2VaVi
  - Trojan-E2qP8
  - Trojan-E8lLr
  - Trojan-dwzic
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-0iYDp
  - SSR-WJNPH
  - VMESS-5K53S
  - VMESS-ceGn5
  - VMESS-gAKZm
  - VMESS-eTlqy
  - SS-rJ5sY
  - VMESS-eX55S
  - VMESS-wLG1Y
  - VMESS-2Q9zg
  - VMESS-DfYEZ
  - VMESS-dToNM
  - VMESS-Oh9sH
  - VMESS-nFzdn
  - VMESS-xg6J1
  - VMESS-kQTHc
  - VMESS-3pvmw
  - Trojan-2VaVi
  - Trojan-E2qP8
  - Trojan-E8lLr
  - Trojan-dwzic
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
