port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-Oyyvz
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-xb0m9
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-rNx9O
  type: vmess
  server: 195.154.40.247
  port: 38952
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-Oyyvz
  - SSR-xb0m9
  - VMESS-rNx9O
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-Oyyvz
  - SSR-xb0m9
  - VMESS-rNx9O
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
