port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-ZRqre
  type: ss
  server: 46.17.45.228
  port: 11111
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-UCXQ4
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-gGPwc
  type: vmess
  server: 195.154.40.247
  port: 19750
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-8ULmb
  type: vmess
  server: web.51.la
  port: 443
  uuid: c6e84072-2e69-4928-90af-436b3fcd0663
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Lck2y
  type: vmess
  server: web.51.la
  port: 443
  uuid: 88888888-8888-8888-8888-888888888888
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-EbbsH
  type: vmess
  server: web.51.la
  port: 443
  uuid: e0c6b3b7-9f5b-4bd6-9abf-260663aa4f1b
  alterId: 0
  cipher: auto
  tls: true
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: SS-ucTQl
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
- name: VMESS-NkfVV
  type: vmess
  server: yal.fxlcn.com
  port: 45263
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-IGXXJ
  type: vmess
  server: 104.21.82.183
  port: 8880
  uuid: 5a7021e0-26b4-45d6-b175-fe551601ca97
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server26.beheshtbaneh.com
- name: VMESS-s3MHG
  type: vmess
  server: xcdvfrr54.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: ''
- name: VMESS-MlakG
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 118287d2-e968-42e1-80d0-12fa2f5d38d6
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: sahand.serveminecraft.net
- name: VMESS-2A9cP
  type: vmess
  server: 45.147.201.231
  port: 23092
  uuid: 28f6d888-cbc5-4210-8cd2-b40cf566d9a8
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-ewc2P
  type: vmess
  server: gov.uk
  port: 443
  uuid: 77848824-93b7-4b89-ffd0-e91afff406ce
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /77848824
    headers:
      Host: zheshiscp.com
- name: VMESS-QQfk4
  type: vmess
  server: 104.21.23.231
  port: 2082
  uuid: 2f821152-c3e9-4074-9185-2790e7425f42
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cs.flha.ru
- name: Trojan-43tUM
  type: trojan
  server: 13.36.216.174
  port: 22222
  password: telegram-id-privatevpns
  params: 'security: tls, sni: trojan.burgerip.co.uk'
- name: Trojan-KEmRX
  type: trojan
  server: 172.67.144.126
  port: 443
  password: 895552fa-6284-4c1d-ba00-3944e0c7c626
  params: 'sni: CFR56ty7890.288288.sHOP, type: ws, path: /By7cEmOrNRS58yeduy9AOG,
    host: cfr56ty7890.288288.shop'
- name: Trojan-v1Shi
  type: trojan
  server: 104.21.35.247
  port: 443
  password: c8eac4b7-95ba-4ce0-920d-c3279eb3b391
  params: 'sni: ff.HuangSHANg2030.DPDnS.oRg, type: ws, path: /ptGwaGzcA4KNAXX, host:
    ff.huangshang2030.dpdns.org'
- name: Trojan-w7LYk
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'sni: 120.233.44.201, allowInsecure: 1'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-ZRqre
  - SSR-UCXQ4
  - VMESS-gGPwc
  - VMESS-8ULmb
  - VMESS-Lck2y
  - VMESS-EbbsH
  - SS-ucTQl
  - VMESS-NkfVV
  - VMESS-IGXXJ
  - VMESS-s3MHG
  - VMESS-MlakG
  - VMESS-2A9cP
  - VMESS-ewc2P
  - VMESS-QQfk4
  - Trojan-43tUM
  - Trojan-KEmRX
  - Trojan-v1Shi
  - Trojan-w7LYk
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-ZRqre
  - SSR-UCXQ4
  - VMESS-gGPwc
  - VMESS-8ULmb
  - VMESS-Lck2y
  - VMESS-EbbsH
  - SS-ucTQl
  - VMESS-NkfVV
  - VMESS-IGXXJ
  - VMESS-s3MHG
  - VMESS-MlakG
  - VMESS-2A9cP
  - VMESS-ewc2P
  - VMESS-QQfk4
  - Trojan-43tUM
  - Trojan-KEmRX
  - Trojan-v1Shi
  - Trojan-w7LYk
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
