port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-BRHBd
  type: ss
  server: 47.129.170.255
  port: 443
  cipher: aes-256-cfb
  password: qawszxc123
- name: SS-wdSBy
  type: ss
  server: 125.141.26.12
  port: 4857
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-I0nhG
  type: ss
  server: 43.226.17.17
  port: 19363
  cipher: chacha20-ietf-poly1305
  password: 2e96aa2f3054
- name: SS-cGIG1
  type: ss
  server: 103.186.154.29
  port: 38388
  cipher: aes-256-cfb
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
- name: SS-Z0dTS
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-mNhy7
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 16012
  cipher: aes-256-gcm
  password: NEYGNTEW7HUQHA1I
- name: SS-6b8LW
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-m84NM
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-3gXtE
  type: ss
  server: hkkh11v1.xpmc.cc
  port: 36368
  cipher: chacha20-ietf-poly1305
  password: 91a41f4e02dc
- name: SS-M1voM
  type: ss
  server: 154.90.63.177
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-DQHcH
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-sxGeK
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: VMESS-U9QI7
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-zIjjN
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-9WWeT
  type: vmess
  server: e871a090-sva740-tcq5zn-19qpt.cm.plebai.net
  port: 15229
  uuid: 4b9ca118-7fab-11eb-bd3a-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-agVbF
  type: vmess
  server: 34ac196c-svlb40-tdnzz0-1qtp7.cm5.p5pv.com
  port: 17232
  uuid: 3653c708-df72-11ee-aec1-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Odh38
  type: vmess
  server: 183.236.51.38
  port: 49302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-8BoaM
  type: vmess
  server: 8.211.154.107
  port: 50951
  uuid: a3d04548-625c-4658-9ff0-f9a7835d1f6d
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-W6Odf
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-VmWfh
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-5rMz0
  type: vmess
  server: e871a090-sva740-tcq5zn-19qpt.cm.plebai.net
  port: 15229
  uuid: 4b9ca118-7fab-11eb-bd3a-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Cb715
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-3TG6P
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Hydz8
  type: vmess
  server: 183.236.51.38
  port: 49302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-veTPJ
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-paUjD
  type: vmess
  server: 34ac196c-svlb40-tdnzz0-1qtp7.cm5.p5pv.com
  port: 17232
  uuid: 3653c708-df72-11ee-aec1-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-LI9JI
  type: vmess
  server: tk.hzlt.tkddns.xyz
  port: 22642
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-b.tkong.cc
- name: VMESS-O7KpW
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-5LfqT
  type: vmess
  server: 120.236.198.165
  port: 22641
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-a.tkong.cc
- name: VMESS-WfLCt
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-vrJlC
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-0F9Hy
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-IUnLu
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: Trojan-ycWSU
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 1, sni: 120.233.44.201'
- name: Trojan-0KOKx
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-rNVzK
  type: trojan
  server: usla.mjt000.com
  port: 443
  password: e4af2638-bb12-4e4a-84f1-a032e23ca63f
  params: 'allowInsecure: 0, sni: usla.mjt000.com'
- name: Trojan-fsRRF
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 1'
- name: Trojan-ZN8g3
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: Trojan-qYmdB
  type: trojan
  server: bd8e9b7d-swzb40-t5vrf3-716s.cu.plebai.net
  port: 15229
  password: 088a0bbe-4f9f-11ea-a15d-f23c913c8d2b
  params: 'allowInsecure: 1, sni: bd8e9b7d-swzb40-t5vrf3-716s.cu.plebai.net'
- name: Trojan-saFdI
  type: trojan
  server: diagram.protocolbuffer.com
  port: 18334
  password: YaN8FFNe58nga3xAu3yTx0CSllcSeOnDZOj3SXROCz3S34B9D3F7Ka0aYa8yaxpXCDRKZ
  params: 'allowInsecure: 0'
- name: Trojan-YAZaI
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: 36.151.251.61'
- name: Trojan-n0LkJ
  type: trojan
  server: f5ada702-swb8g0-t5fh9u-1uni.cu.plebai.net
  port: 15229
  password: adbd0a82-3336-11ed-bd7c-f23c913c8d2b
  params: 'allowInsecure: 1'
- name: Trojan-nFgkq
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: Trojan-04uJk
  type: trojan
  server: bapus.koreanbbq.link
  port: 443
  password: 94Xn93e3F2uOxCE8De8upAAwnlI8ySRRj70Ol6zgYNBjZFCDK5Yaca3D8aT2qaxyEc0DK
  params: 'allowInsecure: 0'
- name: Trojan-8O6WH
  type: trojan
  server: 36.156.102.123
  port: 50723
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: 36.156.102.123'
- name: Trojan-DGA8P
  type: trojan
  server: 36.151.251.62
  port: 13542
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-gFnzU
  type: trojan
  server: 5f9d335d-swexs0-t5juhn-4tue.cu.plebai.net
  port: 15229
  password: fe506496-24eb-11ef-abd3-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 5f9d335d-swexs0-t5juhn-4tue.cu.plebai.net'
- name: Trojan-OPRyy
  type: trojan
  server: 36.151.251.62
  port: 3330
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-6uBK7
  type: trojan
  server: 7d09e919-swq1s0-tcvn0z-1tlyg.cu.plebai.net
  port: 15229
  password: be8ba532-0dcf-11f0-9a65-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 7d09e919-swq1s0-tcvn0z-1tlyg.cu.plebai.net'
- name: SS-ZCp63
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
- name: VMESS-7eTTw
  type: vmess
  server: cdn2.bpcdn.cc
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: gz4wah11v4bem6ws.lovebaipiao.com
- name: VMESS-EXw4p
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-JVa2Q
  type: vmess
  server: 193.123.81.105
  port: 443
  uuid: 9b456c2a-f2c1-45e1-87a9-b7628b04bb24
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: beyonddsz.cfd
- name: VMESS-DKxE9
  type: vmess
  server: cdn2.bpcdn.cc
  port: 80
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: tk1.bk5jh4t6w.jiesk4pdqcqjo16j.xyz
- name: VMESS-zzhu5
  type: vmess
  server: www.wn03.cc
  port: 80
  uuid: 2f38f848-a899-4c87-9807-207a41615e3c
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /rongseven?ed=2048
    headers:
      Host: us.freeyyds.dpdns.org
- name: VMESS-PRdiZ
  type: vmess
  server: 141.193.213.168
  port: 2086
  uuid: 1bf31ad5-cbd4-4c10-a832-81ce4a9ee6c0
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ustoucjjnid18sj6us.lovebaipiao.com
- name: VMESS-DXPDx
  type: vmess
  server: hk2.lrzdx.uk
  port: 443
  uuid: db69d5bc-d36c-4903-f471-74b98c5cefe5
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /register
    headers:
      Host: ''
- name: VMESS-vg7IP
  type: vmess
  server: gov.uk
  port: 443
  uuid: 77848824-93b7-4b89-ffd0-e91afff406ce
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /77848824
    headers:
      Host: zheshiscp.com
- name: VMESS-fpet0
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: Trojan-g0LgG
  type: trojan
  server: mailbox.meijireform.com
  port: 28332
  password: FNCEZ4Z336SlI8TRlyx3Y3SljwaxFexDNRxzya4R82DEOOCYR25eOSBq0K0ez9ZnaX9D3
  params: ''
- name: Trojan-r4F7N
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 0, sni: 120.233.44.201'
- name: Trojan-yGSW1
  type: trojan
  server: 104.21.64.1
  port: 443
  password: 44ed7a37-af89-4cd1-8680-83a7207810d9
  params: 'sni: 21sWDE.7777128.xYZ, allowInsecure: 1, type: ws, path: /HpYP4foAlpTKtfYnjLYhU30U,
    host: 21sWDE.7777128.xYZ, fp: chrome'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-BRHBd
  - SS-wdSBy
  - SS-I0nhG
  - SS-cGIG1
  - SS-Z0dTS
  - SS-mNhy7
  - SS-6b8LW
  - SS-m84NM
  - SS-3gXtE
  - SS-M1voM
  - SS-DQHcH
  - SS-sxGeK
  - VMESS-U9QI7
  - VMESS-zIjjN
  - VMESS-9WWeT
  - VMESS-agVbF
  - VMESS-Odh38
  - VMESS-8BoaM
  - VMESS-W6Odf
  - VMESS-VmWfh
  - VMESS-5rMz0
  - VMESS-Cb715
  - VMESS-3TG6P
  - VMESS-Hydz8
  - VMESS-veTPJ
  - VMESS-paUjD
  - VMESS-LI9JI
  - VMESS-O7KpW
  - VMESS-5LfqT
  - VMESS-WfLCt
  - VMESS-vrJlC
  - VMESS-0F9Hy
  - VMESS-IUnLu
  - Trojan-ycWSU
  - Trojan-0KOKx
  - Trojan-rNVzK
  - Trojan-fsRRF
  - Trojan-ZN8g3
  - Trojan-qYmdB
  - Trojan-saFdI
  - Trojan-YAZaI
  - Trojan-n0LkJ
  - Trojan-nFgkq
  - Trojan-04uJk
  - Trojan-8O6WH
  - Trojan-DGA8P
  - Trojan-gFnzU
  - Trojan-OPRyy
  - Trojan-6uBK7
  - SS-ZCp63
  - VMESS-7eTTw
  - VMESS-EXw4p
  - VMESS-JVa2Q
  - VMESS-DKxE9
  - VMESS-zzhu5
  - VMESS-PRdiZ
  - VMESS-DXPDx
  - VMESS-vg7IP
  - VMESS-fpet0
  - Trojan-g0LgG
  - Trojan-r4F7N
  - Trojan-yGSW1
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-BRHBd
  - SS-wdSBy
  - SS-I0nhG
  - SS-cGIG1
  - SS-Z0dTS
  - SS-mNhy7
  - SS-6b8LW
  - SS-m84NM
  - SS-3gXtE
  - SS-M1voM
  - SS-DQHcH
  - SS-sxGeK
  - VMESS-U9QI7
  - VMESS-zIjjN
  - VMESS-9WWeT
  - VMESS-agVbF
  - VMESS-Odh38
  - VMESS-8BoaM
  - VMESS-W6Odf
  - VMESS-VmWfh
  - VMESS-5rMz0
  - VMESS-Cb715
  - VMESS-3TG6P
  - VMESS-Hydz8
  - VMESS-veTPJ
  - VMESS-paUjD
  - VMESS-LI9JI
  - VMESS-O7KpW
  - VMESS-5LfqT
  - VMESS-WfLCt
  - VMESS-vrJlC
  - VMESS-0F9Hy
  - VMESS-IUnLu
  - Trojan-ycWSU
  - Trojan-0KOKx
  - Trojan-rNVzK
  - Trojan-fsRRF
  - Trojan-ZN8g3
  - Trojan-qYmdB
  - Trojan-saFdI
  - Trojan-YAZaI
  - Trojan-n0LkJ
  - Trojan-nFgkq
  - Trojan-04uJk
  - Trojan-8O6WH
  - Trojan-DGA8P
  - Trojan-gFnzU
  - Trojan-OPRyy
  - Trojan-6uBK7
  - SS-ZCp63
  - VMESS-7eTTw
  - VMESS-EXw4p
  - VMESS-JVa2Q
  - VMESS-DKxE9
  - VMESS-zzhu5
  - VMESS-PRdiZ
  - VMESS-DXPDx
  - VMESS-vg7IP
  - VMESS-fpet0
  - Trojan-g0LgG
  - Trojan-r4F7N
  - Trojan-yGSW1
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
