port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-5LDo1
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-NpT0H
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-k9NxN
  type: vmess
  server: 195.154.40.247
  port: 38952
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-GnCmS
  type: vmess
  server: 172.67.71.217
  port: 443
  uuid: 9072d339-3885-4fe1-b0bc-29fa7505410e
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /fixedfloati.cfd/linkwsd
    headers:
      Host: 1t3chx0.zed23.web1337.net
- name: VMESS-SGyX8
  type: vmess
  server: yal.fxlcn.com
  port: 45263
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-mJTVJ
  type: vmess
  server: 120.198.71.216
  port: 35921
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-X5kkt
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-l19rn
  type: vmess
  server: de01.sh-cloudflare.sbs
  port: 2096
  uuid: b3928f8d-ea81-4d75-bcec-4016a072adff
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: de01.sh-cloudflare.sbs
- name: VMESS-DPQAH
  type: vmess
  server: c1xxdcswe.777169.xyz
  port: 80
  uuid: cad5a49f-14e5-4a05-aae9-c5df8fad394f
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /TjUzWyRmR4P2fGqXENw4Z4
    headers:
      Host: c1xxdcswe.777169.xyz
- name: VMESS-524cS
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 2ff97c6d-8557-42a4-b43f-19c77c5959ea
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: irsoft.sytes.net
- name: VMESS-zbcRj
  type: vmess
  server: 120.198.71.216
  port: 46759
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-QlxTu
  type: vmess
  server: 104.21.112.1
  port: 2053
  uuid: 996016f7-da89-45f1-b3b4-555bc799ed86
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: rak2d1.777269.xyz
- name: VMESS-dm9Xf
  type: vmess
  server: m11sdfg.890604.dpdns.org
  port: 80
  uuid: 0a28b420-4f7c-43ad-a29e-80068ce08263
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /lhU8ShsoPZlulnnYPb86csp
    headers:
      Host: m11sdfg.890604.dpdns.org
- name: VMESS-TmhG6
  type: vmess
  server: 104.21.80.1
  port: 2053
  uuid: 996016f7-da89-45f1-b3b4-555bc799ed86
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: rak2d1.777269.xyz
- name: VMESS-p5fPq
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-Xb4S0
  type: vmess
  server: v18.nmcf.me
  port: 8000
  uuid: d26fc1a3-0d97-416b-abcd-b335b4bf7881
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /nmkj
    headers:
      Host: www.bing.com
- name: Trojan-R7lwZ
  type: trojan
  server: 172.67.181.193
  port: 443
  password: c8eac4b7-95ba-4ce0-920d-c3279eb3b391
  params: 'security: tls, sni: EEeEee4.hUAngSHANG2030.dPdNS.org, type: ws, host: EEeEee4.hUAngSHANG2030.dPdNS.org,
    path: /ptGwaGzcA4KNAXX'
- name: Trojan-E9B5M
  type: trojan
  server: 13.49.13.19
  port: 22223
  password: telegram-id-directvpn
  params: 'security: tls, sni: trojan.burgerip.co.uk, type: tcp, alpn: http/1.1'
- name: Trojan-zFPIv
  type: trojan
  server: 172.67.207.27
  port: 443
  password: 061ec9d5-ba40-428a-8be0-1947b10b5cfc
  params: 'security: tls, sni: T.taipEi108.Dpdns.Org, type: ws, host: t.taipei108.dpdns.org,
    path: /Dmby2AKiZKvMo1YauoQwY5, fp: chrome, alpn: http/1.1'
- name: Trojan-VVOyy
  type: trojan
  server: 104.24.92.207
  port: 2053
  password: '123'
  params: 'sni: epeius001-ea1.pages.dev, type: ws, host: epeius001-ea1.pages.dev'
- name: Trojan-pbPrW
  type: trojan
  server: 36.151.251.59
  port: 7815
  password: RlzoEILU
  params: 'allowInsecure: 0'
- name: Trojan-ll5Ad
  type: trojan
  server: 104.21.23.72
  port: 443
  password: vip
  params: 'security: tls, sni: heihu880.pages.dev, type: ws, host: heihu880.pages.dev,
    path: /?ed=2560'
- name: Trojan-rJyrf
  type: trojan
  server: 104.25.165.81
  port: 8443
  password: '123456'
  params: 'security: tls, sni: top-azx.pages.dev, type: ws, host: top-azx.pages.dev'
- name: Trojan-eW4SC
  type: trojan
  server: 172.67.200.117
  port: 443
  password: c6840587-7ac4-40be-aa4b-ae327eb4fa53
  params: 'security: tls, sni: ccdfRt6.890634.Xyz, type: ws, host: ccdfrt6.890634.xyz,
    path: /ogSVyJu0ksqZjqvVUXlLhk95Ad, fp: chrome, alpn: http/1.1'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-5LDo1
  - SSR-NpT0H
  - VMESS-k9NxN
  - VMESS-GnCmS
  - VMESS-SGyX8
  - VMESS-mJTVJ
  - VMESS-X5kkt
  - VMESS-l19rn
  - VMESS-DPQAH
  - VMESS-524cS
  - VMESS-zbcRj
  - VMESS-QlxTu
  - VMESS-dm9Xf
  - VMESS-TmhG6
  - VMESS-p5fPq
  - VMESS-Xb4S0
  - Trojan-R7lwZ
  - Trojan-E9B5M
  - Trojan-zFPIv
  - Trojan-VVOyy
  - Trojan-pbPrW
  - Trojan-ll5Ad
  - Trojan-rJyrf
  - Trojan-eW4SC
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-5LDo1
  - SSR-NpT0H
  - VMESS-k9NxN
  - VMESS-GnCmS
  - VMESS-SGyX8
  - VMESS-mJTVJ
  - VMESS-X5kkt
  - VMESS-l19rn
  - VMESS-DPQAH
  - VMESS-524cS
  - VMESS-zbcRj
  - VMESS-QlxTu
  - VMESS-dm9Xf
  - VMESS-TmhG6
  - VMESS-p5fPq
  - VMESS-Xb4S0
  - Trojan-R7lwZ
  - Trojan-E9B5M
  - Trojan-zFPIv
  - Trojan-VVOyy
  - Trojan-pbPrW
  - Trojan-ll5Ad
  - Trojan-rJyrf
  - Trojan-eW4SC
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
