port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-Rsa7Q
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SS-HAtS6
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
- name: SS-xRFV5
  type: ss
  server: 147.45.116.44
  port: 443
  cipher: chacha20-ietf-poly1305
  password: ezG2Lqx8SS68
- name: SSR-Szo6l
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-1z4F4
  type: vmess
  server: 195.154.40.247
  port: 38952
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-ApvxP
  type: vmess
  server: cloudgetservice.mcloudservice.site
  port: 443
  uuid: 8f922e2e-18f3-4bd9-a097-09c2d7c139be
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /linkws?ed=2560
    headers:
      Host: MAxNEtViP-gEr-vp1.MaXnETcLOuDSErVice.com
- name: VMESS-qUS78
  type: vmess
  server: v5.heduian.link
  port: 30805
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-uPHx7
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-7Ui8i
  type: vmess
  server: 104.21.80.1
  port: 2053
  uuid: 996016f7-da89-45f1-b3b4-555bc799ed86
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: rak2d1.777269.xyz
- name: VMESS-jbhCW
  type: vmess
  server: www.visa.com.tw
  port: 443
  uuid: 982087ef-8851-44df-eb8e-836f3362f3f1
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /by-zedware-network/?ed=2560
    headers:
      Host: oracle-sjc.ecp.dpdns.org
- name: VMESS-ZZBza
  type: vmess
  server: tk.hzlt.tkddns.xyz
  port: 22641
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-a.tkong.cc
- name: VMESS-Tjmbj
  type: vmess
  server: 104.21.112.1
  port: 2083
  uuid: 996016f7-da89-45f1-b3b4-555bc799ed86
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: rak2d2.777269.xyz
- name: VMESS-xqJFs
  type: vmess
  server: 120.232.153.40
  port: 40292
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-zRFCI
  type: vmess
  server: v6.heduian.link
  port: 30806
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-PxI1o
  type: vmess
  server: auth0.openai.com
  port: 443
  uuid: e537f2f5-2a0c-4f59-92c9-832ca6433bf3
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /irvideo.cfd/linkws
    headers:
      Host: admin.kasrax.ir
- name: VMESS-VEJbg
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 2ff97c6d-8557-42a4-b43f-19c77c5959ea
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: irsoft.sytes.net
- name: VMESS-uJBEi
  type: vmess
  server: 120.232.153.63
  port: 37805
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-6JpeU
  type: vmess
  server: us01.sh-cloudflare.sbs
  port: 8443
  uuid: 2bd0c9d7-f239-437e-a1e1-6cf830af2a1a
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-wByj9
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-vy8iG
  type: vmess
  server: 120.198.71.219
  port: 51095
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-LyeCU
  type: vmess
  server: 104.21.82.183
  port: 8880
  uuid: 5a7021e0-26b4-45d6-b175-fe551601ca97
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server26.beheshtbaneh.com
- name: VMESS-jFV9Z
  type: vmess
  server: 183.236.51.38
  port: 41024
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-131Jb
  type: vmess
  server: 120.232.153.41
  port: 46597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-7NFQu
  type: vmess
  server: 120.232.153.41
  port: 44491
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-3bcSp
  type: vmess
  server: 141.101.120.253
  port: 2096
  uuid: 381cb6d1-6ad4-4909-8494-b8d786cf78ce
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: 1746882891.speed.adl.cccp.freefly.pp.ua
- name: Trojan-wPXa4
  type: trojan
  server: gzyd.cg.xxality.cn
  port: 35000
  password: 09e8b39a-4c09-4df0-a50c-af3bef01567e
  params: 'allowInsecure: 0, sni: cgsg2.hysality.com'
- name: Trojan-UFEDn
  type: trojan
  server: 172.67.216.240
  port: 443
  password: 70776bb4-d791-4cbd-9c9b-c76e937f9e60
  params: 'sni: Xxs345rf.857856.xYZ, allowInsecure: 1, type: ws, path: /71M8Ov1I5Gk9247fHC0XGZG6,
    host: Xxs345rf.857856.xYZ'
- name: Trojan-KnEld
  type: trojan
  server: 217.163.76.221
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'allowInsecure: 1, sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz,
    path: /proxyip=217.163.76.221:443, proxyIP: null'
- name: Trojan-be3gX
  type: trojan
  server: 172.67.181.193
  port: 443
  password: c8eac4b7-95ba-4ce0-920d-c3279eb3b391
  params: 'security: tls, sni: EEeEee4.hUAngSHANG2030.dPdNS.org, type: ws, host: EEeEee4.hUAngSHANG2030.dPdNS.org,
    path: /ptGwaGzcA4KNAXX'
- name: Trojan-IYrLs
  type: trojan
  server: 160.79.105.169
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz, allowInsecure:
    1'
- name: Trojan-qeUr6
  type: trojan
  server: 103.116.7.21
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'security: tls, sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz,
    path: /proxyip=45.67.215.153:443&proxyIP=null, fp: randomized, alpn: h3'
- name: Trojan-lZpC3
  type: trojan
  server: 91.227.77.87
  port: 443
  password: bpb-trojan
  params: 'security: tls, sni: skwygx.top, type: ws, host: skwygx.top, path: /tr'
- name: Trojan-xXciz
  type: trojan
  server: 217.163.76.89
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'allowInsecure: 1, sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz,
    path: /proxyip=217.163.76.89:443, proxyIP: null'
- name: Trojan-bS2oK
  type: trojan
  server: 36.151.251.59
  port: 7815
  password: RlzoEILU
  params: 'allowInsecure: 0'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-Rsa7Q
  - SS-HAtS6
  - SS-xRFV5
  - SSR-Szo6l
  - VMESS-1z4F4
  - VMESS-ApvxP
  - VMESS-qUS78
  - VMESS-uPHx7
  - VMESS-7Ui8i
  - VMESS-jbhCW
  - VMESS-ZZBza
  - VMESS-Tjmbj
  - VMESS-xqJFs
  - VMESS-zRFCI
  - VMESS-PxI1o
  - VMESS-VEJbg
  - VMESS-uJBEi
  - VMESS-6JpeU
  - VMESS-wByj9
  - VMESS-vy8iG
  - VMESS-LyeCU
  - VMESS-jFV9Z
  - VMESS-131Jb
  - VMESS-7NFQu
  - VMESS-3bcSp
  - Trojan-wPXa4
  - Trojan-UFEDn
  - Trojan-KnEld
  - Trojan-be3gX
  - Trojan-IYrLs
  - Trojan-qeUr6
  - Trojan-lZpC3
  - Trojan-xXciz
  - Trojan-bS2oK
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-Rsa7Q
  - SS-HAtS6
  - SS-xRFV5
  - SSR-Szo6l
  - VMESS-1z4F4
  - VMESS-ApvxP
  - VMESS-qUS78
  - VMESS-uPHx7
  - VMESS-7Ui8i
  - VMESS-jbhCW
  - VMESS-ZZBza
  - VMESS-Tjmbj
  - VMESS-xqJFs
  - VMESS-zRFCI
  - VMESS-PxI1o
  - VMESS-VEJbg
  - VMESS-uJBEi
  - VMESS-6JpeU
  - VMESS-wByj9
  - VMESS-vy8iG
  - VMESS-LyeCU
  - VMESS-jFV9Z
  - VMESS-131Jb
  - VMESS-7NFQu
  - VMESS-3bcSp
  - Trojan-wPXa4
  - Trojan-UFEDn
  - Trojan-KnEld
  - Trojan-be3gX
  - Trojan-IYrLs
  - Trojan-qeUr6
  - Trojan-lZpC3
  - Trojan-xXciz
  - Trojan-bS2oK
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
