port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: VMESS-voIIH
  type: vmess
  server: 183.236.51.38
  port: 41024
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-7yzxf
  type: vmess
  server: 120.198.71.216
  port: 59082
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-azGLw
  type: vmess
  server: 120.198.71.216
  port: 46159
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-NqRod
  type: vmess
  server: 120.232.153.63
  port: 37805
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-ufjGB
  type: vmess
  server: 120.198.71.219
  port: 51095
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-EETyp
  type: vmess
  server: 120.232.153.123
  port: 52352
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-riKTV
  type: vmess
  server: 120.198.71.219
  port: 49355
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-0e6Qc
  type: vmess
  server: 120.232.153.41
  port: 41491
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-aZNGw
  type: vmess
  server: 183.236.51.38
  port: 41302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: Trojan-cZhd0
  type: trojan
  server: 113.99.140.184
  port: 39001
  password: 85f133142f04dbf6547da33895cfabb3
  params: 'allowInsecure: 1, sni: www.yrtok.com'
- name: SS-bhlcM
  type: ss
  server: 45.140.169.91
  port: 11111
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-KjWJV
  type: ssr
  server: dongtaiwang5.com
  port: 42000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-e0pB7
  type: vmess
  server: 195.154.40.247
  port: 30569
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - VMESS-voIIH
  - VMESS-7yzxf
  - VMESS-azGLw
  - VMESS-NqRod
  - VMESS-ufjGB
  - VMESS-EETyp
  - VMESS-riKTV
  - VMESS-0e6Qc
  - VMESS-aZNGw
  - Trojan-cZhd0
  - SS-bhlcM
  - SSR-KjWJV
  - VMESS-e0pB7
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - VMESS-voIIH
  - VMESS-7yzxf
  - VMESS-azGLw
  - VMESS-NqRod
  - VMESS-ufjGB
  - VMESS-EETyp
  - VMESS-riKTV
  - VMESS-0e6Qc
  - VMESS-aZNGw
  - Trojan-cZhd0
  - SS-bhlcM
  - SSR-KjWJV
  - VMESS-e0pB7
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
