port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-UIEUu
  type: ss
  server: 195.154.32.37
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-FisPt
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-MDCtI
  type: vmess
  server: 195.154.40.247
  port: 31549
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-RCjZQ
  type: ss
  server: 43.226.17.17
  port: 14312
  cipher: chacha20-ietf-poly1305
  password: 2e96aa2f3054
- name: SS-2RdoF
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-uXZ5I
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: SS-RDxwz
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-FnTqH
  type: ss
  server: 52.195.15.105
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-4yIpi
  type: ss
  server: 34.212.26.32
  port: 443
  cipher: aes-256-cfb
  password: awsps0501
- name: SS-TZpPF
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-zshYM
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-FxK81
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 15007
  cipher: aes-256-gcm
  password: Q5XH89ZLTSGOQASZ
- name: SS-VYIen
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18010
  cipher: aes-256-gcm
  password: TF63RS7M0DB9OJ3B
- name: SS-4hxpm
  type: ss
  server: 125.141.26.12
  port: 4857
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-WgNDg
  type: ss
  server: hkkh11v1.xpmc.cc
  port: 20273
  cipher: chacha20-ietf-poly1305
  password: 91a41f4e02dc
- name: SS-WADaS
  type: ss
  server: 3.38.139.172
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-Gd9jh
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: VMESS-c3j6F
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-MQQAJ
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-3MQ6H
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-slqE9
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-NegH3
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-7U1Km
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-jr9xx
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-D9L8U
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-pYWK7
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-sMsc5
  type: vmess
  server: 8.211.154.107
  port: 50951
  uuid: a3d04548-625c-4658-9ff0-f9a7835d1f6d
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-pnY2f
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-Hhixh
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-pbsqZ
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-xfD7q
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-wtkbc
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: Trojan-fIcBN
  type: trojan
  server: 192.210.207.89
  port: 20080
  password: Aimer
  params: 'allowInsecure: 0, sni: epme.ambercc.filegear-sg.me, type: ws, host: epme.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-agERv
  type: trojan
  server: handles.homeofbrave.net
  port: 28332
  password: CYjXlaFOAyEDZaTe0gZaCOCyy4RwSyKYDq9SSpDCxzF33eA3SS06O28aj65a3lY3znO88
  params: 'allowInsecure: 0'
- name: Trojan-iX7O6
  type: trojan
  server: cutlery.homeofbrave.net
  port: 28331
  password: e3qTaj4gOeDDzR8lzYXpyZDpga5a3SCwyE4CO6c738aZxwlaaAD0SYSYyXOlF9S3FRF0x
  params: 'allowInsecure: 0'
- name: Trojan-mvHZN
  type: trojan
  server: huzzah.meijireform.com
  port: 28331
  password: Aa4cexaO3FReREXgAlp9CjyTjpaRNan3YDx6DxaDYFS3On0SqgF08CZcBpYxy3awXeEIC
  params: 'allowInsecure: 0'
- name: Trojan-7CDFF
  type: trojan
  server: 216.24.57.30
  port: 443
  password: tg-fq521free
  params: 'allowInsecure: 0, sni: torjan.xn--xhq44j.eu.org, type: ws, host: torjan.xn--xhq44j.eu.org,
    path: /'
- name: Trojan-CKPsP
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-V5iFM
  type: trojan
  server: 108.165.152.58
  port: 2087
  password: Aimer
  params: 'allowInsecure: 0, sni: epmw.ambercc.filegear-sg.me, type: ws, host: epmw.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-PROA9
  type: trojan
  server: luber.protocolbuffer.com
  port: 18333
  password: 4a3paxFKgSCxXBlaZn73Suc6AF3Dj3078l8FeDzDOXZOwyCDCICzeApyySAEgeTOSEZSZ
  params: 'allowInsecure: 0, sni: luber.protocolbuffer.com'
- name: Trojan-MYAwA
  type: trojan
  server: huzzah.meijireform.com
  port: 28331
  password: Aa4cexaO3FReREXgAlp9CjyTjpaRNan3YDx6DxaDYFS3On0SqgF08CZcBpYxy3awXeEIC
  params: 'allowInsecure: 0, sni: huzzah.meijireform.com'
- name: Trojan-6Vrze
  type: trojan
  server: 141.11.203.191
  port: 8443
  password: Aimer
  params: 'allowInsecure: 0, sni: epmw.ambercc.filegear-sg.me, type: ws, host: epmw.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-v8VR0
  type: trojan
  server: cutlery.homeofbrave.net
  port: 28331
  password: e3qTaj4gOeDDzR8lzYXpyZDpga5a3SCwyE4CO6c738aZxwlaaAD0SYSYyXOlF9S3FRF0x
  params: 'allowInsecure: 0, sni: cutlery.homeofbrave.net'
- name: Trojan-gej6k
  type: trojan
  server: closet.homeofbrave.net
  port: 18332
  password: BIRCauz5R2S8O3pZ56eg8yC43yla4T3D7znxCDFxSCODO9jA3NxAcaE3YYK3Sq8u9DxZg
  params: 'allowInsecure: 0'
- name: Trojan-L5ep9
  type: trojan
  server: 192.3.127.231
  port: 443
  password: Aimer
  params: 'allowInsecure: 0, sni: epmw.ambercc.filegear-sg.me, type: ws, host: epmw.ambercc.filegear-sg.me,
    path: /?ed=2560'
- name: Trojan-WrRDy
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: Trojan-P3A2E
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: Trojan-GMmHK
  type: trojan
  server: usla.mjt000.com
  port: 443
  password: e4af2638-bb12-4e4a-84f1-a032e23ca63f
  params: 'allowInsecure: 0, sni: usla.mjt000.com'
- name: Trojan-XsYez
  type: trojan
  server: fireplace.wireshop.net
  port: 28331
  password: Ye8uA37l3C9FwpCwBCuZBy4SqlKTapDXEDnCZFRKSNlZCRSy0I3Yc8DxayzOeO3xaxjjg
  params: 'allowInsecure: 0'
- name: SS-V9iD7
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
- name: SS-IWMYs
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: VMESS-Oq1r1
  type: vmess
  server: 183.236.51.38
  port: 41024
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-ahzlg
  type: vmess
  server: 183.236.51.38
  port: 30052
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-yQyCG
  type: vmess
  server: 754d8a58-swmcg0-sy0k9b-yjq0.hgc1.tcpbbr.net
  port: 8080
  uuid: 25b2699a-e18e-11ec-8e69-f23c91cfbbc9
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: 754d8a58-swmcg0-sy0k9b-yjq0.hgc1.tcpbbr.net
- name: VMESS-pMiSh
  type: vmess
  server: lt.fxlcn.com
  port: 45271
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-hAQ85
  type: vmess
  server: 120.232.153.63
  port: 37805
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-18qVS
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-Ij7dI
  type: vmess
  server: 507dabb3-swtr40-sxzp1j-1irfn.hgc1.tcpbbr.net
  port: 8080
  uuid: a33115b6-75fa-11ed-8826-f23c9164ca5d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-MpZYR
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 716eded6-2201-4dbd-9d63-1638c9e8e677
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: pendar.onthewifi.com
- name: VMESS-ClsS6
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-Ez8y9
  type: vmess
  server: hkt.gotochinatown.net
  port: 80
  uuid: 55cce5a4-56b7-11ee-af82-f23c9164ca5d
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-theMK
  type: vmess
  server: www.xinjuc.com
  port: 80
  uuid: 2f38f848-a899-4c87-9807-207a41615e3c
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /rongseven?ed=2048
    headers:
      Host: hk.freeyyds.dpdns.org
- name: VMESS-d7XB2
  type: vmess
  server: m11sdfg.890604.dpdns.org
  port: 80
  uuid: 0a28b420-4f7c-43ad-a29e-80068ce08263
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /lhU8ShsoPZlulnnYPb86csp
    headers:
      Host: m11sdfg.890604.dpdns.org
- name: VMESS-c6bng
  type: vmess
  server: 172.67.214.33
  port: 2082
  uuid: 2f821152-c3e9-4074-9185-2790e7425f42
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cs.flha.ru
- name: VMESS-xHqbL
  type: vmess
  server: a9316cd5-sx4v40-t1ppk8-1i3g8.hgc1.tcpbbr.net
  port: 8080
  uuid: 437cef58-f10b-11ef-8eaf-f23c9164ca5d
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-gSf7V
  type: vmess
  server: 104.21.96.1
  port: 8443
  uuid: 914584ee-3515-46ac-a09d-4677a2e9dc9a
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us01.sh-cloudflare.sbs
- name: Trojan-knqVv
  type: trojan
  server: pricing.protocolbuffer.com
  port: 18334
  password: lOY3KNXAR4jD2lpCaFDI3OygSZ67A8ClDSClZjYwaFpC5qcN2TDzTaIEFYOBx3yn034CZ
  params: ''
- name: Trojan-TEt0E
  type: trojan
  server: magnet.wireshop.net
  port: 443
  password: Eg4ZTOCSZcwl303ZnRaNIKKzaCCDlpOS26TAX7ReY8FR2ISgS3yx3DFaBSC85YqCEBaD9
  params: 'allowInsecure: 0'
- name: Trojan-6Cc7e
  type: trojan
  server: 36.156.102.124
  port: 15624
  password: RlzoEILU
  params: 'allowInsecure: 0, sni: 36.156.102.124'
- name: Trojan-aTAnL
  type: trojan
  server: 15.188.255.203
  port: 22223
  password: telegram-id-directvpn
  params: 'sni: trojan.burgerip.co.uk'
- name: Trojan-ttzPM
  type: trojan
  server: 15.188.255.203
  port: 22222
  password: telegram-id-privatevpns
  params: 'sni: trojan.burgerip.co.uk'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-UIEUu
  - SSR-FisPt
  - VMESS-MDCtI
  - SS-RCjZQ
  - SS-2RdoF
  - SS-uXZ5I
  - SS-RDxwz
  - SS-FnTqH
  - SS-4yIpi
  - SS-TZpPF
  - SS-zshYM
  - SS-FxK81
  - SS-VYIen
  - SS-4hxpm
  - SS-WgNDg
  - SS-WADaS
  - SS-Gd9jh
  - VMESS-c3j6F
  - VMESS-MQQAJ
  - VMESS-3MQ6H
  - VMESS-slqE9
  - VMESS-NegH3
  - VMESS-7U1Km
  - VMESS-jr9xx
  - VMESS-D9L8U
  - VMESS-pYWK7
  - VMESS-sMsc5
  - VMESS-pnY2f
  - VMESS-Hhixh
  - VMESS-pbsqZ
  - VMESS-xfD7q
  - VMESS-wtkbc
  - Trojan-fIcBN
  - Trojan-agERv
  - Trojan-iX7O6
  - Trojan-mvHZN
  - Trojan-7CDFF
  - Trojan-CKPsP
  - Trojan-V5iFM
  - Trojan-PROA9
  - Trojan-MYAwA
  - Trojan-6Vrze
  - Trojan-v8VR0
  - Trojan-gej6k
  - Trojan-L5ep9
  - Trojan-WrRDy
  - Trojan-P3A2E
  - Trojan-GMmHK
  - Trojan-XsYez
  - SS-V9iD7
  - SS-IWMYs
  - VMESS-Oq1r1
  - VMESS-ahzlg
  - VMESS-yQyCG
  - VMESS-pMiSh
  - VMESS-hAQ85
  - VMESS-18qVS
  - VMESS-Ij7dI
  - VMESS-MpZYR
  - VMESS-ClsS6
  - VMESS-Ez8y9
  - VMESS-theMK
  - VMESS-d7XB2
  - VMESS-c6bng
  - VMESS-xHqbL
  - VMESS-gSf7V
  - Trojan-knqVv
  - Trojan-TEt0E
  - Trojan-6Cc7e
  - Trojan-aTAnL
  - Trojan-ttzPM
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-UIEUu
  - SSR-FisPt
  - VMESS-MDCtI
  - SS-RCjZQ
  - SS-2RdoF
  - SS-uXZ5I
  - SS-RDxwz
  - SS-FnTqH
  - SS-4yIpi
  - SS-TZpPF
  - SS-zshYM
  - SS-FxK81
  - SS-VYIen
  - SS-4hxpm
  - SS-WgNDg
  - SS-WADaS
  - SS-Gd9jh
  - VMESS-c3j6F
  - VMESS-MQQAJ
  - VMESS-3MQ6H
  - VMESS-slqE9
  - VMESS-NegH3
  - VMESS-7U1Km
  - VMESS-jr9xx
  - VMESS-D9L8U
  - VMESS-pYWK7
  - VMESS-sMsc5
  - VMESS-pnY2f
  - VMESS-Hhixh
  - VMESS-pbsqZ
  - VMESS-xfD7q
  - VMESS-wtkbc
  - Trojan-fIcBN
  - Trojan-agERv
  - Trojan-iX7O6
  - Trojan-mvHZN
  - Trojan-7CDFF
  - Trojan-CKPsP
  - Trojan-V5iFM
  - Trojan-PROA9
  - Trojan-MYAwA
  - Trojan-6Vrze
  - Trojan-v8VR0
  - Trojan-gej6k
  - Trojan-L5ep9
  - Trojan-WrRDy
  - Trojan-P3A2E
  - Trojan-GMmHK
  - Trojan-XsYez
  - SS-V9iD7
  - SS-IWMYs
  - VMESS-Oq1r1
  - VMESS-ahzlg
  - VMESS-yQyCG
  - VMESS-pMiSh
  - VMESS-hAQ85
  - VMESS-18qVS
  - VMESS-Ij7dI
  - VMESS-MpZYR
  - VMESS-ClsS6
  - VMESS-Ez8y9
  - VMESS-theMK
  - VMESS-d7XB2
  - VMESS-c6bng
  - VMESS-xHqbL
  - VMESS-gSf7V
  - Trojan-knqVv
  - Trojan-TEt0E
  - Trojan-6Cc7e
  - Trojan-aTAnL
  - Trojan-ttzPM
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
