port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-xngZn
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-TTukx
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-opxat
  type: vmess
  server: 195.154.40.247
  port: 52602
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-jGwr6
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: VMESS-VLLnU
  type: vmess
  server: de01.sh-cloudflare.sbs
  port: 2096
  uuid: b3928f8d-ea81-4d75-bcec-4016a072adff
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: de01.sh-cloudflare.sbs
- name: VMESS-yOuiQ
  type: vmess
  server: 104.21.82.183
  port: 8880
  uuid: 5a7021e0-26b4-45d6-b175-fe551601ca97
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server26.beheshtbaneh.com
- name: VMESS-ZNA4t
  type: vmess
  server: 104.21.96.1
  port: 8443
  uuid: 914584ee-3515-46ac-a09d-4677a2e9dc9a
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us01.sh-cloudflare.sbs
- name: VMESS-ht2b4
  type: vmess
  server: 120.198.71.216
  port: 35921
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-9e5fS
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-1SzCT
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 118287d2-e968-42e1-80d0-12fa2f5d38d6
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: sahand.serveminecraft.net
- name: VMESS-a8c9j
  type: vmess
  server: tls.100.node-for-bigairport.win
  port: 56443
  uuid: 5ac8224f-6126-4ffb-9fad-97e3207f8c33
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: tls.100.node-for-bigairport.win
- name: VMESS-3TUlL
  type: vmess
  server: ip.sb
  port: 443
  uuid: cfa8c36c-9652-484a-89e1-34dcc98faac3
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /vmess?ed=2048
    headers:
      Host: cdn.3iapps.com
- name: VMESS-XCYfn
  type: vmess
  server: 120.232.153.63
  port: 37805
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-27Uu7
  type: vmess
  server: 120.198.71.216
  port: 52082
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-DamQy
  type: vmess
  server: 120.198.71.216
  port: 46759
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-IueXx
  type: vmess
  server: 120.232.153.40
  port: 43292
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-A1Tby
  type: vmess
  server: 120.198.71.219
  port: 51095
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-lm1pG
  type: vmess
  server: 132.145.232.171
  port: 443
  uuid: 9b456c2a-f2c1-45e1-87a9-b7628b04bb24
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /linkws
    headers:
      Host: beyonddsz.cfd
- name: VMESS-bNs9f
  type: vmess
  server: xxcvfrrt6.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: xxcvfrrt6.999820.xyz
- name: Trojan-PW1tY
  type: trojan
  server: 36.151.251.60
  port: 28296
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-xngZn
  - SSR-TTukx
  - VMESS-opxat
  - SS-jGwr6
  - VMESS-VLLnU
  - VMESS-yOuiQ
  - VMESS-ZNA4t
  - VMESS-ht2b4
  - VMESS-9e5fS
  - VMESS-1SzCT
  - VMESS-a8c9j
  - VMESS-3TUlL
  - VMESS-XCYfn
  - VMESS-27Uu7
  - VMESS-DamQy
  - VMESS-IueXx
  - VMESS-A1Tby
  - VMESS-lm1pG
  - VMESS-bNs9f
  - Trojan-PW1tY
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-xngZn
  - SSR-TTukx
  - VMESS-opxat
  - SS-jGwr6
  - VMESS-VLLnU
  - VMESS-yOuiQ
  - VMESS-ZNA4t
  - VMESS-ht2b4
  - VMESS-9e5fS
  - VMESS-1SzCT
  - VMESS-a8c9j
  - VMESS-3TUlL
  - VMESS-XCYfn
  - VMESS-27Uu7
  - VMESS-DamQy
  - VMESS-IueXx
  - VMESS-A1Tby
  - VMESS-lm1pG
  - VMESS-bNs9f
  - Trojan-PW1tY
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
