port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-4z9td
  type: ss
  server: 195.154.32.37
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SSR-FIaoL
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-dswFS
  type: vmess
  server: 195.154.40.247
  port: 31549
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: SS-Ufu0I
  type: ss
  server: 125.141.26.12
  port: 4857
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-nqHni
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-OduSS
  type: ss
  server: 3.38.139.172
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-IQjxM
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-Ds0dX
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-GmkWO
  type: ss
  server: 34.212.26.32
  port: 443
  cipher: aes-256-cfb
  password: awsps0501
- name: SS-0q873
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-kzE8i
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: SS-NweXM
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 15007
  cipher: aes-256-gcm
  password: Q5XH89ZLTSGOQASZ
- name: SS-estOd
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18010
  cipher: aes-256-gcm
  password: TF63RS7M0DB9OJ3B
- name: SS-4N51R
  type: ss
  server: 52.195.15.105
  port: 9898
  cipher: chacha20-ietf-poly1305
  password: 1a17b19d-4896-4531-af79-6e91d8ef8228
- name: SS-Nz3oB
  type: ss
  server: hkkh11v1.xpmc.cc
  port: 20273
  cipher: chacha20-ietf-poly1305
  password: 91a41f4e02dc
- name: SS-75Me7
  type: ss
  server: 43.226.17.17
  port: 14312
  cipher: chacha20-ietf-poly1305
  password: 2e96aa2f3054
- name: SS-CK3la
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: VMESS-rWQpS
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-wcFV4
  type: vmess
  server: 8.211.154.107
  port: 50951
  uuid: a3d04548-625c-4658-9ff0-f9a7835d1f6d
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-eXVrK
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-A2XSs
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-SmQGX
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-KCqPs
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-prBdP
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-QKPAC
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-L8p8J
  type: vmess
  server: 120.232.153.41
  port: 41597
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-bWEw9
  type: vmess
  server: 120.232.153.40
  port: 52182
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-heODg
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-mrAqJ
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-frAGF
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-jrF0g
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-RQ9D8
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: Trojan-XRCtU
  type: trojan
  server: bd8e9b7d-swzb40-t5vrf3-716s.cu.plebai.net
  port: 15229
  password: 088a0bbe-4f9f-11ea-a15d-f23c913c8d2b
  params: 'allowInsecure: 1, sni: bd8e9b7d-swzb40-t5vrf3-716s.cu.plebai.net'
- name: Trojan-ZQrc6
  type: trojan
  server: 36.151.251.62
  port: 13542
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-2VOb5
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: 36.151.251.61'
- name: Trojan-3yD2D
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: Trojan-W9DZg
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-Au7mI
  type: trojan
  server: 36.151.251.61
  port: 33097
  password: RlzoEILU
  params: 'allowInsecure: 1'
- name: Trojan-hGpwB
  type: trojan
  server: usla.mjt000.com
  port: 443
  password: e4af2638-bb12-4e4a-84f1-a032e23ca63f
  params: 'allowInsecure: 0, sni: usla.mjt000.com'
- name: Trojan-pOGCz
  type: trojan
  server: f5ada702-swb8g0-t5fh9u-1uni.cu.plebai.net
  port: 15229
  password: adbd0a82-3336-11ed-bd7c-f23c913c8d2b
  params: 'allowInsecure: 1'
- name: Trojan-CzVcY
  type: trojan
  server: 7d09e919-swq1s0-tcvn0z-1tlyg.cu.plebai.net
  port: 15229
  password: be8ba532-0dcf-11f0-9a65-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 7d09e919-swq1s0-tcvn0z-1tlyg.cu.plebai.net'
- name: Trojan-4m8tp
  type: trojan
  server: diagram.protocolbuffer.com
  port: 18334
  password: YaN8FFNe58nga3xAu3yTx0CSllcSeOnDZOj3SXROCz3S34B9D3F7Ka0aYa8yaxpXCDRKZ
  params: 'allowInsecure: 0'
- name: Trojan-P4U4H
  type: trojan
  server: bapus.koreanbbq.link
  port: 443
  password: 94Xn93e3F2uOxCE8De8upAAwnlI8ySRRj70Ol6zgYNBjZFCDK5Yaca3D8aT2qaxyEc0DK
  params: 'allowInsecure: 0'
- name: Trojan-BfbDY
  type: trojan
  server: 5f9d335d-swexs0-t5juhn-4tue.cu.plebai.net
  port: 15229
  password: fe506496-24eb-11ef-abd3-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 5f9d335d-swexs0-t5juhn-4tue.cu.plebai.net'
- name: Trojan-bIdIa
  type: trojan
  server: 36.151.251.62
  port: 3330
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: cdn.egvra.cn'
- name: Trojan-iw3lQ
  type: trojan
  server: 36.156.102.123
  port: 50723
  password: RlzoEILU
  params: 'allowInsecure: 1, sni: 36.156.102.123'
- name: Trojan-wBEYd
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 1, sni: 120.233.44.201'
- name: Trojan-X5LZz
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: SS-AEQNI
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-Zao0f
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15003
  cipher: aes-256-gcm
  password: 4KGHWKCKQAJOVPHO
- name: SS-aaNei
  type: ss
  server: 81.177.215.84
  port: 443
  cipher: chacha20-ietf-poly1305
  password: tihAgVxZO12u
- name: VMESS-hqKgy
  type: vmess
  server: ip.sb
  port: 443
  uuid: cfa8c36c-9652-484a-89e1-34dcc98faac3
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /vmess?ed=2048
    headers:
      Host: cdn.3iapps.com
- name: VMESS-7tj4z
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 716eded6-2201-4dbd-9d63-1638c9e8e677
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: pendar.onthewifi.com
- name: VMESS-2OE5L
  type: vmess
  server: xxxsde4.freevpnatm2025.dpdns.org
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: xxxsde4.freevpnatm2025.dpdns.org
- name: VMESS-EOUQ4
  type: vmess
  server: 5tghyu8.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: 5tghyu8.999820.xyz
- name: VMESS-9vlNJ
  type: vmess
  server: 104.21.82.183
  port: 8880
  uuid: 5a7021e0-26b4-45d6-b175-fe551601ca97
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server26.beheshtbaneh.com
- name: VMESS-A8Jho
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 2ff97c6d-8557-42a4-b43f-19c77c5959ea
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: irsoft.sytes.net
- name: VMESS-knK7O
  type: vmess
  server: 45.147.201.231
  port: 22060
  uuid: d68fe990-0352-49ef-a8f0-0bed118431c2
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-b06c8
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: Trojan-uBsui
  type: trojan
  server: 36.156.102.124
  port: 15624
  password: RlzoEILU
  params: 'allowInsecure: 0, sni: 36.156.102.124'
- name: Trojan-SVIgX
  type: trojan
  server: siwtno.coffeekit.net
  port: 443
  password: 7gZIq33OD6pxTR0SCK4z3IDElYCSe9lRFXaCaOT380eSuCe9yj8OFanXYADAA5B3BwK62
  params: ''
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-4z9td
  - SSR-FIaoL
  - VMESS-dswFS
  - SS-Ufu0I
  - SS-nqHni
  - SS-OduSS
  - SS-IQjxM
  - SS-Ds0dX
  - SS-GmkWO
  - SS-0q873
  - SS-kzE8i
  - SS-NweXM
  - SS-estOd
  - SS-4N51R
  - SS-Nz3oB
  - SS-75Me7
  - SS-CK3la
  - VMESS-rWQpS
  - VMESS-wcFV4
  - VMESS-eXVrK
  - VMESS-A2XSs
  - VMESS-SmQGX
  - VMESS-KCqPs
  - VMESS-prBdP
  - VMESS-QKPAC
  - VMESS-L8p8J
  - VMESS-bWEw9
  - VMESS-heODg
  - VMESS-mrAqJ
  - VMESS-frAGF
  - VMESS-jrF0g
  - VMESS-RQ9D8
  - Trojan-XRCtU
  - Trojan-ZQrc6
  - Trojan-2VOb5
  - Trojan-3yD2D
  - Trojan-W9DZg
  - Trojan-Au7mI
  - Trojan-hGpwB
  - Trojan-pOGCz
  - Trojan-CzVcY
  - Trojan-4m8tp
  - Trojan-P4U4H
  - Trojan-BfbDY
  - Trojan-bIdIa
  - Trojan-iw3lQ
  - Trojan-wBEYd
  - Trojan-X5LZz
  - SS-AEQNI
  - SS-Zao0f
  - SS-aaNei
  - VMESS-hqKgy
  - VMESS-7tj4z
  - VMESS-2OE5L
  - VMESS-EOUQ4
  - VMESS-9vlNJ
  - VMESS-A8Jho
  - VMESS-knK7O
  - VMESS-b06c8
  - Trojan-uBsui
  - Trojan-SVIgX
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-4z9td
  - SSR-FIaoL
  - VMESS-dswFS
  - SS-Ufu0I
  - SS-nqHni
  - SS-OduSS
  - SS-IQjxM
  - SS-Ds0dX
  - SS-GmkWO
  - SS-0q873
  - SS-kzE8i
  - SS-NweXM
  - SS-estOd
  - SS-4N51R
  - SS-Nz3oB
  - SS-75Me7
  - SS-CK3la
  - VMESS-rWQpS
  - VMESS-wcFV4
  - VMESS-eXVrK
  - VMESS-A2XSs
  - VMESS-SmQGX
  - VMESS-KCqPs
  - VMESS-prBdP
  - VMESS-QKPAC
  - VMESS-L8p8J
  - VMESS-bWEw9
  - VMESS-heODg
  - VMESS-mrAqJ
  - VMESS-frAGF
  - VMESS-jrF0g
  - VMESS-RQ9D8
  - Trojan-XRCtU
  - Trojan-ZQrc6
  - Trojan-2VOb5
  - Trojan-3yD2D
  - Trojan-W9DZg
  - Trojan-Au7mI
  - Trojan-hGpwB
  - Trojan-pOGCz
  - Trojan-CzVcY
  - Trojan-4m8tp
  - Trojan-P4U4H
  - Trojan-BfbDY
  - Trojan-bIdIa
  - Trojan-iw3lQ
  - Trojan-wBEYd
  - Trojan-X5LZz
  - SS-AEQNI
  - SS-Zao0f
  - SS-aaNei
  - VMESS-hqKgy
  - VMESS-7tj4z
  - VMESS-2OE5L
  - VMESS-EOUQ4
  - VMESS-9vlNJ
  - VMESS-A8Jho
  - VMESS-knK7O
  - VMESS-b06c8
  - Trojan-uBsui
  - Trojan-SVIgX
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
