port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-6qcwW
  type: ss
  server: freem.vidalith.com
  port: 31411
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-XNnL6
  type: ss
  server: freem.vidalith.com
  port: 31143
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-mxy71
  type: ss
  server: freem.vidalith.com
  port: 31213
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-dyx4Z
  type: ss
  server: freem.vidalith.com
  port: 31611
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-xdAB5
  type: ss
  server: freem.vidalith.com
  port: 31671
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-qL5Wp
  type: ss
  server: 43.226.17.11
  port: 40990
  cipher: chacha20-ietf-poly1305
  password: 60a930c17ff0
- name: SS-Bjxwl
  type: ss
  server: freem.vidalith.com
  port: 31245
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-WH1Kc
  type: ss
  server: freem.vidalith.com
  port: 31141
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-Mgemu
  type: ss
  server: freem.vidalith.com
  port: 31371
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-xgjWV
  type: ss
  server: freem.vidalith.com
  port: 31173
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-KgFML
  type: ss
  server: 18.183.219.5
  port: 443
  cipher: aes-256-cfb
  password: awsps0501
- name: SS-wHh1r
  type: ss
  server: freem.vidalith.com
  port: 31175
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-pxWzE
  type: ss
  server: freem.vidalith.com
  port: 31511
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-v7w0g
  type: ss
  server: 121.127.231.217
  port: 41099
  cipher: chacha20-ietf-poly1305
  password: 1450cecfb93f
- name: SS-be8FL
  type: ss
  server: freem.vidalith.com
  port: 31211
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-B0Yt7
  type: ss
  server: cn01.efan8867801.xyz
  port: 8774
  cipher: rc4-md5
  password: efanccyun
- name: SS-58c4d
  type: ss
  server: freem.vidalith.com
  port: 31571
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-fOddQ
  type: ss
  server: freem.vidalith.com
  port: 31441
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-KRSrb
  type: ss
  server: freem.vidalith.com
  port: 31311
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-bKvhd
  type: ss
  server: freem.vidalith.com
  port: 31541
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-jTpoL
  type: ss
  server: freem.vidalith.com
  port: 31722
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-XM13I
  type: ss
  server: freem.vidalith.com
  port: 31641
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-LZXm1
  type: ss
  server: 125.141.31.72
  port: 15098
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-q8MFM
  type: ss
  server: freem.vidalith.com
  port: 31171
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-wT4zK
  type: ss
  server: cn01.efan8867801.xyz
  port: 8766
  cipher: rc4-md5
  password: efanccyun
- name: SS-kkGHu
  type: ss
  server: freem.vidalith.com
  port: 31341
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-g6F49
  type: ss
  server: freem.vidalith.com
  port: 31741
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-0w3BA
  type: ss
  server: freem.vidalith.com
  port: 31111
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-by0v7
  type: ss
  server: freem.vidalith.com
  port: 31721
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-Gj8je
  type: ss
  server: freem.vidalith.com
  port: 31145
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-02jwa
  type: ss
  server: freem.vidalith.com
  port: 31313
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-wS1Bl
  type: ss
  server: p080.panda001.net
  port: 36379
  cipher: aes-256-cfb
  password: qwerREWQ@@
- name: SS-0gJJ2
  type: ss
  server: freem.vidalith.com
  port: 31215
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-c4YPQ
  type: ss
  server: freem.vidalith.com
  port: 31677
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-xPJbs
  type: ss
  server: freem.vidalith.com
  port: 31241
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-iX6SO
  type: ss
  server: 156.146.40.194
  port: 989
  cipher: aes-256-cfb
  password: f8f7aCzcPKbsF8p3
- name: SS-nNc08
  type: ss
  server: freem.vidalith.com
  port: 31113
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-vOKLZ
  type: ss
  server: freem.vidalith.com
  port: 31243
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-kpvtR
  type: ss
  server: 45.140.169.91
  port: 11111
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SS-2VO37
  type: ss
  server: freem.vidalith.com
  port: 31115
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SS-KRC9Q
  type: ss
  server: freem.vidalith.com
  port: 31471
  cipher: chacha20-ietf-poly1305
  password: aa25eab8-bba6-41ed-bcaa-8074972f42f8
- name: SSR-qkq0l
  type: ssr
  server: dongtaiwang5.com
  port: 42000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-6NdxX
  type: vmess
  server: 38.47.96.30
  port: 443
  uuid: 164a6ad0-476a-4bae-b78f-a3d37cf0f414
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /lzjjj
    headers:
      Host: th.lzj520hxw.dpdns.org
- name: VMESS-cUGJA
  type: vmess
  server: 120.232.153.40
  port: 31209
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-mnp1P
  type: vmess
  server: 9b53711d-sxlj40-szcxa1-dmd8.hkt.east.wctype.com
  port: 460
  uuid: 2058bdd6-1505-11f0-a035-f23c95b6f51d
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: a605477178.m.ctrip.com
- name: VMESS-cSrYr
  type: vmess
  server: tk.hzlt.tkddns.xyz
  port: 22643
  uuid: 98e96c9f-4bb3-39d4-9a2c-fac04257f7c7
  alterId: 2
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: zxjp-c.tkong.cc
- name: VMESS-DpfBP
  type: vmess
  server: 103.224.80.111
  port: 29992
  uuid: c3659582-a6e0-45c2-92ec-3b4d8b240e07
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-6g0zT
  type: vmess
  server: de.vmess.comnpmjs.com
  port: 443
  uuid: ceaaf653-9874-58c6-b100-092c01a1f73d
  alterId: 0
  cipher: auto
  tls: true
  network: grpc
  grpc-opts:
    path: vmess-grpc
    headers:
      Host: N/A
- name: VMESS-OhfCc
  type: vmess
  server: 195.154.40.247
  port: 30569
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-L5VMg
  type: vmess
  server: 183.238.90.8
  port: 46920
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-d9VWb
  type: vmess
  server: v37.heduian.link
  port: 30837
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: v37.heduian.link
- name: VMESS-hSaeh
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-ptJzK
  type: vmess
  server: 183.236.51.38
  port: 30052
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-PvzHO
  type: vmess
  server: 120.198.71.219
  port: 49355
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-uEZXi
  type: vmess
  server: bc842b49-swexs0-t1rt5e-1s09x.hgc1.tcpbbr.net
  port: 8080
  uuid: 62b7824e-47dc-11ef-9f2d-f23c9164ca5d
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: VMESS-UO7Zi
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-t5nLJ
  type: vmess
  server: v8.heduian.link
  port: 30808
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: v8.heduian.link
- name: VMESS-v9Sek
  type: vmess
  server: v24.heduian.link
  port: 30824
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: v24.heduian.link
- name: VMESS-TdwkC
  type: vmess
  server: 8.211.154.107
  port: 50951
  uuid: a3d04548-625c-4658-9ff0-f9a7835d1f6d
  alterId: 0
  cipher: auto
  tls: false
  network: kcp
  kcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-njXpe
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-G0vBB
  type: vmess
  server: v8.heduian.link
  port: 30808
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: v8.heduian.link
- name: VMESS-teuob
  type: vmess
  server: sslvpn.51job.com
  port: 1443
  uuid: a6a0d901-67e9-460a-90b5-634c5c4f9782
  alterId: 64
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    path: /634c5c4f9782
    headers:
      Host: centos7
- name: VMESS-RsZTL
  type: vmess
  server: v12.heduian.link
  port: 30812
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-ou1qL
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-LT0kw
  type: vmess
  server: 103.224.80.111
  port: 29992
  uuid: c3659582-a6e0-45c2-92ec-3b4d8b240e07
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-FuVlH
  type: vmess
  server: 183.238.90.8
  port: 39076
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-SITnX
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-J2gNy
  type: vmess
  server: 120.232.153.40
  port: 40550
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-i3MNO
  type: vmess
  server: 183.236.51.38
  port: 41024
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-6bNVP
  type: vmess
  server: 120.232.153.40
  port: 31209
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-uPHhG
  type: vmess
  server: 183.236.51.38
  port: 49291
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-mEGm9
  type: vmess
  server: 5tghyu8.999820.xyz
  port: 80
  uuid: 90f357dd-79ac-47c6-b0b8-958e2d19de07
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /10W6SJaK0F0oVXeNU6S2RVRP
    headers:
      Host: 5tghyu8.999820.xyz
- name: VMESS-2aNjo
  type: vmess
  server: 183.236.51.38
  port: 41024
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  tcp-opts:
    path: N/A
    headers:
      Host: N/A
- name: VMESS-RaPnc
  type: vmess
  server: v25.heduian.link
  port: 30825
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: v25.heduian.link
- name: Trojan-2n44m
  type: trojan
  server: 203.156.253.12
  port: 39001
  password: 85f133142f04dbf6547da33895cfabb3
  params: 'allowInsecure: 1, sni: www.yrtok.com'
- name: Trojan-NjhIN
  type: trojan
  server: 120.233.44.201
  port: 21179
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 0, sni: k30.tudou211.com'
- name: Trojan-GkEvp
  type: trojan
  server: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net
  port: 15229
  password: def14a51-e0d9-11ec-8429-f23c91cfbbc9
  params: 'allowInsecure: 1, sni: 4560c642-swin40-tjuq6l-wf62.cu.plebai.net'
- name: Trojan-zwKhB
  type: trojan
  server: 113.99.140.184
  port: 39001
  password: 85f133142f04dbf6547da33895cfabb3
  params: 'allowInsecure: 1, sni: www.yrtok.com'
- name: Trojan-J9PDg
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'sni: k28.tudou211.com'
- name: Trojan-nTTWZ
  type: trojan
  server: 154.83.2.54
  port: 2096
  password: d6b8011a-c725-435a-9fec-bf6d3530392c
  params: 'sni: vle.amclubsvip.dpdns.org, allowInsecure: 1, type: ws, path: /?ed=2560&PROT_TYPE=trojan,
    host: vle.amclubsvip.dpdns.org, fp: chrome'
- name: Trojan-Z9BaT
  type: trojan
  server: 120.233.44.201
  port: 21102
  password: 2b1ed981-6547-4094-998b-06a3323d6f6c
  params: 'allowInsecure: 0, sni: k28.tudou211.com'
- name: Trojan-yN2Gm
  type: trojan
  server: 125.94.40.221
  port: 39001
  password: 85f133142f04dbf6547da33895cfabb3
  params: 'allowInsecure: 1, sni: www.yrtok.com'
- name: Trojan-qPT5P
  type: trojan
  server: 13c2c931-swin40-swy6li-tni2.cu.plebai.net
  port: 15229
  password: 5e2f888c-68ef-11ef-96ca-f23c9164ca5d
  params: 'allowInsecure: 0, sni: 13c2c931-swin40-swy6li-tni2.cu.plebai.net'
- name: Trojan-1zMwH
  type: trojan
  server: 391907cc-swgsg0-t1bnjq-1krtb.cu.plebai.net
  port: 15229
  password: 60f6b4c4-9d70-11ed-a4d2-f23c9164ca5d
  params: 'allowInsecure: 0'
- name: Trojan-BVued
  type: trojan
  server: 120.233.128.68
  port: 39001
  password: 85f133142f04dbf6547da33895cfabb3
  params: 'allowInsecure: 1, sni: 120.233.128.68'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-6qcwW
  - SS-XNnL6
  - SS-mxy71
  - SS-dyx4Z
  - SS-xdAB5
  - SS-qL5Wp
  - SS-Bjxwl
  - SS-WH1Kc
  - SS-Mgemu
  - SS-xgjWV
  - SS-KgFML
  - SS-wHh1r
  - SS-pxWzE
  - SS-v7w0g
  - SS-be8FL
  - SS-B0Yt7
  - SS-58c4d
  - SS-fOddQ
  - SS-KRSrb
  - SS-bKvhd
  - SS-jTpoL
  - SS-XM13I
  - SS-LZXm1
  - SS-q8MFM
  - SS-wT4zK
  - SS-kkGHu
  - SS-g6F49
  - SS-0w3BA
  - SS-by0v7
  - SS-Gj8je
  - SS-02jwa
  - SS-wS1Bl
  - SS-0gJJ2
  - SS-c4YPQ
  - SS-xPJbs
  - SS-iX6SO
  - SS-nNc08
  - SS-vOKLZ
  - SS-kpvtR
  - SS-2VO37
  - SS-KRC9Q
  - SSR-qkq0l
  - VMESS-6NdxX
  - VMESS-cUGJA
  - VMESS-mnp1P
  - VMESS-cSrYr
  - VMESS-DpfBP
  - VMESS-6g0zT
  - VMESS-OhfCc
  - VMESS-L5VMg
  - VMESS-d9VWb
  - VMESS-hSaeh
  - VMESS-ptJzK
  - VMESS-PvzHO
  - VMESS-uEZXi
  - VMESS-UO7Zi
  - VMESS-t5nLJ
  - VMESS-v9Sek
  - VMESS-TdwkC
  - VMESS-njXpe
  - VMESS-G0vBB
  - VMESS-teuob
  - VMESS-RsZTL
  - VMESS-ou1qL
  - VMESS-LT0kw
  - VMESS-FuVlH
  - VMESS-SITnX
  - VMESS-J2gNy
  - VMESS-i3MNO
  - VMESS-6bNVP
  - VMESS-uPHhG
  - VMESS-mEGm9
  - VMESS-2aNjo
  - VMESS-RaPnc
  - Trojan-2n44m
  - Trojan-NjhIN
  - Trojan-GkEvp
  - Trojan-zwKhB
  - Trojan-J9PDg
  - Trojan-nTTWZ
  - Trojan-Z9BaT
  - Trojan-yN2Gm
  - Trojan-qPT5P
  - Trojan-1zMwH
  - Trojan-BVued
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-6qcwW
  - SS-XNnL6
  - SS-mxy71
  - SS-dyx4Z
  - SS-xdAB5
  - SS-qL5Wp
  - SS-Bjxwl
  - SS-WH1Kc
  - SS-Mgemu
  - SS-xgjWV
  - SS-KgFML
  - SS-wHh1r
  - SS-pxWzE
  - SS-v7w0g
  - SS-be8FL
  - SS-B0Yt7
  - SS-58c4d
  - SS-fOddQ
  - SS-KRSrb
  - SS-bKvhd
  - SS-jTpoL
  - SS-XM13I
  - SS-LZXm1
  - SS-q8MFM
  - SS-wT4zK
  - SS-kkGHu
  - SS-g6F49
  - SS-0w3BA
  - SS-by0v7
  - SS-Gj8je
  - SS-02jwa
  - SS-wS1Bl
  - SS-0gJJ2
  - SS-c4YPQ
  - SS-xPJbs
  - SS-iX6SO
  - SS-nNc08
  - SS-vOKLZ
  - SS-kpvtR
  - SS-2VO37
  - SS-KRC9Q
  - SSR-qkq0l
  - VMESS-6NdxX
  - VMESS-cUGJA
  - VMESS-mnp1P
  - VMESS-cSrYr
  - VMESS-DpfBP
  - VMESS-6g0zT
  - VMESS-OhfCc
  - VMESS-L5VMg
  - VMESS-d9VWb
  - VMESS-hSaeh
  - VMESS-ptJzK
  - VMESS-PvzHO
  - VMESS-uEZXi
  - VMESS-UO7Zi
  - VMESS-t5nLJ
  - VMESS-v9Sek
  - VMESS-TdwkC
  - VMESS-njXpe
  - VMESS-G0vBB
  - VMESS-teuob
  - VMESS-RsZTL
  - VMESS-ou1qL
  - VMESS-LT0kw
  - VMESS-FuVlH
  - VMESS-SITnX
  - VMESS-J2gNy
  - VMESS-i3MNO
  - VMESS-6bNVP
  - VMESS-uPHhG
  - VMESS-mEGm9
  - VMESS-2aNjo
  - VMESS-RaPnc
  - Trojan-2n44m
  - Trojan-NjhIN
  - Trojan-GkEvp
  - Trojan-zwKhB
  - Trojan-J9PDg
  - Trojan-nTTWZ
  - Trojan-Z9BaT
  - Trojan-yN2Gm
  - Trojan-qPT5P
  - Trojan-1zMwH
  - Trojan-BVued
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
