port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: SS-PwCy1
  type: ss
  server: 195.154.54.171
  port: 13355
  cipher: aes-256-gcm
  password: dongtaiwang.com
- name: SS-hLHqk
  type: ss
  server: 176.32.35.68
  port: 4018
  cipher: aes-256-gcm
  password: 4194ce5b1f36f660
- name: SS-FHbVr
  type: ss
  server: ti3hyra4.slashdevslashnetslashtun.net
  port: 18012
  cipher: aes-256-gcm
  password: N23FDU65EGHFL6OY
- name: SS-1VwZV
  type: ss
  server: 8tv68qhq.slashdevslashnetslashtun.net
  port: 15010
  cipher: aes-256-gcm
  password: ENYGONDU94UW1G6X
- name: SS-v7jfp
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
- name: SSR-6mWKP
  type: ssr
  server: dongtaiwang5.com
  port: 43000
  obfs: tls1.2_ticket_auth
  protocol: auth_chain_a
  cipher: chacha20-ietf
  password: dongtaiwang.com
- name: VMESS-idHad
  type: vmess
  server: 195.154.40.247
  port: 38952
  uuid: ade83fd4-5fe3-4862-8edf-be9eeb182435
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: www.bing.com
- name: VMESS-QHjmy
  type: vmess
  server: v32.heduian.link
  port: 30832
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-6xuS4
  type: vmess
  server: v9.heduian.link
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: baidu.com
- name: VMESS-38Huq
  type: vmess
  server: v5.heduian.link
  port: 30805
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-mt3Q9
  type: vmess
  server: 111.26.109.79
  port: 30828
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-R4sGH
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 118287d2-e968-42e1-80d0-12fa2f5d38d6
  alterId: 0
  cipher: none
  tls: true
  network: ws
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: sahand.serveminecraft.net
- name: VMESS-s3itP
  type: vmess
  server: lt.fxlcn.com
  port: 45291
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: ''
    headers:
      Host: ''
- name: VMESS-8rKUL
  type: vmess
  server: daf66faf-sub0g0-svavf6-ugw2.hk.p5pv.com
  port: 80
  uuid: 41d69b1e-cbf3-11ea-82ef-f23c9164ca5d
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-q3Tes
  type: vmess
  server: lt.fxlcn.com
  port: 45276
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-DTif6
  type: vmess
  server: v29.heduian.link
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /oooo
    headers:
      Host: ocbc.com
- name: VMESS-48qRZ
  type: vmess
  server: d514a957-sv2sg0-swfla6-1rdqg.hk.p5pv.com
  port: 80
  uuid: 2b57ec48-0da4-11ef-8f35-f23c913c8d2b
  alterId: 2
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-ZnNz6
  type: vmess
  server: 120.198.71.216
  port: 35921
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: none
  tls: false
  network: tcp
  tcp-opts:
    path: /
    headers:
      Host: ''
- name: VMESS-GzKeC
  type: vmess
  server: 104.21.82.183
  port: 8880
  uuid: 5a7021e0-26b4-45d6-b175-fe551601ca97
  alterId: 0
  cipher: none
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server26.beheshtbaneh.com
- name: Trojan-1dsLC
  type: trojan
  server: 104.21.112.1
  port: 443
  password: 84831b86-5c76-4173-bdf1-02fa3ed78a32
  params: 'security: tls, sni: eeERrrR.999815.xYZ, type: ws, host: eeerrrr.999815.xyz,
    path: /eS3prPmcpzbScA5VUAi1psm38Tz, fp: chrome, alpn: http/1.1'
- name: Trojan-VIE9E
  type: trojan
  server: 104.21.16.1
  port: 443
  password: 84831b86-5c76-4173-bdf1-02fa3ed78a32
  params: 'security: tls, sni: eeERrrR.999815.xYZ, type: ws, host: eeerrrr.999815.xyz,
    path: /eS3prPmcpzbScA5VUAi1psm38Tz, fp: chrome, alpn: http/1.1'
- name: Trojan-RHLz1
  type: trojan
  server: 198.62.62.4
  port: 443
  password: '12345678'
  params: 'security: tls, sni: 7bdfb97a.ikl.pages.dev, type: ws, host: 7bdfb97a.ikl.pages.dev,
    path: /7bdfb97a.ikl.pages.dev'
- name: Trojan-3kRrc
  type: trojan
  server: 63.178.35.184
  port: 22223
  password: telegram-id-directvpn
  params: 'sni: trojan.burgerip.co.uk'
- name: Trojan-8RqL6
  type: trojan
  server: 172.64.145.158
  port: 443
  password: 6884d714-d3c4-4b49-aa20-767ea92837d6
  params: 'security: tls, sni: icecream.955850.xyz, type: ws, host: icecream.955850.xyz,
    path: /proxyip=45.67.215.153:443&proxyIP=null, fp: randomized, alpn: h3'
proxy-groups:
- name: 自动选择
  type: url-test
  url: https://www.google.com
  interval: 300
  proxies:
  - SS-PwCy1
  - SS-hLHqk
  - SS-FHbVr
  - SS-1VwZV
  - SS-v7jfp
  - SSR-6mWKP
  - VMESS-idHad
  - VMESS-QHjmy
  - VMESS-6xuS4
  - VMESS-38Huq
  - VMESS-mt3Q9
  - VMESS-R4sGH
  - VMESS-s3itP
  - VMESS-8rKUL
  - VMESS-q3Tes
  - VMESS-DTif6
  - VMESS-48qRZ
  - VMESS-ZnNz6
  - VMESS-GzKeC
  - Trojan-1dsLC
  - Trojan-VIE9E
  - Trojan-RHLz1
  - Trojan-3kRrc
  - Trojan-8RqL6
- name: 节点选择
  type: select
  proxies:
  - 自动选择
  - SS-PwCy1
  - SS-hLHqk
  - SS-FHbVr
  - SS-1VwZV
  - SS-v7jfp
  - SSR-6mWKP
  - VMESS-idHad
  - VMESS-QHjmy
  - VMESS-6xuS4
  - VMESS-38Huq
  - VMESS-mt3Q9
  - VMESS-R4sGH
  - VMESS-s3itP
  - VMESS-8rKUL
  - VMESS-q3Tes
  - VMESS-DTif6
  - VMESS-48qRZ
  - VMESS-ZnNz6
  - VMESS-GzKeC
  - Trojan-1dsLC
  - Trojan-VIE9E
  - Trojan-RHLz1
  - Trojan-3kRrc
  - Trojan-8RqL6
- name: 国外媒体
  type: select
  proxies:
  - 节点选择
  - 自动选择
- name: 国内媒体
  type: select
  proxies:
  - DIRECT
  - 节点选择
rules:
- DOMAIN-SUFFIX,facebook.com,节点选择
- DOMAIN-SUFFIX,twitter.com,节点选择
- DOMAIN-SUFFIX,youtube.com,国外媒体
- DOMAIN-SUFFIX,netflix.com,国外媒体
- DOMAIN-SUFFIX,bilibili.com,国内媒体
- DOMAIN-SUFFIX,iqiyi.com,国内媒体
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,节点选择
