name: Update Clash Config

on:
  schedule:
    # 每2小时运行一次
    - cron: '0 */2 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-config:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: 安装依赖
        run: |
          cd clash
          pip install -r requirements.txt
          
      - name: 运行生成器脚本
        run: |
          cd clash
          python generator.py
          
      - name: 配置Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          
      - name: 提交更改
        run: |
          git add clash/gen_clash_config.yaml
          git diff --staged --quiet || git commit -m "更新Clash配置 [自动]" 
          
      - name: 推送更改
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 